### ISSUE TITLE
[EPIC] 2022 Q1 Cloud Connectors Release

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10147]
### Connectors

This section listed connectors with the highest priority and responsible persons:

- [x] Source: Salesforce - @antixar 
- [ ] https://github.com/airbytehq/airbyte/issues/10281 - @bazarnov 
- [x] https://github.com/airbytehq/airbyte/issues/10415 - @lazebnyi 
- [x] https://github.com/airbytehq/airbyte/issues/10803 - @grishick 
### Acceptance criteria

1. Each connector should have a separate document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
2. All available spreadsheets should be filled in based on the collected data by the following [link](https://airbyte.metabaseapp.com/)
3. In order to release to the Beta/GA requires additional development effort a separate issue(s) should be listed in the corresponding issue from the connectors section

**Comment by oustynova** [comment]
Close this one as far as we have separate Epics for each of the connectors
