### ISSUE TITLE
[EPIC] Destination BigQuery to GA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10148]
### Acceptance criteria

- [x] Connector should have a separate document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Collect and list all tech debt-related issues in the section below
- [x] #10758
- [x] Update connector documentation according to the comments in the checklist

### MLP section
- [ ] #9021
- [x] #11089
- [ ] #11090
- [ ] #12655
- [ ] #12658
- [ ] #12660

**Comment by misteryeo** [comment]
@alexandr-shegeda adding a few comments here:

1. Updated the title so it's explicit that this is an Epic for bringing the connector to GA. Let's follow this for other connectors too.
2. Updated the header from Tech Debt Issues to Outstanding Bugs just to be explicit. For the ones listed here, let's copy this to a separate epic for BigQuery Denormalized. This quarter, we won't have the bandwidth to merge BigQuery Denormalized with BigQuery so we should only be working on BigQuery non-denormalized connector issues if any.
3. MLP section looks good for now - @sherifnada is pulling together a [destination template for research](https://docs.google.com/document/d/1W_00iHc2Zy68LZzp2gze1JFalF7aOrWVjtzXP7uu1bw/edit#) similar to what we've been doing for sources to make sure there's no other features we need to add here.

**Comment by misteryeo** [comment]
@alexandr-shegeda for clarity - BigQuery we're bringing to GA. BigQuery De-normalized we're bringing to Beta first. Let's keep these two efforts separate. Once they're both in GA, we'll allocate time to merge them.

The [destination template is now complete](https://docs.google.com/document/d/1W_00iHc2Zy68LZzp2gze1JFalF7aOrWVjtzXP7uu1bw/edit#) as a first draft, can you give that a try to create a research doc for BigQuery and determine if there are more MLP criteria for BigQuery?

**Comment by alexandr-shegeda** [comment]
@misteryeo moved bigquery-denormalized related tickets into a separate issue #10579

**Comment by misteryeo** [comment]
@alexandr-shegeda Making sure we're aligned here - OAuth doesn't need to be completed, that's been documented and is sufficient for now. Please go ahead and wrap up the BigQuery checklist spreadsheet. I've added comments there. Thanks!

**Comment by terekete** [comment]
Will this be released with Oauth ?

**Comment by misteryeo** [comment]
No, we won't be releasing OAuth with GA @terekete

**Comment by terekete** [comment]
Is Oauth coming in a future release ? Reasoning I ask, not everyone in industry agrees to use service account keys.

**Comment by misteryeo** [comment]
@terekete Yep, we'll plan to implement OAuth in a future release but we don't have a set timeframe just yet. I'd added your request for us to keep track and will continue to take requests from other users of BigQuery as well to help us prioritize.

**Comment by sherifnada** [comment]
@alexandr-shegeda shouldn't this issue be closed? if i understand correctly the destination has been labelled as GA

**Comment by sherifnada** [comment]
@grishick to advise here -- my understanding is oauth shouldn't be part of GA but data types might be

**Comment by grishick** [comment]
@alexandr-shegeda per @misteryeo 's comment above, we can release BQ destination to GA w/o OAuth

**Comment by grishick** [comment]
Someone has already labeled BQ destination as GA
