### ISSUE TITLE
[EPIC] Source Shopify to Cloud

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10281]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1oUCKelveKttE3ZK5lqtuYtS1Yooc0yM_94DYm8I6Sn8/edit):

- [x] #10448
- [x] https://github.com/airbytehq/airbyte/pull/10794
- [ ] Support incremental deletes
- [x] https://github.com/airbytehq/airbyte/issues/10381
- [ ] #10817 (depends on https://github.com/airbytehq/airbyte-cloud/pull/1250)
- [x] https://github.com/airbytehq/airbyte/issues/11069
- [ ] deploy shopify to dev-cloud and get approval from Shopify for our oauth application
- [ ] revert https://github.com/airbytehq/airbyte/pull/10783

Outstanding Bugs
- [x] https://github.com/airbytehq/airbyte/issues/10379
- [x] https://github.com/airbytehq/airbyte/issues/10451
- [x] https://github.com/airbytehq/airbyte/issues/9976
- [x] https://github.com/airbytehq/airbyte/issues/10595

**Comment by bazarnov** [comment]
> * [ ]  Implement 'tender_transactions' stream
It's already there, inside of `Transactions` stream, providing both transaction details and the user bounded to the transaction per each `order_id`. 

> * [ ]  Support incremental deletes
Shopify does not provide the functionality to retrieve the removed records either using UI or using API calls.

Considering the answer, what are the future steps for this task?

**Comment by misteryeo** [comment]
Thanks @bazarnov - are you able to work with @ycherniaiev to ensure the [research](https://docs.google.com/document/d/1oUCKelveKttE3ZK5lqtuYtS1Yooc0yM_94DYm8I6Sn8/edit) document is updated to reflect the result of your investigation on `tender_transactions`?

@sherifnada any thoughts on the incremental deletes?

**Comment by bazarnov** [comment]
> Thanks @bazarnov - are you able to work with @ycherniaiev to ensure the [research](https://docs.google.com/document/d/1oUCKelveKttE3ZK5lqtuYtS1Yooc0yM_94DYm8I6Sn8/edit) document is updated to reflect the result of your investigation on `tender_transactions`?

We've already aligned yesterday on the daily meeting. This subject was discussed. The `tender_transactions` is the subset of 2 different data objects: Orders + Transactions, with the small amount of fields that `includes user_id`, `order_id` and `payment_details`, basically speaking it's a preset used in GraphQL to make an aggregated result, instead of joining 2 different tables afterwards. We already have `Orders`, `Transactions` as separate streams, the user can make all the mutations after the sync on their side.

**Comment by ycherniaiev** [comment]
> Thanks @bazarnov - are you able to work with @ycherniaiev to ensure the [research](https://docs.google.com/document/d/1oUCKelveKttE3ZK5lqtuYtS1Yooc0yM_94DYm8I6Sn8/edit) document is updated to reflect the result of your investigation on `tender_transactions`?
> 
> @sherifnada any thoughts on the incremental deletes?

@misteryeo @bazarnov Document is updated. _Tender_transactions_ is still a separate stream by Fivetran according to https://fivetran.com/docs/applications/shopify#schemainformation. So make a note.

**Comment by sherifnada** [comment]
@bazarnov @misteryeo for incremental deletes: I think we can get them [via webhooks](https://shopify.dev/api/admin-rest/2022-01/resources/webhook#top), but that's not going to happen by EOQ. So I think we should create a ticket with this context but consider it non-blocking for beta

**Comment by misteryeo** [comment]
Sounds good, let's move forward with this suggestion @bazarnov

**Comment by bazarnov** [comment]
UPDATE:

The https://github.com/airbytehq/airbyte/issues/10448 is implemented and merged into master last week.
The other thing: `Support incremental deletes` is not currently possible to implement, due to the fact that we don't have the possibility to track the removed records within the data. 

Is there anything else we should cover for the `Beta` status at this moment?

**Comment by misteryeo** [comment]
Updated the description to reflect some outstanding bugs @bazarnov

**Comment by bazarnov** [comment]
> https://github.com/airbytehq/airbyte/issues/10379
> https://github.com/airbytehq/airbyte/issues/10451

These 2 issues are related and should be fixed by:
https://github.com/airbytehq/airbyte/pull/10794

>  Source Shopify: KeyError during normalization #9976
This one is just the matter of updating the connector >= `0.1.31`

> https://github.com/airbytehq/airbyte/issues/10595
Not sure this is the actual issue at all. I've tested the sync, it was successful, I've also commented in this issue to describe the mechanism of child stream work.

**Comment by bazarnov** [comment]
Update: 

All listed `Outstanding Bugs` are resolved and merged into master.

**Comment by erica-airbyte** [comment]
@misteryeo Created [this issue](https://github.com/airbytehq/airbyte/issues/11069) for showing the correct connector phase label for Shopify

**Comment by sherifnada** [comment]
@bazarnov I've unassigned this issue from you pending completion of https://github.com/airbytehq/airbyte/issues/11334

**Comment by bazarnov** [comment]
> @bazarnov I've unassigned this issue from you pending completion of #11334

Ok, feel free to assign it back, once it's finished.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Shopify in GA](https://app.harvestr.io/components/0/list/BVBvE4Jmv)

**Comment by bazarnov** [comment]
@YowanR all the issues,  related to this Epic and all other small bugs that blocked us previously are resolved. The `source-shopify` is released as `alpha` to the Cloud and will remain, until moving to the `beta` is decided. We can now close this Epic as well.

**Comment by bazarnov** [comment]
The `source-shopify` has been released to Cloud as  `alpha`. This Epic could be closed now.
