### ISSUE TITLE
[EPIC] Salesforce Source to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10283]
- [ ] Investigation of streams supported by Airbyte https://github.com/airbytehq/airbyte/issues/10282

--
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1Z5wue_M3wKkWl667-aHLmtJd6IyyVNnoooUZzA0ucfA/edit#):

- [x] Support incremental deletes https://github.com/airbytehq/airbyte/issues/10155
- [x] improve check connection performance https://github.com/airbytehq/airbyte/issues/10405
- [x] edit docs after walkthrough https://github.com/airbytehq/airbyte/pull/10679

**Comment by bazarnov** [comment]
> * Implement 'to be determined' stream

Didn't find anything related to such a notion in SalesForce, could you please add more context here?

> *  ... other streams to be added

We fetch and handle all the possible & available streams dynamically based on:
- User `Role` & `Permissions` to `read` & `fetch` objects and their data (administration question)
- Whether or not, the stream has the `queryable` property is set to `true`, which means it's available for fetch the data, otherwise we will hit the `400 - bad request`, or `503 - forbidden` in response.
- No other restrictions applied, so we should have the full list of available streams as much as possible (both standard objects & custom ones along with standard and custom fields)

>  * Support incremental deletes

It's in progress here:
https://github.com/airbytehq/airbyte/issues/10155

**Comment by misteryeo** [comment]
1. Let's do exactly as you've proposed here and update the documentation.
2. "to be determined" was referring to the results of (1) :) 
3. To clarify, this means that for Salesforce we are technically already at parity with competitors because we handle all possible and available streams dynamically - is that accurate?
4. Great!

**Comment by bazarnov** [comment]
> 1. Let's do exactly as you've proposed here and update the documentation.

We've communicated this part with the assignee of https://github.com/airbytehq/airbyte/issues/10155, this should be corrected with PR coming.

> 3. To clarify, this means that for Salesforce we are technically already at parity with competitors because we handle all possible and available streams dynamically - is that accurate?

Yes.

**Comment by sherifnada** [comment]
@antixar will be away from the project for an indeterminate time due to the Russia-Ukraine war :( 

I continued his work on #10405 and closed that PR. We should be able to proceed with this issue.

**Comment by sherifnada** [comment]
I believe all requirements have been fulfilled, now only a UX walkthrough is needed
