### ISSUE TITLE
[EPIC] Stripe Source to Beta

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10284]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1qltg3eKLvjVK0cPel7SiptVRrytPhRwqjBSEc4WLJlc/edit#):

Merge documentation changes:
- [x]  https://github.com/airbytehq/airbyte/pull/11286

Improvements: 
- [ ] Document 'payouts_transactions' stream
- [ ] Document 'apple_domain' stream
- [ ] Document #10498
- [ ] Document #10499
- [ ]  Support incremental deletes https://github.com/airbytehq/airbyte/issues/10153

**Comment by bazarnov** [comment]
> * Implement 'payouts_transactions' stream

This stream is the part of the connector already called: `Payouts`.
The is no other resources called 'payouts_transactions' found in documentation of Stripe, could you please provide more information about where have you seen such a stream?

**Comment by bazarnov** [comment]
> 1. Karina had mentioned that Fivetran supported this in addition to Transactions.

I've checked the code of the tap that Fivetran & Stitch are using, this "pseudo-stream" is just the subset of the BalanceTransactions stream. Here is the code part: 
1) https://github.com/singer-io/tap-stripe/blob/a04bfa1e507b0d75e4680392e1ccbee96dffa7df/tap_stripe/__init__.py#L42
2) https://github.com/singer-io/tap-stripe/blob/a04bfa1e507b0d75e4680392e1ccbee96dffa7df/tap_stripe/__init__.py#L90

> 2. Karina had mentioned Stitch supported this - so let's find out what's been miscommunicated here in terms of what Stitch is supporting if this isn't a stream.

I believe there is no miscommunication here, this information was scrapped from their official documentation, but there is no mention that such a stream exists in singer/tap, as well as no information in official documentation of Stripe.

> 3. @sherifnada thoughts on getting accounts upgraded in order to be able to implement premium streams? In this case, for issuing?

Would be super great!

> 4. Karina mentioned that replicating incremental deletes is supported by both Stripe natively as well as by Fivetran in the research - can you clarify with her first?

I will align with our Unblockers, so we could deep dive into this research once again)

**Comment by misteryeo** [comment]
Great!

So then for (1) and (2) lets make sure we update the research doc to reflect these new findings.

We can wait for Sherif on (3).

**Comment by sherifnada** [comment]
Upgrading the stripe account requires a business verification so they enable card issuing functionality. 

@bazarnov do you know if we're able to hit those endpoints in the test mode? It seems I can hit it by running the following API call: 

```
➜  airbyte git:(sherif/connector-labels) ✗ curl https://api.stripe.com/v1/issuing/disputes \
  -u REDACTED: \
  -d limit=3 \
  -G
{
  "object": "list",
  "data": [

  ],
  "has_more": false,
  "url": "/v1/issuing/disputes"
}
```

I can do the business verification if needed (Most of it is done already but we need to link a bank account to Stripe as they don't have a concept of a "full" sandbox). But just checking if it's necessary.

**Comment by bazarnov** [comment]
I was able to reach the `issuing/disputes` + `issuing/cards` endpoint using `API LIVE Key` + `Host Site Password` from LastPass, but I don't know where this Live API Key comes from, probably the account standing behind this Key has the access to the target endpoints we need:

Input:
```
curl https://api.stripe.com/v1/issuing/disputes \
  -u sk_live_51......Mv.....Xk3 \
  -d limit=3 \
  -G
```

Output:
```
{
  "object": "list",
  "data": [

  ],
  "has_more": false,
  "url": "/v1/issuing/disputes"
}
```

Well, in the testing mode, we can try to reach out those endpoints and add them to the source-connector.

**Comment by bazarnov** [comment]
Update: 

Those two PRs are implemented and could be merged:

1. https://github.com/airbytehq/airbyte/issues/10498
2. https://github.com/airbytehq/airbyte/issues/10499

However, we need to enable `Issuing` functionality for at least `acct_1G9HZLIEn5WyEQxn` account we are using for tests at this very moment, for now we're hitting `403` using existing credentials for `issuing`-like streams. So I believe we do need the business verification in this case.

**Comment by sherifnada** [comment]
@bazarnov i submitted for business verification with stripe so hopefully we get it soon

**Comment by sherifnada** [comment]
@bazarnov please drop any new streams from the scope of certifying Stripe as beta. The business certification from Stripe is taking too long. Let's skip and certify without anything blocked on those streams.

**Comment by bazarnov** [comment]
@sherifnada @misteryeo 
Based on the epic's description and the investigation afterwards (https://github.com/airbytehq/airbyte/issues/10284#issuecomment-1042899728), there is nothing to implement or fix so far, we just moving on with [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1wCPX3eBBPFRI5sMeK4LBjooDs3bFpAa9Fr2os0S0P3g/edit#gid=1288588270) and fill-in the relevant information into it.

**Comment by misteryeo** [comment]
The spreadsheet has been reviewed by product - please proceed to review @bazarnov

**Comment by misteryeo** [comment]
What are we missing to finalize this @bazarnov?

**Comment by bazarnov** [comment]
We need to review this changes: https://github.com/airbytehq/airbyte/pull/11286
Publish and merge that PR, we should good to go, afterwards.

**Comment by misteryeo** [comment]
Reviewed @bazarnov - I think we're pretty close to going live here. Added [a template in the checklist](https://docs.google.com/spreadsheets/d/1wCPX3eBBPFRI5sMeK4LBjooDs3bFpAa9Fr2os0S0P3g/edit?disco=AAAAWh4dVow) for you once everything's been deployed.
