### ISSUE TITLE
[EPIC] Github Source to Beta

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10280]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1GPrZjW6Y6zL-BE2_id0zCp2AGTWCLzwcYuXVLT2s66A/edit#):
- [x] Document issue for adding 'deployments' stream
- [x] Document issue for adding 'project_cards' stream
- [x] Document issue for adding 'project_columns' stream
- [x] Document issue for adding 'pr_commits' stream
- [x] Document issue for adding 'pull_requests_reviews' stream
- [x] https://github.com/airbytehq/airbyte/issues/10965
- [x] https://github.com/airbytehq/airbyte/issues/11211

Outstanding Bugs
- https://github.com/airbytehq/airbyte/issues/10555

**Comment by misteryeo** [comment]
@grubberr when you document the issue of MLP feature gaps in the list above, can you make sure to link the issue back into the description of this epic? Thank you!

**Comment by grubberr** [comment]
@misteryeo Because we decided to implement new features on next steps I have moved all notes and open issues to new
[EPIC] Github Source to GA https://github.com/airbytehq/airbyte/issues/11387

is it ok?

**Comment by misteryeo** [comment]
@grubberr moving to a new GA epic is fine - but just want to make sure that you're actually documenting the MLP feature gaps as separate issues and linking them like we did here for Hubspot: https://share.getcloudapp.com/JruOqQlK
