### ISSUE TITLE
[EPIC] Fix database connection leak

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#10386]
## Summary
Some of the `JdbcDatabase` methods return a stream embedded with a database connection. The connection can only be closed when the consumption of the stream is done (in an `onClose` callback), and the closure is not automatic. There are use cases that do not manually close those streams. This is not an intuitive operation because most Java streams do not require closure, as they are not involved with resources.

## Tasks
- [x] https://github.com/airbytehq/airbyte/issues/10129
- [ ] Try Sentry JDBC profiling to monitor production connection usage
- [x] https://github.com/airbytehq/airbyte/issues/10128

**Comment by evantahler** [comment]
Appears to be complete.  We can re-open if required
