### ISSUE TITLE
[EPIC] Facebook Marketing Source to Beta

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#10415]
[MLP](https://docs.google.com/document/d/1lQlxwLt22CFMAG3qTWYn4MpRSi2XCLQVqEkb0XeqBeA/edit#) improvements:
- [ ] #9842 - Facebook Marketing Source: Support "Replicate Incremental Deletes"
- [ ] #9840 - Facebook Marketing Source: Add "Ad Account" stream
- [ ] #6226 - Facebook Marketing Source: Add "Ad Image" stream

Engineering Acceptance Criteria:
- [ ] Facebook Marketing Source have at least 90% unit test coverage

**Comment by sherifnada** [comment]
FYI @lazebnyi #8060 is not a connector issue, it's a platform issue. I crossed it out from the checklist above.

**Comment by misteryeo** [comment]
@lazebnyi This potential bug was surfaced for Facebook Marketing - can we take a look this week please? Added it to the list in description: https://github.com/airbytehq/airbyte/issues/10629#issuecomment-1053726988

**Comment by lazebnyi** [comment]
Successfully certified to GA - https://docs.google.com/spreadsheets/d/17_0unX7j1lXk5lMsJUzJYQdUoPZCDaMlO2svtKfBcLc
