### ISSUE TITLE
[EPIC] Destination BigQuery Denormalized to BETA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10579]
### Acceptance criteria

- [x] Connector should have a separate document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Collect and list all tech debt-related issues in the section below

### Outstanding Bugs
- [ ] #9345 
- [ ] #8870
- [ ] #5912
- [ ] #8209 
- [ ] #8586 
- [ ] #8895

### MLP section
- [ ] Destination BigQuery-Denormalized: improve check connection performance

**Comment by misteryeo** [comment]
Let's deprioritize https://github.com/airbytehq/airbyte/issues/9345 - that won't be a blocker to bring this connector to beta or GA. Thanks @alexandr-shegeda!

**Comment by misteryeo** [comment]
@alexandr-shegeda Reviewed checklist.
