### ISSUE TITLE
[EPIC] Google Ads Source to Beta

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#10786]
* [x] Check that all streams pass acceptance tests
* [x] #10787
  * https://github.com/airbytehq/airbyte/issues/10662
  * https://github.com/airbytehq/airbyte/issues/10392 - waiting on additional info from user
  * https://github.com/airbytehq/airbyte/issues/9886
  * https://github.com/airbytehq/airbyte/issues/9438
* Add the blockers to the current sprint; fix them
* [x] https://github.com/airbytehq/airbyte/issues/10964
  * [x] Fix check_connection error handling
* [x] Check the docs
  * [x] https://github.com/airbytehq/airbyte/issues/3394
* [x] Check featureset
  * Created https://github.com/airbytehq/airbyte/issues/11510
* [x] Final preflight checks

**Comment by edgao** [comment]
@misteryeo this is how errors from the "test connection" button get displayed, is this something that needs to be fixed before beta? (note the `\\\` and `\n`)

![Screen Shot 2022-03-16 at 11 49 55 AM](https://user-images.githubusercontent.com/5741425/158665148-6a4ca378-2fe9-4574-b89e-11bcc5c6b197.png)

**Comment by misteryeo** [comment]
Ooh, thanks for surfacing this. We should definitely fix this - do you know if this is just how we're parsing the error returned from Google Ads API directly?

Or would this parsing issue go across all connectors?

@sherifnada feels like we should add this to the checklist when certifying. WDYT?

**Comment by sherifnada** [comment]
If I had to guess, the problem is that because this is rendered as HTML, newlines expressed as `\n` are not rendered correctly because they need to be expressed using `<br />`. This seems to me like something the UI should address? Sort of like a "string to HTML text" conversion? 

WDYT @timroes

**Comment by edgao** [comment]
I was more thinking that the connector should extract the error message rather than just converting the raw api response to a string and dumping that into the UI. Haven't looked super closely at this, but it seems doable (and much more in-scope than a UI change)

**Comment by sherifnada** [comment]
@edgao ah got it -- seems simple enough. Works with me

**Comment by timroes** [comment]
@sherifnada As you mentioned `\n` isn't working because even if we render it in HTML it's not causing a line break. While `<br />` should be working I'd in general highly discourage trying to use it explicitly (like in connector specs), since it usually means you make assumption about layout, which you should not try to do on the backend side.

In this specific case where we're rendering JSON that's now not correctly formatted, I'd go with @edgao: We should try not to have JSON rendered in a string error message. No matter whether we'll get newlines to work or not, this will look horrible in the UI. We should rather shorten it into a human readable error, and if we want to have the full benefit of the JSON still available in the UI, we should have this as a separate field and actually render it dedicated in the UI in some modal/tooltip/etc as advanced information.

**Comment by edgao** [comment]
new issues for the streams that fivetran supports that we currently do not:

* https://github.com/airbytehq/airbyte/issues/11530
* https://github.com/airbytehq/airbyte/issues/11531
* https://github.com/airbytehq/airbyte/issues/11532
* https://github.com/airbytehq/airbyte/issues/11533
* https://github.com/airbytehq/airbyte/issues/11534
* https://github.com/airbytehq/airbyte/issues/11535
* https://github.com/airbytehq/airbyte/issues/11536
* https://github.com/airbytehq/airbyte/issues/11537
* https://github.com/airbytehq/airbyte/issues/11538
* https://github.com/airbytehq/airbyte/issues/11539
* https://github.com/airbytehq/airbyte/issues/11540
* https://github.com/airbytehq/airbyte/issues/11541
* https://github.com/airbytehq/airbyte/issues/11542
* https://github.com/airbytehq/airbyte/issues/11543
* https://github.com/airbytehq/airbyte/issues/11544
* https://github.com/airbytehq/airbyte/issues/11545
* https://github.com/airbytehq/airbyte/issues/11546
* https://github.com/airbytehq/airbyte/issues/11547
* https://github.com/airbytehq/airbyte/issues/11548
* https://github.com/airbytehq/airbyte/issues/11549
* https://github.com/airbytehq/airbyte/issues/11550
* https://github.com/airbytehq/airbyte/issues/11551
* https://github.com/airbytehq/airbyte/issues/11552
* https://github.com/airbytehq/airbyte/issues/11553
* https://github.com/airbytehq/airbyte/issues/11554
* https://github.com/airbytehq/airbyte/issues/11555
* https://github.com/airbytehq/airbyte/issues/11556
* https://github.com/airbytehq/airbyte/issues/11557
* https://github.com/airbytehq/airbyte/issues/11558
* https://github.com/airbytehq/airbyte/issues/11559
* https://github.com/airbytehq/airbyte/issues/11560
