### ISSUE TITLE
[EPIC] Source Hubspot to Beta

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10804]
###  According to [checklist](https://docs.google.com/spreadsheets/d/1jlmHGuAAsLZ9Xr5KpzUMK9yMSO-2qd5ZhqxxkrH66nY/edit#gid=1288588270):

- [MLP](https://docs.google.com/document/d/1KOiJT6hENQTOdNI2DGgMDRTD2JV0NBLOU3uxRyhE42w/edit#) improvements:

   - [x] Document issue for adding email_subscription: https://github.com/airbytehq/airbyte/issues/11123
   - [x] Document issue for adding contact_identity_profile: https://github.com/airbytehq/airbyte/issues/11170
   - [x] Document issue for adding identity_profile_identity: https://github.com/airbytehq/airbyte/issues/11169
   - [x] Research and understand how Fivetran supports ‘Capture merges’ and document as an issue: https://github.com/airbytehq/airbyte/issues/11178
   - [x] Research and understand how Fivetran supports ‘Replicate incremental deletes’ and document as an issue: https://github.com/airbytehq/airbyte/issues/11179
  
- Engineering Acceptance Criteria:

   - [x] Unit test coverage https://github.com/airbytehq/airbyte/issues/11120

- All outstanding bug reports blocking GA:

   - [X] Docs parity: https://github.com/airbytehq/airbyte/issues/10533
   - [X] Review this contribution: https://github.com/airbytehq/airbyte/pull/10700 
   - [X] Cast numerical value: https://github.com/airbytehq/airbyte/issues/10463 
   - [x] KeyError https://github.com/airbytehq/airbyte/issues/11306

- Label connector as GA in cloud:

   - [x]  [label hubspot as Beta in the UI](https://github.com/airbytehq/airbyte-cloud/blob/61195b703db231a43300f9e34f31468e1988469c/airbyte-bootloader-wrapped/src/main/resources/seed/source_definitions.yaml#L271)

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by misteryeo** [comment]
@girarda Product/UX pieces in checklist completed.

**Comment by lazebnyi** [comment]
Successfully certified to Beta - https://docs.google.com/spreadsheets/d/1jlmHGuAAsLZ9Xr5KpzUMK9yMSO-2qd5ZhqxxkrH66nY
