### ISSUE TITLE
expose oauth as the only available auth option for shopify in cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10817]
Once #10381 is completed, we want to implement a middle layer for shopify which hides the API key auth and only exposes Oauth. 

Context for why this is important is here https://github.com/airbytehq/airbyte/issues/8633#issuecomment-1053849175

## Acceptance Criteria
- [x] Shopify exposes oauth as the only available auth method in cloud
- [x] Shopify app install endpoint https://github.com/airbytehq/airbyte/issues/11299
- [ ] Airbyte app is approved by Shopify (https://github.com/airbytehq/airbyte/issues/11334)
- [ ] Shopify source is available for all workspaces (https://github.com/airbytehq/airbyte/issues/11241)
- [ ] any existing shopify users in cloud have been migrated to use oauth

### note on migrating existing customers
there is a bit of a deadlock issue here. Shopify is not giving us the approval to use oauth because we exposed API key auth previously. So to get approved for oauth, we need to disable API key auth, request approval, THEN our customers will be able to use shopify auth. 

This means that between disabling API key auth, and getting approved for oauth, those customers' connections will be in limbo (because we will have implemented the config/spec transformation logic for that connector). Theoretically, though, as long as they don't _update_ their source connector, API key auth should continue working fine. 

Once we get approved for oauth we should ask them to re-auth their shopify connector 

To find all sources using shopify run `select * from actor where actor_definition_id = '9da77001-af33-4bcd-be46-6252bf9342b9'` against the prod db.

**Comment by sherifnada** [comment]
@girarda this may be an easy win after #10381 as it unlocks releasing Shopify (an EOQ targeted connector) in cloud

**Comment by girarda** [comment]
The first step should be ready for review when I'm done testing it in dev
