### ISSUE TITLE
Source Facebook Marketing: Add new type CampaignsInsights

### ISSUE THREAD

**Issue by valerioditinno** [airbytehq/airbyte#10848]
## Summary

It would be nice if the Source was capable of syncing the following table and its data: [CampaignInsights](https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/insights/)

## TODOs
(Complete the TODOs based on the instruction, and convert each bullet point with the `[Issue]` tag into an issue.)
- [ ] [Issue] Add a new destination acceptance test (DAT) test case for this type.
- List every destination below, either update the destination to suppor this type, or override its DAT to bypass the new test case.
  - [ ] Example: [Issue] support <type-name> in destination bigquery
- [ ] [Issue] Make sure every destination can pass the new DAT test case.
  - Even if a destination does not need to support this type, its DAT should not break.
- List every source that should support this type below.
  - [ ] Example: [Issue] support <type-name> in source github

## Desired Timeline

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
