### ISSUE TITLE
[EPIC] Perform self-healing operations on temporal workflows that are in an unexpected terminal state

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#10931]
## What

Temporal can ends in a state where the previous workflow either failed or didn't continue as new because of a bug. This is not an expected state but it can happen. In order to be able to improve the reliability of the temporal workflow, we need to be able to perform operation from this state.
Those operations need to start a new workflow and then send a signal. Temporal provides [helper](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java#L237) for that.

The operation that need to be perform are (They are order by priority, the manual sync, reset and update have the same priority):
- [x] https://github.com/airbytehq/airbyte/issues/11214
  -  Delete: delete the connection (TBD: Cancel all non-terminal running jobs)
- [ ] https://github.com/airbytehq/airbyte/issues/11217
  - Cancel: cancel all the running jobs and the related attempts. Then continue as new.
- [ ] https://github.com/airbytehq/airbyte/issues/11213
  - Manual sync: create a new workflow that won't wait.
- [x] https://github.com/airbytehq/airbyte/issues/11215
  - Update: Start a new workflow as if it was the first run.
- [ ] https://github.com/airbytehq/airbyte/issues/11216
  - Manual reset: Start a new workflow that performs a reset.

## DoD

New signal methods are a implemented and tested to handle the scenario describe in the issue.

**Comment by pmossman** [comment]
Grooming notes:
- Currently, we need to manually restart a workflow to allow users to perform operations on a Connection
- Instead, we want to always respect the user's intent, regardless of workflow state
- Depends on: forbidding actions on a deleted Connection

Requires updates to the temporal workflow, like an activity to fetch jobs and forcibly cancel, plus internal state cleanup. Try to get back to a normal run.

Temporal State machine doc is in review, will be helpful for guiding this ticket.

Benoit will break this issue into smaller tasks that can be worked on by multiple team members, to help share temporal context.

Question: without doing this, what happens today? Answer: much manual manipulation via tctl. After this ticket, user actions should "self-heal" the workflow.
