### ISSUE TITLE
[EPIC] Source Intercom to Beta

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10936]
### According to [checklist](https://docs.google.com/spreadsheets/d/1cyhhbNXoCdYo1OnJ_cAeRvBnoAombKnCwidtPZOff8U/edit#gid=1288588270):

- [MLP](https://docs.google.com/document/d/1sKtGFXx_BXTlgdJyvjaZosBScLsTCMmFQ1TRbQucTXc/edit#heading=h.22fd5raysmm3) improvements:

   - [x]  https://github.com/airbytehq/airbyte/issues/11366
  
- Engineering Acceptance Criteria:

   - [x] https://github.com/airbytehq/airbyte/issues/11364

- All outstanding bug reports blocking GA:

   - [x] #11177 
   - [x] #10250 
   - [x]  https://github.com/airbytehq/airbyte/issues/9572 - confirm that linked PRs closes this, otherwise dig into this issue

- Label connector as GA in cloud:
   - [x] https://github.com/airbytehq/airbyte-cloud/pull/1026

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by misteryeo** [comment]
@lazebnyi checklist reviewed!

**Comment by lazebnyi** [comment]
Successfully certified to Beta - https://docs.google.com/spreadsheets/d/1cyhhbNXoCdYo1OnJ_cAeRvBnoAombKnCwidtPZOff8U
