### ISSUE TITLE
[EPIC] Source Zendesk Support to Cloud Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#11021]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/179CgrB6Mc6TCad8BoAoYLkEt7BsVdW9boIdvauTg6OQ/edit?usp=sharing) within [this issue](https://github.com/airbytehq/airbyte/issues/10035):

- [x] check if all requirements are satisfied
- [x] create [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1QhyQzvcM6uOB8hmVv55gS4oRovDe8bapXVwj7nTTll0/edit#gid=1288588270) for release checklist and tag Andy for UX run through
- [x] #11416
- [x] #11688 

Outstanding bugs:

- [x] https://github.com/airbytehq/airbyte/issues/6285
- [x] https://github.com/airbytehq/airbyte/issues/8519
- [x] https://github.com/airbytehq/airbyte/issues/10613
- [x] https://github.com/airbytehq/airbyte/pull/11727

Needs confirmation the issue is no longer present:

- [ ] https://github.com/airbytehq/airbyte/issues/11035

**Comment by bazarnov** [comment]
About bugs:
1) https://github.com/airbytehq/airbyte/issues/8519 - waiting for customer’s reply or PR as contribution to continue working on it.
2) https://github.com/airbytehq/airbyte/issues/6285 - there is a half-ready PR by @antixar, I think we will leverage this to release the OAuth2.0 functionality and close this dependency.

**Comment by bazarnov** [comment]
@misteryeo 
Please take a look at https://docs.google.com/spreadsheets/d/1QhyQzvcM6uOB8hmVv55gS4oRovDe8bapXVwj7nTTll0/edit#gid=1288588270 MLP doc for Zendesk Support, for review.

**Comment by misteryeo** [comment]
Hey @bazarnov I was just about to review this but realized it's not in Cloud yet. So I can't start the UX/Docs review.

**Comment by bazarnov** [comment]
> Hey @bazarnov I was just about to review this but realized it's not in Cloud yet. So I can't start the UX/Docs review.

@misteryeo 
Here is the [PR](https://github.com/airbytehq/airbyte-cloud/pull/1261) fixes this. Once it merged and new OSS Release is out, we can get back to review, I believe.

**Comment by bazarnov** [comment]
@misteryeo 
The source Zendesk Support is released to Cloud Prod and oAuth flow is tested. Please proceed with your review. Thank you.

**Comment by bazarnov** [comment]
The last outstanding bug: https://github.com/airbytehq/airbyte/issues/11035 is no longer the issue, it should be covered by the `0.2.2` version of `source-zendesk-support`. More info here: https://github.com/airbytehq/airbyte/issues/11035#issuecomment-1084214386

**Comment by misteryeo** [comment]
Checklist reviewed @bazarnov

**Comment by bazarnov** [comment]
@misteryeo 
The changes after the review are reflected in this [PR](https://github.com/airbytehq/airbyte/pull/11688), please check it.
