### ISSUE TITLE
[EPIC] Source Amazon Ads to Cloud Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#11028]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1W_00iHc2Zy68LZzp2gze1JFalF7aOrWVjtzXP7uu1bw/edit?userstoinvite=airbyte_java_team@globallogic.com&actionButton=1#heading=h.2omrtxnn9za3):

 - [ ] check if all requirements are satisfied
 - [ ] create Google Spreadsheet for release checklist and tag Andy for UX run through
 - [x] https://github.com/airbytehq/airbyte/issues/11367
 - [x] https://github.com/airbytehq/airbyte/issues/11417
 - [x] https://github.com/airbytehq/airbyte/issues/12540

Outstanding bugs:
- [x] https://github.com/airbytehq/airbyte/issues/8916 

MLP research:
- [x] https://github.com/airbytehq/airbyte/issues/11186
