### ISSUE TITLE
[EPIC] Source Instagram to Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#11027]
### According to [checklist](https://docs.google.com/spreadsheets/d/1ldd86xPP3AnB8y1QlvV8RXuNCW_07Kattvc3MqZ7OjY):

- [MLP](https://docs.google.com/document/d/15JmLQA_4olCZP8OX3JNT9Ym8iGxFXqs-P3r5eVNH43s) improvements:
  - [x] ~~#11115~~  -  will be added during GA certification (slack [conv](https://airbytehq.slack.com/archives/C02U9R3AF37/p1647285191140779?thread_ts=1647284507.993459&cid=C02U9R3AF37))
  - [x] ~~#11116~~  - will be added during GA certification (slack [conv](https://airbytehq.slack.com/archives/C02U9R3AF37/p1647285191140779?thread_ts=1647284507.993459&cid=C02U9R3AF37))

- Engineering Acceptance Criteria: 
  - [x] #11117 

- Label connector as GA in cloud:
  - [x] https://github.com/airbytehq/airbyte-cloud/pull/1214

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed 

</details>

**Comment by lazebnyi** [comment]
Successfully certified to Beta - https://docs.google.com/spreadsheets/d/1lRtAi5NXLs4_0unkPfVfx-xy3_924JlK3lbNaZodvC8
