### ISSUE TITLE
[EPIC] Source Mailchimp to Cloud Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#11031]
MLP requirements as surfaced through [research](https://docs.google.com/document/d/1orYG8xiKVDqYpa_6nDofLWcKE_OxW98x6rin5THSmvM/edit#heading=h.kyp5r0t74f7a):

 - [x] check if all requirements are satisfied
 - [x] create Google Spreadsheet for release checklist and tag Andy for UX run through

Outstanding bugs:

- [x] https://github.com/airbytehq/airbyte/issues/8825 

Engineering Acceptance Criteria:

- [x] https://github.com/airbytehq/airbyte/issues/11347
- [x] https://github.com/airbytehq/airbyte/issues/11288

Label connector as Beta in cloud:

- [x] https://github.com/airbytehq/airbyte-cloud/pull/1538/

**Comment by misteryeo** [comment]
Checklist and docs reviewed!
