### ISSUE TITLE
[EPIC] Source Amazon Seller Partner to Alpha

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#11030]
### According to checklist:

[MLP](https://docs.google.com/document/d/1taDEWV5jnlnXCmuSKDBuf2XTzzczIuS2u0Hf9zwJI7E/edit?usp=sharing) improvements.
  
- [x] https://github.com/airbytehq/airbyte/issues/11963
- [x] https://github.com/airbytehq/airbyte/issues/11964

Release on cloud:

- [x] unblock connector as Alpha for [cloud](https://github.com/airbytehq/airbyte-cloud/pull/1769):

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by misteryeo** [comment]
Reviewed checklist @annalvova05!
