### ISSUE TITLE
[EPIC] Developer Leverage

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11138]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Issues
- [ ] https://github.com/airbytehq/airbyte/issues/11129 (alot of the things mentioned in here affect dev quality of life and may need to be broken out)
- [x] https://github.com/airbytehq/airbyte/issues/9651
- [x] https://github.com/airbytehq/airbyte-cloud/issues/1155
- [x] https://github.com/airbytehq/airbyte/issues/11136
- [ ] https://github.com/airbytehq/airbyte/issues/11130
- [x] https://github.com/airbytehq/airbyte/issues/11137
- [x] https://github.com/airbytehq/airbyte/issues/10958
- [ ] https://github.com/airbytehq/airbyte/issues/11903
- [x] https://github.com/airbytehq/airbyte-cloud/issues/2365
- [ ] https://github.com/airbytehq/airbyte/issues/11904
- [ ] https://github.com/airbytehq/airbyte/issues/11819

**Comment by andyjih** [comment]
@cgardens Closing this epic since I think Q4 work has created new epics that captures the current thinking. Feel free to re-open if you feel differently!
