### ISSUE TITLE
[EPIC] Gradle Caching

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11130]
## Describe the solution you’d like
When I run `./gradlew build` twice in a row, it should be instantaneous. Right now it takes multiple minutes.

## Execution Plan
* [ ] - https://github.com/airbytehq/airbyte/issues/11131
* [ ] - https://github.com/airbytehq/airbyte/issues/11132
* [ ] - https://github.com/airbytehq/airbyte/issues/19784
* [ ] ... add known gradle caching issue here.

**Comment by andyjih** [comment]
cc @salima-airbyte to follow-up

**Comment by davinchia** [comment]
This is a duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947.
