### ISSUE TITLE
[EPIC] internal operations tooling (Retool)

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11143]
## Tell us about the problem you're trying to solve
For both managing the connector catalog and various cloud operations tasks, there are operations that an internal user (i.e. product manager or technical support) could perform if given the correct access. 

## Describe the solution you’d like
This issue will list some of these operations. Based on compiling them we should investigate what would be the right way to expose it (i.e. retool or equivalent?).

## Use Cases
most of these are getting pulled from this [brainstorm](https://docs.google.com/document/d/1HysX4SC5n3VHB7WnqHB_60KBFAtqHUzLoTUxkO_2Pkc/edit#) from dec '21.

* Manage connector catalog (i.e. change name, logo, version, etc)
* Promote user to instance admin
* Disable all of a user's workspaces
* link to orb (where all credit operations can be performed)
* grant a workspace actor to a connector

New brainstorm meeting to happen in april '22.

## Execution Plan
- [ ] compile internal tooling use cases 
   - [ ] issue to have new brainstorm meeting https://github.com/airbytehq/airbyte/issues/11882
- [ ] spike issue to set up Retool https://github.com/airbytehq/airbyte/issues/11885
- [ ] implement the use cases (split these into separate issues when we get there?)

**Comment by sherifnada** [comment]
@pmossman what's the status of implementing a retool-esque thing? asking since it relates to #1773
