### ISSUE TITLE
[EPIC] Surface custom connectors in Cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11144]
## Tell us about the problem you're trying to solve
Custom connectors are currently disabled in Cloud. They are highly sought after, let's add them! They were originally hidden because: 
1. We have to treat custom connectors as "malicious" since we don't write those connectors. We want to put added protection in place to sandbox them. ([issue](https://github.com/airbytehq/airbyte-cloud/issues/649))
2. We need to scope connector definitions by workspace so that custom connectors are only accessible in workspaces to which they are added.

## Execution Plan
- [x] https://github.com/airbytehq/airbyte/issues/9652
- [ ] https://github.com/airbytehq/airbyte-cloud/issues/649
- [ ] plan for helping users debug and iterate on their connectors (@sherifnada @misteryeo -- we discussed this one a bit last week. this one is very ambiguous and unscoped. likely starting with some beta users to handhold and learn from would be valuable.)

**Comment by cgardens** [comment]
[architecture diagram](https://whimsical.com/general-design-4vgbnPGntqSRGdifyXzbvu)

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Custom Connectors](https://app.harvestr.io/components/0/list/Izqb2yCrW)

**Comment by pmossman** [comment]
Ongoing work towards Custom Connectors is now captured in a new epic: https://github.com/airbytehq/airbyte-cloud/issues/3079
