### ISSUE TITLE
Apply buffering changes to BigQuery Destination when using staging

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11203]
## Subtasks
- [x] Refactor GCS and S3 related classes to DRY the code
  - [x] S3 and GCS destination config
- [x] Migrate BigQuery destination to use the new serialized buffering staging strategy
- [x] Migrate BigQuery denormalized destination to use the new serialized buffering staging strategy
