### ISSUE TITLE
[EPIC] Destination Redshift to GA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#11287]
### Acceptance criteria

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://drive.google.com/drive/folders/1gF08xGXrpUsNwga4_1XemTHellTlhj5N)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed

### Outstanding Bugs

- [x] #6340
- [ ] #10831
- [x] #11580
- [x] #12265
- [x] #12709
- [x] #12843
### MLP section

- [ ] #6787
- [x] #9038
- [ ] #11572
- [ ] #4871
- [x] #8045
- [x] #11426
- [x] #12131
- [x] #12132

**Comment by misteryeo** [comment]
@lazebnyi reviewed your latest updates to the checklist. For clarity, check_performances always block Beta/GA.

**Comment by misteryeo** [comment]
@lazebnyi reviewed checklist again - LGTM except two things:
- https://github.com/airbytehq/airbyte/pull/12100 doesn't seem to appear in production
- https://github.com/airbytehq/airbyte/issues/11580 unsure what's happening here since there are open comments on the PR from 2 weeks ago?

**Comment by lazebnyi** [comment]
@misteryeo I think that's questions to @alexandr-shegeda 🙂

**Comment by VitaliiMaltsev** [comment]
> reviewed checklist again - LGTM except two things:
> 
> * [Redshift Destination: update spec #12100](https://github.com/airbytehq/airbyte/pull/12100) doesn't seem to appear in production
> * [Destination Redshift: improve check performance #11580](https://github.com/airbytehq/airbyte/issues/11580) unsure what's happening here since there are open comments on the PR from 2 weeks ago?

* [Redshift Destination: update spec #12100](https://github.com/airbytehq/airbyte/pull/12100) - i'm not sure if these changers were released in the new cloud or oss versions, but those changes were definitely merged in the master
* [Destination Redshift: improve check performance #11580] - the PR is currently in Airbyte review status, outstanding comments were replied today

**Comment by VitaliiMaltsev** [comment]
> @VitaliiMaltsev Thanks for confirming on #12100 - I can see that it's been merged into master but we need to ensure that this is reflected in production for our users. Can you investigate and make sure this is the case?
> 
> cc: @alexandr-shegeda

@misteryeo after my consultation with @girarda  - the new version with updated spec could be deployed  in the cloud when this [task](https://github.com/airbytehq/airbyte/issues/12265) is resolved

**Comment by mattyweb** [comment]
Can https://github.com/airbytehq/airbyte/issues/14441 get added to the Redshift GA list? It would be one thing if it only truncated data or skipped a row but currently it appears if there is even 1 row of VARCHAR data around 65535 in length the whole process blows up...

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/33869
