### ISSUE TITLE
[EPIC] Amazon S3 Destination to GA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#11289]
### Acceptance criteria

- [x] Create a checklist document that should be placed on the [Google Drive](https://docs.google.com/spreadsheets/d/1SUvv5seJcWRCT26aeCPudrmGz1Fj8CF9vQygLlvz05k/edit#gid=1288588270)
- [x] Checklist filled up by engineering team
- [x] Create/Revise MLP document and place it [here](https://docs.google.com/document/d/1m79jsevosyNOALMq2XF2wntoLt1FAL_Kdaw9t7miwHY/edit)
- [x] Collect and list all tech debt-related issues in the section below
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed

### MLP section
In this section, all required features should be listed

#### Nice to have
- https://github.com/airbytehq/airbyte/issues/4184
- https://github.com/airbytehq/airbyte/issues/10940
- https://github.com/airbytehq/airbyte/issues/7587
- https://github.com/airbytehq/airbyte/issues/5128

#### Must have
-

**Comment by sashaNeshcheret** [comment]
@misteryeo Please take a look at description and linked docs.

**Comment by misteryeo** [comment]
Reviewed checklist and added some outstanding items.

**Comment by misteryeo** [comment]
Reviewed checklist @sashaNeshcheret

**Comment by sashaNeshcheret** [comment]
@misteryeo could you check list of Outstanding Bugs in 'Nice to have' section to verify that no one is not blocking going s3 to GA?

**Comment by misteryeo** [comment]
LGTM @sashaNeshcheret!

**Comment by misteryeo** [comment]
@sashaNeshcheret reviewed - checklist looks good overall but it looks like the changes you made to the input fields were in markdown instead of HTML. I've gone and updated them here: https://github.com/airbytehq/airbyte/pull/12797

**Comment by sashaNeshcheret** [comment]
@misteryeo I've published and merged #12797, as far as we finishing with certification I can proceed with updating the releaseStage in the connector index and the Connector Status in release sheet, correct? Also could you update your review point in epic description and appropriate cells in excel doc.

**Comment by misteryeo** [comment]
@sashaNeshcheret checklist has been reviewed?

#12797 doesn't look like it's been deployed into Cloud - I mentioned this in Slack and asking @grishick for help as well. But besides that, those next steps make sense to me assuming this gets deployed.

**Comment by grishick** [comment]
FYI, I opened a PR to bump this connector's version in cloud: https://github.com/airbytehq/airbyte-cloud/pull/1674

**Comment by grishick** [comment]
@misteryeo the new connector version has been published into Airbyte Cloud. Please confirm if it's good to be called GA now and then we can change the label to GA.

**Comment by misteryeo** [comment]
LGTM @grishick @sashaNeshcheret

**Comment by sashaNeshcheret** [comment]
I updated release stage for OSS and cloud and add PRs to doc, @misteryeo should we use new version of certification doc or we can use existing one, and could you fill in "Product" rows.

**Comment by misteryeo** [comment]
The certification doc you've used now is fine - I've reviewed and LGTM thanks @sashaNeshcheret
