### ISSUE TITLE
[EPIC] Github Source to GA

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#11387]
- [ ] Document issue for adding 'team_members' stream
- [ ] Document issue for adding 'team_memberships' stream
- [ ] Support incremental deletes https://github.com/airbytehq/airbyte/issues/10279

**Comment by misteryeo** [comment]
Checklist reviewed - looks good. I think the one thing we want to make sure to resolve / improve is here with Sherif's latest comment: https://github.com/airbytehq/alpha-beta-issues/issues/34
