### ISSUE TITLE
[EPIC] Connector as Configuration

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#11582]
## Tell us about the problem you're trying to solve
Iterate on the next version of CDK to enable developers to build connectors with as little code as possible

## Describe the solution you’d like
Build a new connector by writing a yaml config file describing how the data can be retrieved from the source

Because the end goal is to improve the developer's experience, this issue is broken down into small goals from which we'll learn

## Success criteria
30% of connectors can be implemented as a yaml file with no custom code overloads

## Issues
A similar iterative process will be repeated after gathering feedbacks from the MVP.

- [x] https://github.com/airbytehq/airbyte/issues/11584
- [x] https://github.com/airbytehq/airbyte-cloud/issues/1317
- [x] https://github.com/airbytehq/airbyte/issues/11777
- [x] #11959
- [x] #11947
- [x] https://github.com/airbytehq/airbyte/issues/11897
- [x] #11948
- [x] https://github.com/airbytehq/airbyte/issues/11898
- [x] https://github.com/airbytehq/airbyte/issues/12800
- [x] #11949
- [x] #11950
- [x] #11951
- [x] https://github.com/airbytehq/airbyte/issues/13126
