### ISSUE TITLE
[EPIC] Source Smartsheets to Beta

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#11759]
### According to [checklist](https://docs.google.com/spreadsheets/d/1y66T9JVc1fBj0DqzIH-XsNnnvCOsgmq1Hd_jLJ2L_98):

- [MLP](https://docs.google.com/document/d/1gWztezmxeXl2JX63iNbl-XqJj8sPGfidZm3n8mx9j78) improvements:
   - [ ] https://github.com/airbytehq/airbyte/issues/12174 
- Engineering criterias:
   - [x] https://github.com/airbytehq/airbyte/pull/12077
   - [x] https://github.com/airbytehq/airbyte/pull/12203
- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/5520 
   - [x] https://github.com/airbytehq/airbyte/issues/8099 

- Label connector as Beta in cloud:
   - [x] label smartsheets as beta in the UI 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by sherifnada** [comment]
@davydov-d please consider the checklist approved, we're ready to move forward here

**Comment by davydov-d** [comment]
Successfully certified to Beta: https://docs.google.com/spreadsheets/d/1y66T9JVc1fBj0DqzIH-XsNnnvCOsgmq1Hd_jLJ2L_98/edit#gid=1288588270
