### ISSUE TITLE
[EPIC] Source Intercom to GA

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#11756]
### According to [checklist](https://docs.google.com/spreadsheets/d/14wrsj6vsLIChzSrbr2NVIFwGZxBofV_CbqW7sRuiJas/edit#gid=1700962388):

- Documentation structure follows our standard template:
    - [x] https://github.com/airbytehq/airbyte/pull/13033

- Label connector as GA in cloud:
    - [x] https://github.com/airbytehq/airbyte-cloud/pull/1703

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by misteryeo** [comment]
@oustynova Why was this removed from this current sprint? Does this mean the commitment to bringing Intercom to GA won't happen this sprint?

**Comment by misteryeo** [comment]
@lazebnyi Checklist reviewed! Had one question around the docs template for Prerequisites.
