### ISSUE TITLE
[EPIC] Destination Postgres to BETA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#11790]
### Acceptance criteria
* [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
* [x] Checklist filled up by engineering team
* [x] Collect and list all tech debt-related issues in the section below
* [ ] Create/Revise MLP document and place it [here](https://drive.google.com/drive/folders/1gF08xGXrpUsNwga4_1XemTHellTlhj5N)
* [ ] Move checklist to the unblockers team
* [ ] Reviewed/Updated by unblockers team
* [ ] Move checklist to the product team for review
* [ ] Reviewed/Updated by product team
* [ ] Update connector documentation according to the comments in the checklist
* [ ] Certification completed

### Non-blocking issues
https://github.com/airbytehq/airbyte/issues/3199

### Blocking issues
https://github.com/airbytehq/airbyte/issues/11721
https://github.com/airbytehq/alpha-beta-issues/issues/57
https://github.com/airbytehq/alpha-beta-issues/issues/53
https://github.com/airbytehq/alpha-beta-issues/issues/11
https://github.com/airbytehq/airbyte/issues/6661

### MLP section

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537096700) by [Unito](https://www.unito.io)

**Comment by etsybaev** [comment]
@igrankova could you please take a look at the checklist from unblockers point of view? 
Thanks in advance!

**Comment by etsybaev** [comment]
Hi @andyjih . Could you please review this as part of  "Move checklist to the product team for review" section?
Thanks!

**Comment by misteryeo** [comment]
Reviewed the checklist - everything LGTM except the blocking issues which we haven't yet completed yet since we've deprioritized them.

cc: @grishick

**Comment by etsybaev** [comment]
Moved to "ON HOLD" since it was deprioritized
