### ISSUE TITLE
[EPIC] Source Postgres to GA

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#11791]
### Acceptance criteria
* [x] #12449
* [x] Checklist filled up by engineering team
* [x] #12450
* [x] #12451
* [x] Move checklist to the product team for review
* [x] Reviewed/Updated by product team
* [x] Update connector documentation according to the comments in the checklist
* [x] Certification completed

### MLP section

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537096363) by [Unito](https://www.unito.io)

**Comment by NayaBeauty1** [comment]
do this work
