### ISSUE TITLE
[Epic] Improve UX when syncing multiple tables per connection in Postgres source

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#11845]
## Tell us about the problem you're trying to solve
Currently, when users configure multiple tables per sync job, they run into various usability and scale problems. This epic is an umbrella to track issues related to syncing multiple DB tables per job

## Issues in this epic
* [x] https://github.com/airbytehq/airbyte/issues/3206
* [ ] https://github.com/airbytehq/airbyte/issues/10649
* [x] https://github.com/airbytehq/airbyte/issues/9552

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537077996) by [Unito](https://www.unito.io)
