### ISSUE TITLE
[EPIC] CI Improvements

### ISSUE THREAD

**Issue by git-phu** [airbytehq/airbyte#11903]
## Tell us about the problem you're trying to solve
Currently our CI build has multiple steps that can run tests.  If a test failure occurs in one of these steps, we have to parse through multi thousand line log files to understand what went wrong.
Feels like we can make this experience a bit better.

Furthermore, we don't have good metrics around things like how long individual tests take, how frequently they fail (either transiently or because the test is too brittle), etc.

We also don't have historical metrics around how long each job in a ci run takes, so we can't easily spot anomalies  or jobs that are increasing in length over time.

Let's investigate how we can address these issues (use some existing github actions?, use a different ci system for some steps?, completely replace github actions?).

We should prefer a solution that minimizes the amount of things we have to build ourselves as well as the amount of things we have to change with our current build system.

### Design
- [ ] Investigate what github actions exist for test reporting
- [ ] Investigate how to integrate other CI systems with Github Actions
- [ ] Investigate what other CI systems we might use instead of Github Actions
- [ ] Tech Spec for CI improvements

### Implementation
- [ ] Improved Test Reporting for CI runs
- [ ] Metrics for Individual Tests
- [ ] Metrics for CI build steps

**Comment by andyjih** [comment]
@supertopher Should this epic live in the infra team's backlog? I'm removing it from `team/workflows` for now, but let me know if you think differently!
