### ISSUE TITLE
[EPIC] Prep config-based connectors for field testing

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#11949]
## Tell us about the problem you're trying to solve
Get the config-based connectors framework in shape for community members to field test it and give us feedback.

- [x] https://github.com/airbytehq/airbyte/issues/12998
- [x] CDK: add flag to turn on debugging mode #3078
- [x] Refactor low-code paginator and stream slicer to increase cohesion #14305
- [x] Add config-based connector option to connector template #14361
- [x] #14934
- [x] https://github.com/airbytehq/airbyte/issues/14935
- [x] Tutorial for low-code CDK #13126
- [x] #11951
- [x] [low-code connectors] document concepts and architecture #14516
- [x] [low-code cdk] Generate json schema for low-code connectors and validate yaml file #14484
- [x] [low-code connectors] add config-based connectors json schema to repo to docs for reference #14510
- [x] Migrate source-sendgrid to config-base #11950
- [x] top-level "definitions" field ?

-----
- [ ] Migrate source-greenhouse to config-base #14517
- [ ] [low-code connectors] expose expanded config-based connector definition #14511
- [x] Migrate source-my-hours to config-based #14518 
- [ ] [low-code connectors] Document common patterns and recipes for config-based connectors #14592
- [ ] [low-code connectors] use decorator to set class type mapping and default implementations #14513
- [ ] https://github.com/airbytehq/airbyte/issues/12986
- [ ] https://github.com/airbytehq/airbyte/issues/12980

- [ ] rename transformations to shape
- [ ] declarative stream's cursor_field should delegate to stream slicer
