### ISSUE TITLE
[EPIC] Ensure Source and Destination errors are distinguished and useful (Defogging phase 0)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12118]
_From [Connector Quality & Observability - Defogging Connector Metrics](https://www.notion.so/Connector-Quality-Observability-Defogging-Connector-Metrics-5ab942fe90af48dc8b533814b03e00ba)_

The goal of Phase 0 is to ensure that are able to store and syndicate relevant failure reasons for every failed sync.  This includes gaining specific messages from the connector when something goes wrong.  This Epic introduces `AirbyteTraceMessage` to allow connectors to share better information with the platform.

**Analyitcs Team**

- [x] https://github.com/airbytehq/airbyte-warehouse/issues/92
- [x] https://github.com/airbytehq/airbyte-warehouse/issues/83
- [ ] Determine which OSS versions to include in reports

**OSS Platform Team**

- [x] https://github.com/airbytehq/airbyte/issues/10190
- [x] https://github.com/airbytehq/airbyte/pull/12458
- [x] https://github.com/airbytehq/airbyte/issues/12519
- [x] https://github.com/airbytehq/airbyte/issues/12161
- [x] https://github.com/airbytehq/airbyte/issues/10021 (until this happens no failure reason will persist in the OSS db)

**UI Team**
- [x] https://github.com/airbytehq/airbyte/issues/12130

**Connectors/sources Team**

- [x] #12322
- [x] https://github.com/airbytehq/airbyte/issues/12773

**Connectors/databases Team**

**Future Work**
- [ ] https://github.com/airbytehq/airbyte/issues/11322
- [ ] https://github.com/airbytehq/airbyte/issues/12864
- [ ] Update XXX Connector with detailed log messages when crashing

**Comment by sherifnada** [comment]
fyi @evantahler this is a relevant ticket being done by the platform team: https://github.com/airbytehq/airbyte/issues/11279

**Comment by evantahler** [comment]
The final goal of this story is to end up with logic in our datawarehouse similar to [this sheet](https://docs.google.com/spreadsheets/d/1gvLXo4xYXoxaKTyvFeSoWcPR_cMkV14TXglJOttW1gk/edit#gid=0)

**Comment by evantahler** [comment]
I'm calling https://github.com/airbytehq/airbyte/issues/12322 done, as both CDKs now emit `AirbyteLogMessage` generically when something goes wrong, and new versions of GA connectors have been released.  https://github.com/airbytehq/airbyte/issues/11322 remains open, but that's enhancement future work.

**Comment by evantahler** [comment]
Optional story - Add a sync summary to the end of the logs - https://github.com/airbytehq/airbyte/issues/12864

**Comment by sherifnada** [comment]
Calling this one done as the bulk of the work is completed
