### ISSUE TITLE
[Epic] Redesign connector generated UI components

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12138]
We want to significantly improve the UI of several UI components that are used when generator connector configuration. There is no fully defined list of those components yet, and we'll work with Design together on getting more of them improved.

### Enhancements
- [x] https://github.com/airbytehq/airbyte/issues/12204
- [ ] https://github.com/airbytehq/airbyte/issues/12197
- [ ] https://github.com/airbytehq/airbyte/issues/12055

### Bugs
- [x] https://github.com/airbytehq/airbyte/issues/11084
- [x] https://github.com/airbytehq/airbyte/issues/10858
- [x] https://github.com/airbytehq/airbyte/issues/8130
- [x] https://github.com/airbytehq/airbyte/issues/12199
- [x] https://github.com/airbytehq/airbyte/issues/12201
- [x] https://github.com/airbytehq/airbyte/issues/12202

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
From discussion w/ @edmundito 
- The Group label, the box its in, and the dropdown aren't aligned:
<img width="687" alt="Screen Shot 2022-04-20 at 11 40 51 AM" src="https://user-images.githubusercontent.com/633226/164300478-e038b8bc-8933-4b28-bd5c-af15d381e4bf.png">
 
- Some descriptions are super long-- is there a better way to communicate this information? The field descriptions are passed from .yml files currently.

- If the user tries to save a Source or Destination with missing required fields, the only feedback right now is that the field text turns red. We should do more (toast? message? something?)

- [bug] If I see a required field validation error and then change the Source type, the new form fields show the same validation error. Perhaps the error is being tied to the Input Label. ![2022-04-20_11-49-06 (1)](https://user-images.githubusercontent.com/633226/164302054-17e2c52f-43ac-4da2-80bd-c639f842c5c5.gif)

**Comment by timroes** [comment]
We've in the past also seen a lot of confusion around putting the example for a field as a placeholder and users understand that as the default value. We might want to improve how we render example values as part of this.

**Comment by edmundito** [comment]
I broke down what we've discussed so far into issues and added each one to the description of this epic. They are categorized into bugs and enhancements. Bugs are things that the devs can tackle with little to no design input, but enhancements are things that will need a design pass first.

**Comment by sherifnada** [comment]
I would also throw these issues in the hat: 

https://github.com/airbytehq/airbyte/issues/8060
https://github.com/airbytehq/airbyte/issues/10874

**Comment by timroes** [comment]
Closing this epic, since it's not maintained properly anymore and we're having individual issues for individual remaining tasks.
