### ISSUE TITLE
[EPIC] Source Bing Ads to Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#12238]
### According to checklist (need to be created and attached):

- MLP improvements:

- All outstanding bug reports blocking Beta:
   - [ ] https://github.com/airbytehq/airbyte/issues/9972
   - [ ] https://github.com/airbytehq/airbyte/issues/6294

- Label connector as Beta in cloud:
   - [ ] label `Bing Ads` as beta in the UI 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by bazarnov** [comment]
@sherifnada @misteryeo 
The https://github.com/airbytehq/airbyte/issues/12490 requires additional development and will take couple of days. As far as this should be an enhancement, let's move this issue for `GA` certification for `Source Bing Ads`. WDYT?

**Comment by misteryeo** [comment]
SGTM, let's move forward with this and add this issue to a GA epic @bazarnov

**Comment by bazarnov** [comment]
@misteryeo 
After the quick scope, the https://github.com/airbytehq/airbyte/issues/12490 should be covered with this PR as well.

**Comment by misteryeo** [comment]
Checklist reviewed @bazarnov

**Comment by bazarnov** [comment]
Released to Beta, closing this Epic.
