### ISSUE TITLE
[EPIC] Source Google Search Console to Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#12237]
### According to checklist (need to be created and attached):

- MLP improvements:

- All outstanding bug reports blocking Beta:

- Label connector as Beta in cloud:
   - [ ] label `Google Search Console` as beta in the UI 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
Reviewed @lazebnyi!
