### ISSUE TITLE
[EPIC] Source Amplitude to Beta

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#12240]
### According to [checklist](https://docs.google.com/spreadsheets/d/1fPZaImKjj-cPpwF9qpwYD4noPmH9IHKhmDzCiUbkugE/edit#gid=1288588270):

- MLP improvements:
   - [x] #12432

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/10220
   - [x] https://github.com/airbytehq/airbyte/issues/7900 

- Label connector as Beta in cloud:
   - [x] label `Amplitude` as beta in the UI https://github.com/airbytehq/airbyte-cloud/pull/1570

<details><summary><strong>Acceptance criteria </strong></summary>

- [] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by bazarnov** [comment]
The Source Amplitude is now in Beta, this Epic is closed.
