### ISSUE TITLE
[Epic] Source postgres to Beta

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12455]
The main purpose of this issue is to track release progress for the connector.
Acceptance criteria
 

- [x] Create a [checklist](https://docs.google.com/spreadsheets/d/1pKYyD25pEli7MgaLDg3mk6td4raJq7sqgZ6DAbLgExI/edit#gid=1288588270) document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x]  Checklist filled up by engineering team
- [x]  Link tech debt issues as blockers to this epic
- [x]  Create/Revise MLP document and place it [here](https://drive.google.com/drive/folders/1gF08xGXrpUsNwga4_1XemTHellTlhj5N)
- [x]  Move checklist to the unblockers team
- [x]  Reviewed/Updated by unblockers team
- [x]  Move checklist to the product team for review
- [x]  Reviewed/Updated by product team
- [x]  Update connector documentation according to the comments in the checklist
- [x]  Certification completed
