### ISSUE TITLE
[EPIC] implement configurable features to support low-code connectors

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12800]
- [x] #12880
- [x] #12881
- [x] #12978
- [x] #12884
- [x] #12889
- [x] #12995
- [x] #12989
- [X] #12886
- [X] https://github.com/airbytehq/airbyte/issues/13431
- [X] https://github.com/airbytehq/airbyte/issues/13434
- [x] #12970
- [x] #12974
- [x] #12975
- [x] #12976
- [x] #12977
- [x] #12983
- [x] #12988
- [x] #12990
- [x] #12997
- [x] #12998
- [x] #13000
- [x] #13002

----
below the line:
- [ ] #13429
- [ ] Implement support for creating request parameters by joining lists of strings (confluence)
- [ ] #12984
- [ ] #12930
- [ ] Implement support for transforming record's fields (pivotal tracker)  
- [ ] #12929
- [ ] #12973
- [ ] #12992
- [ ] #12996
- [ ] #13001
- [ ] #12979
- [ ] #12980
- [ ] #12986

**Comment by girarda** [comment]
Added a column to the feature matrix to identify outstanding issues for each connectors: https://docs.google.com/spreadsheets/d/1HP-nA5_EDFu3zRXKv5zyHJMrDWP0puO9S93kwcVYwo8/edit?usp=sharing

Here is the same list grouped by issues to highlight the high-leverage issues we should tackle first:
[('https://github.com/airbytehq/airbyte/issues/12880',
  ['amazon-ads',
   'cart',
   'chartmogul',
   'close-com',
   'commercetools',
   'confluence',
   'drift',
   'freshdesk',
   'intercom',
   'paypal-transaction',
   'persistiq',
   'posthog',
   'square',
   'stripe',
   'tempo',
   'woocommerce',
   'yahoo-finance-price',
   'zendesk-sunshine']),
 ('https://github.com/airbytehq/airbyte/issues/12882',
  ['amazon-ads',
   'freshdesk',
   'freshsales',
   'greenhouse',
   'harvest',
   'intercom',
   'lever-hiring',
   'paypal-transaction',
   'pinterest',
   'pivotal-tracker',
   'qualaroo',
   'search-metrics',
   'square',
   'stripe',
   'zendesk-sunshine',
   'zenloop']),
 ('https://github.com/airbytehq/airbyte/issues/12889',
  ['cart',
   'chargify',
   'delighted',
   'drift',
   'flexport',
   'freshservice',
   'greenhouse',
   'hellobaton',
   'intercom',
   'okta',
   'outreach',
   'posthog',
   'twilio',
   'woocommerce',
   'zendesk-sunshine',
   'zendesk-talk']),
 ('https://github.com/airbytehq/airbyte/issues/12886',
  ['chargify',
   'chartmogul',
   'delighted',
   'freshdesk',
   'freshsales',
   'klaviyo',
   'paypal-transaction',
   'paystack',
   'recharge',
   'retently',
   'salesloft',
   'strava',
   'yahoo-finance-price',
   'zenloop']),
 ('https://github.com/airbytehq/airbyte/issues/12974',
  ['amplitude',
   'chargify',
   'commercetools',
   'delighted',
   'freshservice',
   'lemlist',
   'pinterest',
   'prestashop',
   'qualaroo',
   'twilio',
   'woocommerce',
   'zendesk-sunshine']),
 ('https://github.com/airbytehq/airbyte/issues/12881',
  ['chargebee',
   'dixa',
   'flexport',
   'freshdesk',
   'intercom',
   'paypal-transaction',
   'pinterest',
   'recharge',
   'search-metrics',
   'square',
   'stripe',
   'zendesk-talk']),
 ('https://github.com/airbytehq/airbyte/issues/12976',
  ['cart',
   'chargebee',
   'delighted',
   'freshservice',
   'klaviyo',
   'paystack',
   'woocommerce',
   'zendesk-sunshine',
   'zenloop']),
 ('https://github.com/airbytehq/airbyte/issues/12978',
  ['chargebee',
   'commercetools',
   'delighted',
   'intercom',
   'klaviyo',
   'pinterest',
   'posthog',
   'woocommerce']),
 ('https://github.com/airbytehq/airbyte/issues/12989',
  ['harvest',
   'hellobaton',
   'mailgun',
   'persistiq',
   'pinterest',
   'sentry',
   'square',
   'stripe']),
 ('https://github.com/airbytehq/airbyte/issues/12977',
  ['cart', 'close-com', 'freshdesk', 'lemlist', 'okta', 'zendesk-sunshine']),
 ('https://github.com/airbytehq/airbyte/issues/12983',
  ['drift', 'exchange-rates', 'flexport', 'freshdesk', 'pinterest', 'square']),
 ('https://github.com/airbytehq/airbyte/issues/12990',
  ['harvest', 'mailgun', 'paypal-transaction', 'pinterest']),
 ('https://github.com/airbytehq/airbyte/issues/12995',
  ['outreach', 'paypal-transaction', 'search-metrics', 'square']),
 ('https://github.com/airbytehq/airbyte/issues/12975',
  ['cart', 'harvest', 'pivotal-tracker']),
 ('https://github.com/airbytehq/airbyte/issues/12884',
  ['chartmogul', 'square', 'zendesk-sunshine']),
 ('https://github.com/airbytehq/airbyte/issues/12997',
  ['paystack', 'stripe', 'woocommerce']),
 ('https://github.com/airbytehq/airbyte/issues/12998',
  ['pivotal-tracker', 'woocommerce', 'zendesk-sunshine']),
 ('https://github.com/airbytehq/airbyte/issues/12970',
  ['amazon-ads', 'lever-hiring']),
 ('https://github.com/airbytehq/airbyte/issues/12979',
  ['close-com', 'pivotal-tracker']),
 ('https://github.com/airbytehq/airbyte/issues/12986',
  ['freshdesk', 'paypal-transaction']),
 ('https://github.com/airbytehq/airbyte/issues/12988',
  ['freshsales', 'twilio']),
 ('https://github.com/airbytehq/airbyte/issues/12996',
  ['paypal-transaction', 'twilio']),
 ('https://github.com/airbytehq/airbyte/issues/13000', ['qualaroo', 'stripe']),
 ('outstandingissues', [nan]),
 ('https://github.com/airbytehq/airbyte/issues/12973', ['amplitude']),
 ('https://github.com/airbytehq/airbyte/issues/12980', ['drift']),
 ('https://github.com/airbytehq/airbyte/issues/12984', ['flexport']),
 ('https://github.com/airbytehq/airbyte/issues/12992', ['intercom']),
 ('`check`dependsonahardcodedlistofcurrencies', ['python-http-tutorial']),
 ('https://github.com/airbytehq/airbyte/issues/13001', ['qualaroo']),
 ('https://github.com/airbytehq/airbyte/issues/13002', ['recharge']),
 ('NONE', ['sendgrid']),
 ('needtocheckthatthetickerisvalid', ['yahoo-finance-price'])]
