### ISSUE TITLE
[EPIC] Zendesk Support to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12935]
### According to [checklist](https://docs.google.com/spreadsheets/d/1QhyQzvcM6uOB8hmVv55gS4oRovDe8bapXVwj7nTTll0/edit#gid=1820065035):

- MLP improvements:
   - [X] [Document](https://docs.google.com/document/d/179CgrB6Mc6TCad8BoAoYLkEt7BsVdW9boIdvauTg6OQ/edit) any stream or feature not supported by Airbyte but supported by Fivetran or Stitch

- All outstanding bug reports blocking GA:
   - [x] https://github.com/airbytehq/airbyte/issues/12926
   - [x] https://github.com/airbytehq/airbyte/issues/10829
   - [x] https://github.com/airbytehq/airbyte/issues/10920
   - [x] https://github.com/airbytehq/airbyte/issues/11973
   - [x] https://github.com/airbytehq/airbyte/issues/12591
   - [x] https://github.com/airbytehq/airbyte/issues/12155
   - [x] #13223

   No action required:
   - [ ] https://github.com/airbytehq/alpha-beta-issues/issues/84 (small amount of free space on resource)

- Label connector as GA in cloud:
   - [x] #13167

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
@bazarnov reviewed checklist - LGTM!
