### ISSUE TITLE
[EPIC] Source Linkedin Ads to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12934]
### According to [checklist](https://docs.google.com/spreadsheets/d/1xcZVcquTXb8YmobTfr9QhYgLPVQvw8Ch9XYSAiBAd_I/edit#gid=1700962388):

- MLP improvements:
   - [x] [Document](https://docs.google.com/document/d/1Mb4AATy5am1k-SAhnrBr4d3s9T902_zFHwBZT2XLfb4/edit) any stream or feature not supported by Airbyte but supported by Fivetran or Stitch

- Outstanding bugs:
   - [x] https://github.com/airbytehq/airbyte/issues/13018

- Other steps before release to GA:
   - [x] #13494
   - [x] #13492
   - [x] #13493

<details><summary><strong>Acceptance criteria </strong></summary>

- [ ] Create a checklist document that should be placed on the [Google Drive](https://docs.google.com/spreadsheets/d/1xcZVcquTXb8YmobTfr9QhYgLPVQvw8Ch9XYSAiBAd_I/edit#gid=1700962388)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
Checklist looks good! Please make sure that when you deploy docs to follow the guide shared in the Slack channel and verify that it appears in production with the side bar showing :)

**Comment by bazarnov** [comment]
Released along with OSS Release: 0.39.15-alpha
