### ISSUE TITLE
[EPIC] Source HubSpot to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12931]
###  According to [checklist](https://docs.google.com/spreadsheets/d/1glCsR8WuqJcxn79LLEUllcQLBfq5pTbCmL7PVRyeqQw/edit#gid=1288588270):
 
- Docs
   - [x] https://github.com/airbytehq/airbyte/pull/13306

- All outstanding bug reports blocking GA:
   - [x] https://github.com/airbytehq/airbyte/issues/12269
   - [x] https://github.com/airbytehq/airbyte/issues/12333
   - [x] https://github.com/airbytehq/airbyte/issues/11655
   - [x] https://github.com/airbytehq/airbyte/issues/11792
   - [x] https://github.com/airbytehq/alpha-beta-issues/issues/79
   - [x] https://github.com/airbytehq/airbyte/issues/12858
   - [x] https://github.com/airbytehq/airbyte/issues/12911

- Label connector as Beta in cloud:
   - [ ]  https://github.com/airbytehq/airbyte-cloud/pull/1768
   - [ ] https://github.com/airbytehq/airbyte/pull/13307
  
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
Reviewed checklist @lazebnyi

**Comment by lazebnyi** [comment]
Successfully certified to GA -https://docs.google.com/spreadsheets/d/1glCsR8WuqJcxn79LLEUllcQLBfq5pTbCmL7PVRyeqQw
