### ISSUE TITLE
[EPIC] Source Mailchimp to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12936]
### According to [checklist](https://docs.google.com/spreadsheets/d/1fPZaImKjj-cPpwF9qpwYD4noPmH9IHKhmDzCiUbkugE/edit#gid=1700962388):

- MLP improvements:
   - [x] [Document](https://docs.google.com/document/d/1SuPoss68t2r5b-6zU2hlWAe34RE1za0sRbGvkAGM04M/edit) any stream or feature not supported by Airbyte but supported by Fivetran or Stitch

- Other steps before release to GA:
   - [x] #13636

<details><summary><strong>Acceptance criteria </strong></summary>

- [ ] Create a checklist document that should be placed on the [Google Drive](https://docs.google.com/spreadsheets/d/1fPZaImKjj-cPpwF9qpwYD4noPmH9IHKhmDzCiUbkugE/edit#gid=1700962388)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
LGTM @arsenlosenko!
