### ISSUE TITLE
New Source: Zendesk Chat

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1316]
## Tell us about the new integration you’d like to have
[Zendesk Chat](https://developer.zendesk.com/rest_api/docs/chat/introduction)

Entities to sync: 
* Account
* Agents
* Bans
* Chats
* Departments
* Goals
* Shortcuts
* Triggers

All these resources should sync full refresh to start with, but the intent is to make this source incremental in the future. If there will be a lot of throwaway work when making this source fullrefresh first then incremental, it should be created as incremental from the beginning. 

## Describe the alternative you are considering or using
The alternative is [tap-github](https://github.com/singer-io/tap-zendesk-chat) from Singer.

**Comment by sherifnada** [comment]
@kitkatbarxp some questions about your use of Zendesk Chat:

* which endpoints from the Zendesk Chat API do you need?
* which destinations are you sending this data to ?
* can you describe the usecase/context around using this API?

**Comment by kitkatbarxp** [comment]
endpoints: incremental exports, specifically on the chats objects

destination: it'd likely be a postgres instance for now. In the medium/long term, there are possibilities of loading the data into redshift/snowflake, or at least some type of json file in s3.

context/use case: My company uses Zendesk heavily to support our customers. We support them via chat, email, and phone. There are a lot of operational and customer insights that we can derive to help us support our customers better and also improve our own product. It'd be useful to get information on Chat information such as wait times and engagements, so that we can get a sense of our effectiveness of customer support via Chat.

**Comment by vitaliizazmic** [comment]
## Integration Vetting
The integration has already been vetted

Ready for implementation

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
API key

**Creating an account**
Free account available?  No, but Airbyte obtained a sponsored partner account

**How to populate the account with data?**
Most streams can be populated entirely through the API except Accounts and Routing Settings.

**Available streams for sync**

- Accounts
- Agents
- Visitors
- Chats
- Shortcuts
- Triggers
- Bans
- Departments
- Goals
- Skills
- Roles
- Routing Settings
 
**Integration supports incremental sync?**
Some

**Other information/blockers**
[https://github.com/airbytehq/airbyte/issues/1316](https://github.com/airbytehq/airbyte/issues/1316)

**Comment by yevhenii-ldv** [comment]
**Are the account test credentials available in Lastpass?** Yes

## Note

For implement current connector we can't use Zendesk Chat Singer Tap, because `read` method doesn't work.

## Task breakdown

- [ ] Populate source with data (6h)
- [ ] Create source scaffolding and populate schemas folder (2h, can using schemas from Singer Tap)
- [ ] Implement spec, check, and discover (2h)
- [ ] Implement Read 
    - [ ] Create API base abstract class (2h)
      - [ ] Create Base stream abstract classes (6h)
- [ ] Implement Incremental sync (5h) 
- [ ] Handle rate limiting (2h)
- [ ] Implement standard tests and add docs (3h)

**Comment by sherifnada** [comment]
@kitkatbarxp Zendesk Chat has been merged into master and will be included by default as part of Airbyte beginning with tomorrow's release, `0.23.0-alpha`!
