### ISSUE TITLE
[EPIC] Source Oracle Netsuite to Alpha

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#13349]
1. Create a research and scoping document for Netsuite to validate requirements for Alpha
2. Validate that integration sandbox account is viable for this connector
3. Build new connector in Q3.

### According to [checklist](https://docs.google.com/spreadsheets/d/1f-osgphx0YC0PbLtf7_iwzSuMdgWG3jWKjyC-zWimNo/edit#gid=201691089):

- Alpha release based on [Research](https://docs.google.com/document/d/1dK229W_v5B6OVEj3O2PJkCgJ41lqNN21kLqiwult1iw/edit)
   
- Issues need to be closed before ALPHA release:
   - [x] https://github.com/airbytehq/airbyte/issues/3212

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by drrest** [comment]
Part about first point:
Overall scope for all: https://docs.google.com/document/d/1bOadNhXDkiqUlRTmhdW8zpbFFVf4va761SAMisC0Y20

**Comment by misteryeo** [comment]
Thanks @drrest, @sherifnada will respond to the comments that you left. 

Can you proceed to digging into (2) as well? We want to ensure that the sandbox is adequate for building out the connector. Thanks!

**Comment by misteryeo** [comment]
@drrest circling back here - have you had a chance to validate if the sandbox is appropriate?

**Comment by misteryeo** [comment]
Hi @drrest, following up here:

1. Did you manage to validate the viability of using the sandbox? 
2. We've had some additional conversations with customers of Netsuite to understand which method of pulling data is preferred, which streams of data are desired and what configuration options they would like to see - you can read more and listen to recordings [here](https://docs.google.com/document/d/1dK229W_v5B6OVEj3O2PJkCgJ41lqNN21kLqiwult1iw/edit?pli=1#heading=h.fc68t9drswsp). As a next step, in your scoping doc, are you able to make a recommendation of which approach you think we should take while listing out the pros and cons across the different methods? If it's helpful, this [conversation with a Netsuite consultant](https://docs.google.com/document/d/1dK229W_v5B6OVEj3O2PJkCgJ41lqNN21kLqiwult1iw/edit?pli=1#heading=h.g7vzy8s6oci7) talks through some of those pros and cons.

Would love for us to be able to move forward on implementation after we take a look at your breakdown and recommendation.

**Comment by drrest** [comment]
> Hi @drrest, following up here:
> 
> 1. Did you manage to validate the viability of using the sandbox?
> 2. We've had some additional conversations with customers of Netsuite to understand which method of pulling data is preferred, which streams of data are desired and what configuration options they would like to see - you can read more and listen to recordings [here](https://docs.google.com/document/d/1dK229W_v5B6OVEj3O2PJkCgJ41lqNN21kLqiwult1iw/edit?pli=1#heading=h.fc68t9drswsp). As a next step, in your scoping doc, are you able to make a recommendation of which approach you think we should take while listing out the pros and cons across the different methods? If it's helpful, this [conversation with a Netsuite consultant](https://docs.google.com/document/d/1dK229W_v5B6OVEj3O2PJkCgJ41lqNN21kLqiwult1iw/edit?pli=1#heading=h.g7vzy8s6oci7) talks through some of those pros and cons.
> 
> Would love for us to be able to move forward on implementation after we take a look at your breakdown and recommendation.
> 
> cc: @YowanR

Hi @misteryeo 
1) I was tried to check sandbox variant. It was a some time ago. Last time it is not worked as well
2) Can you please give me access to these files, because i haven't.

**Comment by misteryeo** [comment]
Closing the loop here - access has been granted. @drrest let me know how things go after you've reviewed - would love to see recommendations on a path forward for us to build this out!

**Comment by bazarnov** [comment]
Merged into OSS Master. Closing this Epic for now, once needed - re-open it.
