### ISSUE TITLE
[EPIC] Source Amplitude to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#13403]
### According to [checklist](https://docs.google.com/spreadsheets/d/1fPZaImKjj-cPpwF9qpwYD4noPmH9IHKhmDzCiUbkugE/edit#gid=1700962388):

- MLP improvements:
   - [x] [Document](https://docs.google.com/document/d/1paI_5Ct8p-KfSRM2ENNg0lEV7hPIili2O3hN7WhCR90/edit) any stream or feature not supported by Airbyte but supported by Fivetran or Stitch

- Outstanding bugs:
   - [x] https://github.com/airbytehq/alpha-beta-issues/issues/96
   - [x] #13598
   - [x] https://github.com/airbytehq/airbyte/issues/13266
   - [x] https://github.com/airbytehq/alpha-beta-issues/issues/78

- Other steps before release to GA:
   - [x] #13597

<details><summary><strong>Acceptance criteria </strong></summary>

- [ ] Create a checklist document that should be placed on the [Google Drive](https://docs.google.com/spreadsheets/d/1fPZaImKjj-cPpwF9qpwYD4noPmH9IHKhmDzCiUbkugE/edit#gid=1700962388)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
Checklist reviewed @bazarnov
