### ISSUE TITLE
New Source: Klaviyo

### ISSUE THREAD

**Issue by rouseguy** [airbytehq/airbyte#1352]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?

Source: Klaviyo. Every 15 minutes. 

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
For Shopify developers, this is the email marketing tool of choice. I am building apps for Shopify merchants. There are 1M+ Shopify merchants - and Klaviyo is the No.1 email marketing tool for Shopify merchants

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Singer tap.

**Comment by michel-tricot** [comment]
Thanks @rouseguy!

Do you have a sense of how good Klaviyo singer tab is? (if you have a link to the singer tap you've looked at, that would be amazing)

**Comment by michel-tricot** [comment]
Is it the one: https://github.com/singer-io/tap-klaviyo ?

**Comment by rouseguy** [comment]
Yes - that's right. I haven't used the Singer tap. I pull directly from the APIs.

**Comment by sherifnada** [comment]
@rouseguy if you already have code written for pulling from Klaviyo, would you be open to taking a crack at contributing the Airbyte connector? No worries if you don't have the bandwidth, figured it's worth asking.

**Comment by rouseguy** [comment]
I will check. Unfortunately, am out for next 3 weeks. Dont think I can be helpful before march beginning.

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**

no

**Available authentication modes (API key/Oauth/other)**

API key

**Creating an account**

Account was created and credentials added to Lastpass

**How to populate the account with data?**

_It can be done through the API and UI_

**Available streams for sync**

* bounce
* click
* dropped_email
* mark_as_spam
* open
* receive
* unsubscribe
* global_exclusions
* lists

**Integration supports incremental sync?**

some streams

**Other information/blockers**

If we use [Singer Tap](https://github.com/singer-io/tap-klaviyo), then we will have to make fork the repository and merge the [PR](https://github.com/singer-io/tap-klaviyo/pull/22/files) into the master to fix the `discover` method.

Python [library](https://github.com/klaviyo/python-klaviyo) for working with Klaviyo.

**Comment by keu** [comment]
**Are the account test credentials available in Lastpass?** yes

## Task breakdown
- [ ] Create source scaffolding (spec, check + discover) and populate schemas folder (8h)
- [ ] Implement Read (8h)
- [ ] Populate source with data (8+h) - high risk, as there are many streams, we can use API client
- [ ] Implement Incremental Read (4h)
- [ ] Handle rate limiting (3h)
- [ ] Implement standard tests (4h)

Total: 43h

**Comment by keu** [comment]
this Source will be the first one to pydantic for spec and schemas

**Comment by keu** [comment]
unfortunately, there is no information about the rate limit in the docs, neither about exact limits nor where to find backoff value in the response. It just says the backoff value is there.
