### ISSUE TITLE
[EPIC] Source Sentry to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#13881]
### According to [checklist](https://docs.google.com/spreadsheets/d/1TtUQ8ca6Al-AmH9xCp_mIzBhjM2FYPZwR1-ZmDimfQg/edit#gid=1820065035):

- MLP improvements based on [Research](https://docs.google.com/document/d/1QWv3ivMgx9IWvrIKrAnjm-kqpdPd6NiJZRW0JMAzQgc/edit):
   None

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/13730

- Other improvements:
   - [x] https://github.com/airbytehq/airbyte/issues/15882

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by Phlair** [comment]
@igrankova tickets that @pedroslopez and I are working on aren't related to source-sentry, they are part of the connector incident management project, we're using Sentry as the tool for this.

**Comment by igrankova** [comment]
@Phlair, thank you for mentioning it. I'm removing these issues from Epic.
