### ISSUE TITLE
[EPIC] Source Klaviyo to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14048]
### According to [checklist](https://docs.google.com/spreadsheets/d/1guymBpuiIJz0d3wLo70I0ASOYTJhalchLO_AtBul_9k/edit#gid=1288588270):

- [MLP](https://docs.google.com/document/d/1aiw92DE1a7PgNiheke6Xuiq_n7UEwkcyLDcVXLuJAfM/edit#heading=h.cbz2s8pcohr1) improvements 

- All outstanding bug reports blocking Beta: all resolved (see section below)

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by YowanR** [comment]
I've reviewed the checklist -- LGTM! Thanks!

**Comment by davydov-d** [comment]
Successfully certified to Beta: https://docs.google.com/spreadsheets/d/1guymBpuiIJz0d3wLo70I0ASOYTJhalchLO_AtBul_9k/edit#gid=1288588270
