### ISSUE TITLE
[EPIC] Source Slack to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14052]
### According to [checklist](https://docs.google.com/spreadsheets/d/1MCHJHD3bFg7GeWJO2pFgdn_hjxzWPYK2gcNzhHVYQVU/edit#gid=1288588270):

- MLP improvements:
   - Airbyte covered the same streams as Stitch except the “team.info” stream. 
   - We should list the Public App on a Marketplace. 

- All outstanding bug reports blocking Beta:
   - [x] [9419](https://github.com/airbytehq/airbyte/issues/9419)
   - [x] [11919](https://github.com/airbytehq/airbyte/issues/11919)
   - [x] [2892](https://github.com/airbytehq/airbyte/issues/2892) 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by YowanR** [comment]
LGTM -- thank you!
