### ISSUE TITLE
[EPIC] Source Marketo to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14056]
### According to [checklist](https://docs.google.com/spreadsheets/d/1usgaDN5L---npitHjv3VbtceZw9_8VhVcTX6jjuzhTE/edit#gid=1288588270):

- MLP improvements:
  - https://docs.google.com/document/d/16hxgPhnA1c2B4vZY0Sg22pKjh7FyBs00nwQBGtANmSA/edit#  (we need to implement more streams!)

- All outstanding bug reports blocking Beta:
   - [X] https://github.com/airbytehq/airbyte/issues/15823
   - [X] https://github.com/airbytehq/airbyte/issues/14149
   - [X] https://github.com/airbytehq/airbyte/issues/12732
   - [X] https://github.com/airbytehq/airbyte/issues/10191

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>
