### ISSUE TITLE
[EPIC] Source Zendesk Chat to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14146]
### According to [checklist](https://docs.google.com/spreadsheets/d/1qA5B7_xA3v2Z1LPU0ze148mnvn2N18m3jcR3Hm29iPw/edit#gid=1288588270):

- MLP improvements based on [Research](https://docs.google.com/document/d/1gdAB96P2YY4jTuuSthLkn7Hn_EKOwPgLbxOAmIrd-04/edit):
   
    None

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/5478
   - [x] https://github.com/airbytehq/airbyte/issues/13379
   
- Other improvements:
   - [x] https://github.com/airbytehq/airbyte/issues/15479
   - [x] https://github.com/airbytehq/airbyte/issues/15715
   - [x] https://github.com/airbytehq/airbyte/issues/15716

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by YowanR** [comment]
LGTM -- thanks!
