### ISSUE TITLE
[EPIC] Source Gitlab to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14152]
### According to [checklist](https://docs.google.com/spreadsheets/d/1vgh-0Crm68oEhrVdDMoR5fD5tG1uMoqkQKNeceb8r04/edit#gid=1288588270):

- [MLP](https://docs.google.com/document/d/1u95XzZ_aI2HtmGyrOdtlCu4hmEPdKAo0AEg1uOQRmro/edit#heading=h.22fd5raysmm3) improvements:

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/12901
   - [x] https://github.com/airbytehq/airbyte/issues/20022
   - [x] https://github.com/airbytehq/airbyte/issues/12900
   - [x] https://github.com/airbytehq/airbyte/issues/11248
   - [x] https://github.com/airbytehq/airbyte/issues/21076 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/20507)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by YowanR** [comment]
@davydov-d can you take a look, please?

**Comment by davydov-d** [comment]
@girarda @YowanR here is the PR implementing OAuth - https://github.com/airbytehq/airbyte/pull/7506.
The plan was to merge the PR as soon as it gets unblocked ([#3990](https://github.com/airbytehq/airbyte/issues/3990) should be closed) -> certify to beta -> unpin in cloud. Am I missing something?

**Comment by davydov-d** [comment]
@girarda @YowanR here is the PR implementing OAuth - https://github.com/airbytehq/airbyte/pull/7506.
The plan was to merge the PR as soon as it gets unblocked ([#3990](https://github.com/airbytehq/airbyte/issues/3990) should be closed) -> certify to beta -> unpin in cloud. Am I missing something?

**Comment by TBernstein4** [comment]
I was made aware that this [issue](https://github.com/airbytehq/airbyte/issues/12476) even though it is closed is not fixed and a user has encountered a similar [issue](https://github.com/airbytehq/airbyte/issues/21076). I noticed it appears as closed/completed in this [EPIC] and just wanted to make sure the team was aware that this was something that still needed to be addressed. 
<img width="512" alt="Screenshot 2023-01-20 at 9 54 07 AM" src="https://user-images.githubusercontent.com/104733644/213730839-99b35541-3baa-4249-b49e-cd2dc4224440.png">

**Comment by davydov-d** [comment]
thanks @TBernstein4, I'll take a look
