### ISSUE TITLE
Source MySQL to Beta

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14327]
This is an Epic that aggregates issues that are required to be closed for MySQL source to be certified as beta.

* [ ] Create a certification spreadsheet
* [ ] Link spreadsheet in the issue description
* [ ] Checklist filled up by engineering team
* [ ] Move checklist to the product team for review
* [ ] Reviewed/Updated by product team
* [ ] Update connector documentation according to the comments in the checklist
* [ ] Update connector label to Beta
* [ ] Deploy beta connector version to Airbyte Cloud
