### ISSUE TITLE
Investigate usage of heartbeat property in debezium for CDC 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#15040]
Helpful info in Debezium's internal postgres implementation :
This is from our discussion around the scenario that a customer adds lots of tables in the publication for CDC but only adds a small sub-set of tables in the Airbyte catalog to sync, and if one of the tables which is not part of Airbyte's  catalog has thousands of WAL logs then it might be troublesome for the connector.
It might result in Airbyte shutting down cause it didn't receive any record from the server for 1 minute cause all the records are filtered out.
The disk space would climb up since debezium is filtering out all the records, it is not commiting lsn to the server
Turns out there is a solution for this in debezium. Firstly debezium has in built warning system if such a thing happens, there is warning inside class `PostgresStreamingChangeEventSource`
```
LOGGER.warn("Received {} events which were all filtered out, so no offset could be committed. "
                    + "This prevents the replication slot from acknowledging the processed WAL offsets, "
                    + "causing a growing backlog of non-removeable WAL segments on the database server. "
                    + "Consider to either adjust your filter configuration or enable heartbeat events "
                    + "(via the {} option) to avoid this situation.",
                    numberOfEventsSinceLastEventSentOrWalGrowingWarning, Heartbeat.HEARTBEAT_INTERVAL_PROPERTY_NAME);
```
Secondly we could use the [heartbeat](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-heartbeat-interval-ms) property to tackle this, if my understanding is correct, it would send back a random record in above scenario thus making sure we receive a record (which should be skipped) and it would enable debezium to commit the offset on the server end as well 

```
Heartbeat messages are useful for monitoring whether the connector is receiving change events from the database. Heartbeat messages might help decrease the number of change events that need to be re-sent when a connector restarts. To send heartbeat messages, set this property to a positive integer, which indicates the number of milliseconds between heartbeat messages.
```

**Comment by edgao** [comment]
sprint update: I did some experimentation on this, but didn't make any significant progress. I found that enabling heartbeats would interfere with the debezium shutdown, i.e. even after calling requestClose [here](https://github.com/airbytehq/airbyte/blob/cf7698e00378474f6b81c4ef7ed890a54e823767/airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumRecordIterator.java#L83), we would just continue iterating forever. But didn't manage to track down why that was happening.

**Comment by rodireich** [comment]
I wonder how we can best utilize heartbeat.
If our record iterator has a poll wait time of x seconds, and a heartbeat rate of h seconds:

-  if we put _h < x_ then the stream will never be able to shutdown. Even if we force a shutdown and solve the issue @edgao [saw](https://github.com/airbytehq/airbyte/issues/15040#issuecomment-1232288799), since the producer will keep sending messages and the queue will never drain.
- If we put _h > x_ then I don't see what benefit we get from it as the stream will close after x.

We could decide on another timeout (y) who purpose is after y seconds of only heartbeats without any change event we can shut the sync, but I'm not sure it solves the issue for real life scenario

**Comment by rodireich** [comment]
> the scenario that a customer adds lots of tables in the `PUBLICATION`[^1] for CDC but only adds a small sub-set of tables in the Airbyte catalog to sync

Assumption: if a customer is seeing these timeouts during their cdc reads it suggests that their publication is way too broad compared to the set of tables that are actually synced by Airbyte and **they should narrow down the synced publication**.
That is to say - a configuration problem.

if this assumption holds then we can utilize heartbeats as followed:
1. With existing polling timeout of _p_ seconds we'll add a heartbeat every _h_ seconds where _h < p_.
2. As a result of heartbeat, the queue will always have activity more frequent than the _p_ seconds timeout, that is unless some crash or network issue 
3. We are going to define a new timeout value _y_ that indicated the time we only received heartbeat pulses with no actual change record. The value of _y_ is considerably longer than _p_.
4. If no change record received for _y_ seconds we are going to fail sync but with a message suggesting the customer to check the scope of their `PUBLICATION` and consider reducing the number of tables to the ones that are synced by Airbyte.
5. If queue times out as a result of no any activity after _p_ seconds we would fail the sync same way we fail today.

[^1]: `PUBLICATION` of a replication slot in postgres defines the set of tables whose activity is logged for the purpose of CDC based replication.

**Comment by rodireich** [comment]
### TODO

- [ ] Check how network disconnection, db going down affects heartbeats and existing engine connection.
- [ ] Change shutdown routine of debezium engine to allow heartbeat messages that keep the queue not empty.
- [ ] Test assumption on how publication behave on a very large db.
- [ ] Add a configurable heartbeat value.

**Comment by rodireich** [comment]
#### Analysis of the issue
There are two thing going on with postgres WAL logs[^1]:
1. At the beginning of a read we ask DB for its current position. This tells our read what target LSN we need to get to. The problem is that result we get is a **db wide value** (e.g _`lsn = 100`_) but changes we read might only include a subset of db row inset/delete/update so after reading all changes we may only get to a lower number than target (_`lsn = 90`_). 

2. On a very large db that logs many changes to its WAL, if we sync a subset of those tables that may not have a lot of changes, then our read needs to go over a lot of logs that are irrelevant in order to collect the changes that are relevant to us. This causes a long periods of what looks like inactivity.

[^1]: WAL- write ahead logs are a journal of all db operations allowing replicating it: INSERT row…, DELETE row etc.
#### How we can solve it
By setting heartbeat in CDC, our queue will get periodic heartbeat messages according to the frequency we define.
We identify these heartbeat and omit them from regular handling of incoming events. We also read the _`heartbeat_lsn `_ value in these heartbeats.
Similarly to how we look at incoming events' _`lsn`_, 
What we can do is to look at the change of _`heartbeat_lsn`_. The value will keep changing in the case of (2) and will indicate that Debezium is moving forward in reading logs that may not contain information that is relevant to our sync - that is changes in tables we sync. 
We apply the following logic:
|Sync will continue for as long as we didn't reach target lsn and _`lsn`_ changed or _`heartbeat_lsn`_ changed within the last minute.|
|------|

This solves (2) but not (1). 
The issue in (1) can be solved by another feature of heartbeat that writes a quest to source db on every heartbeat, which forces the DB to add a change that is relevant to our sync: something like adding a "heartbeat" table to our journal and cause changes on that table during sync. This ensures that the DB will increment its current position (_`lsn = 120`_) and also that the WAL logs we read will have this latest value, which ensures that we're always going to reach target position _`120`_.
I don't this this part is crucial as starting to write to source db has its own challenges and risks and will bring up questions.
If we implement the suggested _`heartbeat_lsn`_ above we can know when to complete a sync within a range of about a minute, which should be good enough.

**Comment by rodireich** [comment]
Closing this investigation issue.

**Comment by aakarim** [comment]
Hi, is there an update on CDC heartbeats on MySQL? I'm still not able to use Airbyte on MySQL because of CDC issues. If there's a tracking issue that would be helpful.

**Comment by sh4sh** [comment]
@aakarim work on implementing CDC heartbeats for MySQL will be tracked in https://github.com/airbytehq/airbyte/issues/23257, feel free to leave a thumbs up or comment to help with prioritization
