### ISSUE TITLE
Source MySQL to GA

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#15914]
This is an Epic that aggregates issues that are required to be closed for MySQL source to be certified as GA.

* [ ] Create a certification spreadsheet
* [ ] Link spreadsheet in the issue description
* [ ] Checklist filled up by engineering team
* [ ] Move checklist to the product team for review
* [ ] Reviewed/Updated by product team
* [ ] Update connector documentation according to the comments in the checklist
* [ ] Update connector version to 1.0
* [ ] Update connector label to GA
* [ ] Deploy latest version to Airbyte Cloud
* [ ] Certification completed
