### ISSUE TITLE
[EPIC] Source Asana to GA

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16010]
## The main purpose of this issue is to track release progress for the connector.

- MLP [Doc](https://docs.google.com/document/d/1lClC4dIptzvYLvSsg1ZhuboFG-vKviHth1_mlFZV1Uk/edit#heading=h.22fd5raysmm3)

<details><summary><strong>Acceptance criteria </strong></summary>

- [ ] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>
