### ISSUE TITLE
[EPIC] Source Slack to GA

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16068]
## The main purpose of this issue is to track release progress for the connector.

<strong> According to the [checklist](https://docs.google.com/spreadsheets/d/1MCHJHD3bFg7GeWJO2pFgdn_hjxzWPYK2gcNzhHVYQVU/edit#gid=1700962388)</strong>:
- MLP [Doc](https://docs.google.com/document/d/1uMmY22ixpxQbpCX45GpEyn0Rgl5X2jRoMRM89C6ohmY/edit)
- All outstanding bugreports blocking GA:

   - ~~[ ] https://github.com/airbytehq/oncall/issues/556 (not sure though, waiting for Juan to respond)~~ - I've excluded the issue from this epic as it look like a platform issue - @davydov-d  
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>
