### ISSUE TITLE
[EPIC] Source Greenhouse to GA

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16061]
### According to the [checklist](https://docs.google.com/spreadsheets/d/1-MpqpPogi6Fr-XFR3NAMnwevmoQ3-t6I5HijmfnIdJY/edit#gid=1700962388):
- [MLP](https://docs.google.com/document/d/1tmY23gj354sDg2MXgIrBzEgc4Auck6bRD1eQEBQFW2c/edit) improvements:
- All outstanding bug reports blocking GA:
 - [X] https://github.com/airbytehq/alpha-beta-issues/issues/295
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>
