### ISSUE TITLE
[EPIC] Source Marketo to GA 

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16076]
## The main purpose of this issue is to track release progress for the connector.

<strong>According to the [checklist](https://docs.google.com/spreadsheets/d/1usgaDN5L---npitHjv3VbtceZw9_8VhVcTX6jjuzhTE/edit#gid=1700962388)</strong>:
 - MLP [Doc](https://docs.google.com/document/d/16hxgPhnA1c2B4vZY0Sg22pKjh7FyBs00nwQBGtANmSA/edit)
 - Outstanding bugs:
  - [X] https://github.com/airbytehq/alpha-beta-issues/issues/228
  - [X] https://github.com/airbytehq/alpha-beta-issues/issues/238
  - [X] https://github.com/airbytehq/airbyte/issues/16986
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>
