### ISSUE TITLE
[EPIC] Source Freshdesk to GA

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16072]
### According to [checklist](https://docs.google.com/spreadsheets/d/1bLZlYL3PuNMekwIOsLzAmerJlNmXy0RbLWhDntJTCX4/edit#gid=1700962388):

- MLP improvements based on [Research](https://docs.google.com/document/d/194jx0s2QEA_A4PmVkozKXkbuQKATRDcEVrtx6jK3dQ8/edit):
    None

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/alpha-beta-issues/issues/288
   - [x] https://github.com/airbytehq/alpha-beta-issues/issues/316
   
- Other improvements:
   - [x] #17140

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>
