### ISSUE TITLE
[EPIC] Source Asana: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16801]
## Tell us about the problem you're trying to solve
For ceratin connectors our competitors implemented more than we did. We should investigate the pros and cons of implementing these feutures in Airbyte.

## Describe the solution you’d like
Fivetran implemented 4 sreams that we did not: Attachment, Organization Export, Portolio, Portfolio Memebership:

- [x] [Attachment](https://docs.google.com/document/d/179CgrB6Mc6TCad8BoAoYLkEt7BsVdW9boIdvauTg6OQ/edit#)
- [x] [Organization Export](https://docs.google.com/document/d/1CZ-0H9BfNaP7FQrts2MnpGFkilvLwCqulhnLCrDo0mA/edit)
- [x] [Portfolio](https://docs.google.com/document/d/1InuPpJz_K7a0bnH_V0otY_WDeJ3AG8CvTr5vB159QbQ/edit)
- [x] [Portfolio Memebership](https://docs.google.com/document/d/1XUgv1CPLlOmGib2GBlyTvYLVCRh6tapZ_BVn7VTxQIE/edit#)
