### ISSUE TITLE
[EPIC] Source Zendesk Support: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16858]
## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/179CgrB6Mc6TCad8BoAoYLkEt7BsVdW9boIdvauTg6OQ/edit#)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:
- [x] Articles
- [x] Audit Logs
- [x] Brands
- [x] Custom Agent Roles
- [x] Incremental Exports **! this stream was in Fivetran Zendesk Support ERD [schema](https://docs.google.com/presentation/d/1CKAD_AK3i8oPN_97OwSH0Uff9LNsTp2Q2t-tOir8rxM/edit#slide=id.p) - CALL_METRIC, but the link to the Zendesk docs leads to the Zendesk Talk API, so I didn't create the issue for this stream, it is covered by Airbyte in Zendesk Talk connector**
- [x] Organization Fields
- [x] Organization Memberships
- [x] Post Comments
- [x] Posts
- [x] Schedules
- [x] Skill-based Routing
- [x] Ticket Skips
- [x] Topics
- [x] Votes

**Comment by sh4sh** [comment]
Hey @igrankova, do you know if there is a current ticket about implementing the [Incremental Exports API](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/)? 

It would resolve performance issues with a stream in the Zendesk Support connector. Currently the `ticket_audit` stream [only supports client-side incremental syncs](https://docs.airbyte.com/integrations/sources/zendesk-support#supported-streams) as the API endpoint doesn't have a `start_date` parameter. The [endpoint doc](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_audits/#list-all-ticket-audits) says the Incremental Exports API would help, and we could migrate the stream to it, but I wanted to check in first so work isn't duplicated.
