### ISSUE TITLE
[EPIC] Source Chargebee: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16880]
## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1yRDI1VItRqDfNKMQukqv0kr4Gx6cgh4Oh_Xh5LnxNo4/edit)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:

- [x] Payment Source
- [x] Transactioon
- [x] Gift
- [x] Quote Line Item
- [x] Quote
- [x] Credit Note
- [x] Unbilled Charge
- [x] Virtual Bank Account
- [ ] Customer Referral Url
- [x] Promotional Credit
- [x] Customer Contact
- [x] Hosted Pages
- [x] Site Migration Details

**Comment by pnilan** [comment]
@ycherniaiev `customer_referral_url` is returned as a subset of the `customer` stream.
