### ISSUE TITLE
[EPIC] Source Google Ads: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17200]
## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1KOiJT6hENQTOdNI2DGgMDRTD2JV0NBLOU3uxRyhE42w/edit?usp=sharing)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:
- [ ] ad_customizers_feed_item_report
- [ ] ad_performance_report
- [ ] adgroup_performance_report
- [ ] age_range_performance_report
- [ ] audience_performance_report
- [ ] automatic_placements_performance_report
- [ ] bid_goal_performance_report
- [ ] budget_performance_report
- [ ] call_metrics_call_details_report
- [ ] campaign_ad_schedule_target_report
- [ ] campaign_location_target_report
- [ ] campaign_performance_report
- [ ] click_performance_report
- [ ] creative_conversion_report
- [ ] criteria_performance_report
- [ ] destination_url_report
- [ ] final_url_report
- [ ] gender_performance_report
- [ ] geo_performance_report
- [ ] keywordless_category_report
- [ ] keywordless_query_report
- [ ] keywords_performance_report
- [ ] landing_page_report
- [ ] marketplace_performance_report
- [ ] paid_organic_query_report
- [ ] parental_status_performance_report
- [ ] placeholder_feed_item_report
- [ ] placeholder_report
- [ ] placement_performance_report
- [ ] product_partition_report
- [ ] search_query_performance_report
- [ ] top_content_performance_report
- [ ] url_performance_report
- [ ] user_ad_distance_report
- [ ] video_performance_report
