### ISSUE TITLE
Connector Builder - Phase 0

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#17369]
Phase 1 of the Connector Builder project, as described in the Tech Spec here: https://docs.google.com/document/d/11HrieUnA7oa6YsDhOVZpAVkOoZt2RWQQWJLPf7xQodY/edit#heading=h.xtm4ef2l8j3w

----
Server todo list
- [x] https://github.com/airbytehq/airbyte/issues/17813
- [x] https://github.com/airbytehq/airbyte/issues/17542
- [x] https://github.com/airbytehq/airbyte/issues/17541
- [x] https://github.com/airbytehq/airbyte/issues/17543
- [x] https://github.com/airbytehq/airbyte/issues/17540
- [x] #18465
- [x] https://github.com/airbytehq/airbyte/issues/18575
----
below the line
- [ ] https://github.com/airbytehq/airbyte/issues/17710
- [ ] https://github.com/airbytehq/airbyte/issues/17709

**Comment by lmossman** [comment]
Phase 0 was completed in early Jan, closing out
