### ISSUE TITLE
[Epic] Auto-Detect Schema Changes

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#17520]
* [PRD](https://docs.google.com/document/d/1hvwPXnfi0TMK05dnh4Oy-n5WEDCD9msCbUOLxwnp0Uw/edit)
* [Figma Prototype](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=972%3A36208&node-id=972%3A36212&viewport=446%2C338%2C0.09&scaling=min-zoom&starting-point-node-id=972%3A36212&show-proto-sidebar=1)

```[tasklist]
### Tasks
- [x] #17521
- [x] #17522
- [x] #17525
- [x] #17526
- [x] #17632
- [x] #17527
- [x] #17528
- [x] #17523
- [x] #19242 
- [x] #17529 
- [x] #18979 
- [x] #17829 
- [x] #17828
- [x] #17826
- [x] #20201 
- [ ] #17619
- [ ] #17530
- [x] #17633
- [x] #17936
- [x] #17830 
- [x] #19920 
- [ ]  https://github.com/airbytehq/airbyte-cloud/issues/4208
- [ ] https://github.com/airbytehq/airbyte/issues/22562
- [ ] https://github.com/airbytehq/airbyte/issues/24462
```

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by davinchia** [comment]
@benmoriceau what is the status of this?

**Comment by cgardens** [comment]
closes https://github.com/airbytehq/airbyte/issues/1037

**Comment by davinchia** [comment]
@benmoriceau what is the status of this? Can we close this epic?

**Comment by benmoriceau** [comment]
@davinchia I think so, the 3 open tickets are actually done. We may still need to build a board with the metrics that have been added.
