### ISSUE TITLE
[Epic] Connection streams table redesign

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18187]
```[tasklist]
- [x] #19142
- [x] #19092
- [x] #18188
- [x] #18242
- [x] #18243 
- [x] #18186
- [x] #17823 
- [x] #17937 
- [x] #20372
- [x] #19918
- ~#19308~
- [x] #20196
- [x] #20450 
- [x] #20451
- [x] #21338
- [x] #20452
- [x] #20454
- [x] #20455
- [x] #20584
- [ ] #18267 
- [ ] https://github.com/airbytehq/airbyte/issues/20969
- [ ] https://github.com/airbytehq/airbyte/issues/22196
- [ ] https://github.com/airbytehq/airbyte/issues/22429
- [ ] #22624
- [ ] #22625 
- [ ] #22626 
- [ ] #21772
- [ ] https://github.com/airbytehq/airbyte/issues/24163
```

**Comment by josephkmh** [comment]
@edmundito does it make sense to add this column selection issue to your epic as well? https://github.com/airbytehq/airbyte/issues/20584

**Comment by edmundito** [comment]
It's live! Future improvements will be handled outside of the epic as individual enhancements or new epics.
