### ISSUE TITLE
First E2E test for connection streams table redesign

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18267]
Create initial e2e test for new connection table during the connection create state. This is the first pass for supporting the new table in end to end testing

* Test should try to create a connection, set some values in the table, and then delete the table.
* Provide list of items that were not covered in the test so that it can be broken down into different Github issues.

### Tasks
```[tasklist]
- [x]  Add base test ( https://github.com/airbytehq/airbyte/pull/22412):
    - [x] Create Source and Destination via API
    - [x] Populate DB
    - [x] Implement flow: New connection => Existing Source => Existing destination => New Connections Stream table
    - [x] Check page routing(how app redirects and where we are after actions)
    - [x] Set Replication Frequency to `Manual`
    - [x] Set up connection - check API response (partially)
    - [x] Clean up: remove the connection, source, and destination
- [ ] Test specifically for Streams Table functionality (https://github.com/airbytehq/airbyte/pull/22582):
    - [x] Check Source and Destination connector icons
    - [x] Check table columns names
    - [x] Check how many rows are displayed(actual/expected amount). _Need to prepare appropriate test data_
    - [x] Check table filtering
    - [x] Check table scrolling
```

- [ ] Check table empty state (empty source/empty filter results) (**blocked** by https://github.com/airbytehq/airbyte/issues/22505) (TODO: Split into its own issue)
    

TODO: Split each root task into other github issues
- [ ] Test stream:
    - [ ] Turn off the sync stream (stream should have a red background and minus icon on the right)
    - [ ] _Stream select (will be covered in bulk edit tests)_
    - [ ] Check stream namespace, stream name, selected sync mode, destination namespace, destination stream name
    - [ ] Check the stream details panel opening by clicking on stream(row)
    - [ ] Stream should have all available sync modes
- [ ] Test stream sync modes(source and destination should support all available). Check that some sync modes have required fields(cursor and PK) :
    - [ ] Incremental Dedup + History: Courser defined and PK defined
    - [ ] Incremental Dedup + History: Select Cursor value(only one can be selected)  and PK defined
    - [ ] Incremental Dedup + History: Select Cursor value(only one can be selected)  and select PK (can be selected multiple) 
    - [ ] Incremental Dedup + History: Courser defined  and select PK (can be selected multiple)
    - [ ] Incremental + Append: cursor is required
    - [ ] Full refresh + Overwrite: cursor and PK are not supported
    - [ ] Full refresh + Append: cursor and PK are not supported
- [ ] Test stream details panel
    - [ ] ...will be updated... 
- [ ] Test bulk edit panel
    - [ ] ...will be updated...

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by colesnodgrass** [comment]
Discussed in grooming session on 20221026, follow-ups:
- [ ] @edmundito to add description to this ticket

**Comment by tealjulia** [comment]
currently missing test case: stream details (fields) panel opens as expected

**Comment by edmundito** [comment]
@dizel852 I updated the description of this task to indicate what needs to be split into other issues.

**Comment by dizel852** [comment]
@edmundito done:
https://github.com/airbytehq/airbyte/issues/22640
https://github.com/airbytehq/airbyte/issues/22641
https://github.com/airbytehq/airbyte/issues/22643
https://github.com/airbytehq/airbyte/issues/22644

**Comment by krishnaglick** [comment]
Closing since followup tickets have been made, and work has been done.
