### ISSUE TITLE
Source Delighted: Migrate connector from Alpha (Python) to Beta (YAML)

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#18711]
### According to the [checklist](https://docs.google.com/spreadsheets/d/1FeNDtlcLRz--cfy1lByy556P3_gNCeS27Et3Foio_ws/edit#gid=1288588270):
- [MLP](https://docs.google.com/document/d/13aE-FB8ZdqBIQ7Nv-sDs4LBK-1U2NmGPmIKfRMEokfI/edit#heading=h.22fd5raysmm3) improvements:
- All outstanding bug reports blocking Beta: --
 
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should be placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://drive.google.com/drive/folders/1gF08xGXrpUsNwga4_1XemTHellTlhj5N)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by misteryeo** [comment]
@davydov-d added a few comments in the checklist
