### ISSUE TITLE
[EPIC] Source SalesLoft to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#19217]
### According to [checklist](https://docs.google.com/spreadsheets/d/1RtzgwOz_ik2xpuLtt6CsuSCilQ2dTBMiEtwiAVDDoeg/edit?usp=sharing):

- MLP improvements:
  [SalesLoft source](https://docs.google.com/document/d/13hpdr1zvqvn8ge8lr9fvVGm7nBs8A6PGcH9RrP7NJ2k/edit?usp=sharing)

- All outstanding bug reports blocking Beta:
   - [x] https://github.com/airbytehq/airbyte/issues/13659
   - [x] https://github.com/airbytehq/airbyte/issues/13660

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [x] Checklist filled up by engineering team
- [x] Collect and list all tech debt-related issues in the section below
- [x] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [x] Move checklist to the unblockers team
- [x] Reviewed/Updated by unblockers team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [x] Certification completed
 
</details>

**Comment by igrankova** [comment]
Planned to Q1 2023
cc @YowanR
