### ISSUE TITLE
Epic: CDK v2

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19239]
## Tell us about the problem you're trying to solve
This issue is an aggregator for issues we might want to prioritize in the next breaking change of the CDK

- [ ] https://github.com/airbytehq/airbyte/issues/9722
- [ ] https://github.com/airbytehq/airbyte/issues/14012 and https://github.com/airbytehq/airbyte/issues/3284
- [ ] https://github.com/airbytehq/airbyte/issues/5755
- [ ] https://github.com/airbytehq/airbyte/issues/2820
- [ ] https://github.com/airbytehq/airbyte/issues/3257
- [ ] https://github.com/airbytehq/airbyte/issues/10301
- [ ] https://github.com/airbytehq/airbyte/issues/7972
- [ ] https://github.com/airbytehq/airbyte/issues/7390
- [ ] https://github.com/airbytehq/airbyte/issues/11824
- [ ] https://github.com/airbytehq/airbyte/issues/19238

**Comment by girarda** [comment]
closing the epic because we're not actively working on this
