### ISSUE TITLE
[EPIC] Lowcode to GA

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#19658]
Placeholder epic to track issues to resolve as part of promoting the framework to GA

### UX improvements
- [x] https://github.com/airbytehq/airbyte/issues/19334
- [ ] https://github.com/airbytehq/airbyte/issues/18435
- [x] https://github.com/airbytehq/airbyte/issues/18052
- [ ] Split between url_base and path is confusing
- [ ] https://github.com/airbytehq/airbyte/issues/16554
- [ ] https://github.com/airbytehq/airbyte/issues/15868
- [ ] https://github.com/airbytehq/airbyte/issues/18126
- [ ] https://github.com/airbytehq/airbyte/issues/16559
- [ ] [Easy to forget that you need to rebuild the docker image for some operations](https://github.com/airbytehq/airbyte/pull/17918#issuecomment-1276803724)
- [ ] https://github.com/airbytehq/airbyte/issues/14363
- [x] https://github.com/airbytehq/airbyte/issues/15467

### Documentation
- [ ] [Better onboarding docs for first connector](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1663260834568809)
- [ ] [Difficult to configure OAuthAuthenticator](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1663260834568809)
- [ ] [A getting-started-addon for how to create the schema-files would be awesome](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1663260834568809)
- [ ] [Better explanation of the difference between stream slicer and pagination](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1663004423665499)
- [ ] [Not enough documentation on substreamslicer](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1662747417995429)
- [ ] [Diffs in tutorial should be highlighted](https://airbytehq-team.slack.com/archives/C03TP6W8081/p1660858849144129)
- [ ] https://github.com/airbytehq/airbyte/issues/18062
- [x] https://github.com/airbytehq/airbyte/issues/18663
- [ ] https://github.com/airbytehq/airbyte/issues/15184
- [x] https://github.com/airbytehq/airbyte/issues/14592

### Bugs
- [ ] https://github.com/airbytehq/airbyte/issues/18088
- [ ] https://github.com/airbytehq/airbyte/issues/17802
- [ ] https://github.com/airbytehq/airbyte/issues/17281
- [ ] https://github.com/airbytehq/airbyte/issues/18136
- [x] https://github.com/airbytehq/airbyte/issues/15628
- [ ] https://github.com/airbytehq/airbyte/issues/17801
- [ ] https://github.com/airbytehq/airbyte/issues/15576

### Feature requests
- [x] https://github.com/airbytehq/airbyte/issues/17107
- [ ] https://github.com/airbytehq/airbyte/issues/18783
- [ ] https://github.com/airbytehq/airbyte/issues/19406
- [ ] https://github.com/airbytehq/airbyte/issues/18784
- [x] https://github.com/airbytehq/airbyte/issues/15737
- [ ] https://github.com/airbytehq/airbyte/issues/18322
- [ ] https://github.com/airbytehq/airbyte/issues/18769
- [ ] https://github.com/airbytehq/airbyte/issues/18440
- [ ] https://github.com/airbytehq/airbyte/issues/13429
- [ ] https://github.com/airbytehq/airbyte/issues/13196
- [ ] https://github.com/airbytehq/airbyte/issues/13001
- [ ] https://github.com/airbytehq/airbyte/issues/12996
- [ ] https://github.com/airbytehq/airbyte/issues/12992
- [ ] https://github.com/airbytehq/airbyte/issues/12986
- [ ] https://github.com/airbytehq/airbyte/issues/12984
- [ ] https://github.com/airbytehq/airbyte/issues/12980
- [ ] https://github.com/airbytehq/airbyte/issues/12979
- [ ] https://github.com/airbytehq/airbyte/issues/12973
- [ ] https://github.com/airbytehq/airbyte/issues/12930
- [ ] https://github.com/airbytehq/airbyte/issues/12929

### Tech debt
- [x] https://github.com/airbytehq/airbyte/issues/14012

**Comment by girarda** [comment]
closing the epic because this is not something we're actively working on
