### ISSUE TITLE
Integration with Asana

### ISSUE THREAD

**Issue by tsw-attila** [airbytehq/airbyte#1969]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Would be great to add Asana to your sources.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368211269044) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@tsw-attila thanks for your request. Could you give us some context on the connector by answering the questions in the issue description? Specifically: 
* Which sources/destinations you'd like to use in conjunction with Asana
* What is your usecase for replicating asana data? 
* Would you be open to contributing the connector?

**Comment by hoanghapham** [comment]
Not sure about the OP's use case, but I am also interested in this.
I am looking for a way to pull Asana task statistics into our BigQuery data warehouse to have visibility of our operations. Questions that we have are:
- How long does it take for a task to be completed? Break down to team members.
- What are the task types that take the longest to complete? (by using tags as a dimension)

So far I see Stitch has an integration. However I am considering using Airbyte for other ETL tasks within the company, so if Asana is supported, we do not need to add another tool to the stack.

**Comment by sherifnada** [comment]
@hoanghapham thanks for the context! We'll scope this work soon. Could you let us know: which of the [Asana API endpoints](https://developers.asana.com/docs) do you need support for?

**Comment by tsw-attila** [comment]
> @tsw-attila thanks for your request. Could you give us some context on the connector by answering the questions in the issue description? Specifically:
> 
> * Which sources/destinations you'd like to use in conjunction with Asana
> * What is your usecase for replicating asana data?
> * Would you be open to contributing the connector?

Hi @sherifnada thank you for getting in touch. First thing, I'm a novice so bear with me if my responses do not properly address the questions you asked.

> * I would probably use BigQuery or PostgreSQL as the destination
> * [Use  case is quite confusing] I am looking to analyse the asana data for performance on the various tasks, projects, and teams
> * Not sure how I can do that as a non-programmer. I only have basic working knowledge of SQL. I use BI tools extensively for analysis, and that's where it ends for me.

**Comment by sherifnada** [comment]
@tsw-attila no problem! thanks for the information. Which API endpoints would you like to sync using the connector? API docs: https://developers.asana.com/docs

**Comment by hoanghapham** [comment]
@sherifnada the one that I think our team will need are:
- Task
- Projects
- Users
- Teams, Team Memberships
- Events
- Stories
- Custom fields
- Tags

**Comment by sherifnada** [comment]
Deprioritized by one sprint, Will revisit next sprint (starting beginning of May)

**Comment by sherifnada** [comment]
## Integration Vetting
**Webhook-based? (no/partially/yes)**
it is webhook-capable but most endpoints are standard REST

**Available authentication modes (API key/Oauth/other)**
API Key + OAuth

**Creating an account**
Created a free account. Also applied for a developer sandbox account. 

**How to populate the account with data?**
_Can it be done entirely through the API?_ yes

**Available streams for sync**
listed here: https://developers.asana.com/docs/
 
**Integration supports incremental sync?**


**Other information/blockers**

**Comment by Zirochkaa** [comment]
**Are the account test credentials available in Lastpass?** No, only login+password and when I logged in I saw a message which said that our free 30-day trial has ended (see screenshot below):

<img width="730" alt="image" src="https://user-images.githubusercontent.com/19872253/116887103-93073f00-ac32-11eb-9c43-33df09ba8304.png">

And when I pressed `Select your plan` I saw this page:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/19872253/116887185-b205d100-ac32-11eb-87e6-96b6c4a683ee.png">

I'm not sure wether I'm allowed to select paid subscription or not so I just leave it to you @sherifnada .

## Note

We may look at [Asana Singer Tap](https://github.com/singer-io/tap-asana) code, but it needs to be checked whether it works or not first.

## Task breakdown

- [ ] Populate source with data (7h, because there are quite many streams that require data)
- [ ] Create source scaffolding and populate schemas folder (4h, may be extracted using [Asana Singer Tap](https://github.com/singer-io/tap-asana) code)
- [ ] Implement spec, check, and discover (8h)
- [ ] Implement Read (I'm actually not sure how long will take this step, but I believe it'll take more than 8h)
- [ ] Implement Incremental sync (6h)
- [ ] Handle rate limiting (3h)
- [ ] Implement standard tests (2h, but will see if they are needed)
- [ ] Add docs (3h)

Above time estimations are a little increased because I'd like to implement this source and this will be my first source so I beleave some parts of this task will take more time then if this was my, for example, fifth connector. Hope this makes sense.

**Comment by sherifnada** [comment]
for subscription use the sandbox accounts available in lastpass.

**Comment by Zirochkaa** [comment]
@tsw-attila and @hoanghapham 

We just merged this connector into master and released a new version of the connector. 

The connector will be available in the next release of Airbyte (we usually release every Tuesday). If you can't wait and want to get started now trying it out in a running Airbyte instance, add the connector like described in https://docs.airbyte.io/integrations/custom-connectors#adding-your-connectors-in-the-ui . The information for the connector is: 

**Display Name**: Asana
**Docker repository name**: airbyte/source-asana
**Docker image tag**: 0.1.0
**Documentation URL**: hub.docker.com/r/airbyte/source-asana

Please let us know if you have any further questions. 

Enjoy!

**Comment by hoanghapham** [comment]
Awesome, thanks a lot @Zirochkaa !
