### ISSUE TITLE
connector-builder-server to V1

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#19995]
- [x] https://github.com/airbytehq/airbyte/issues/19761
- [x] https://github.com/airbytehq/airbyte/issues/19499
- [x] https://github.com/airbytehq/airbyte/issues/19500

**Comment by flash1293** [comment]
@girarda All tasks done, can this be closed?

**Comment by flash1293** [comment]
@girarda All tasks done, can this be closed?
