### ISSUE TITLE
Postgres CDC

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2156]
## Tell us about the problem you're trying to solve
* CDC is one of the most sought after features from our users.

## Describe the solution you’d like
* [x] Define what features are included in CDC
* [x] Spec out how we will implement it in Airbyte
* [x] POC to see if debezium is a good choice ([issue](https://github.com/airbytehq/airbyte/issues/2465))
* [x] Consensus on CDC's interaction with the AB protocol ([issue](https://github.com/airbytehq/airbyte/issues/2466))
* [x] Implement debezium jdbc source
* [x] Handle state management ([issue](https://github.com/airbytehq/airbyte/issues/2549))
* [x] Handle logic on when to close debezium ([issue](https://github.com/airbytehq/airbyte/issues/2549))

[Spec](https://docs.google.com/document/d/1QUTafE8EUr4UfB87gNUZFc9C4ZVyOVchrVXzxAsnYrk/edit?usp=sharing)

## Related
* https://github.com/airbytehq/airbyte/issues/957

**Comment by sherifnada** [comment]
TIL [Debezium](https://github.com/debezium/debezium) supports embedded CDC. I don't know if this is a good solution, but it's relevant since we brought up Debezium last week. 

Relevant section from the README: 

> Applications that don't need or want this level of fault tolerance, performance, scalability, and reliability can instead use Debezium's embedded connector engine to run a connector directly within the application space. They still want the same data change events, but prefer to have the connectors send them directly to the application rather than persist them inside Kafka.

**Comment by cgardens** [comment]
[wal2json](https://github.com/eulerto/wal2json) is the library that I spent some time looking at a little while ago. I found it, because it is what the the Singer `tap-postgres` uses. The thing to note here is that it only handles writing _postgres_ WALs to a json object formatted specifically for wal2json. It is not obviously extensible to other dbs. It may still be useful in just extract the WAL from a postgres db (even if we have to do further transformation). 

I spent some time trying to set this up on 2 local databases but got hung up and never got back to finishing it. The key here is that it's non-trivial to set up because you have to mess with your db settings. I think this is likely going to be true no matter what tool we use.

**Comment by michel-tricot** [comment]
That's really cool to get an MVP up and running!

**Comment by michel-tricot** [comment]
Yep regarding the setup complexity. CDC requires the logs to be created which isn't a default

**Comment by ChristopheDuong** [comment]
You can take a look at this too: https://www.stitchdata.com/docs/integrations/databases/postgresql/v1#install-wal2json-plugin

**Comment by sherifnada** [comment]
Separately, some questions I have about CDC: 

1. Is it going to be only within DBs (e.g: PG to PG) or is there a world where it makes sense to have it work across DBs as well? We don't need to implement anything more than single-DB CDC out the gate but it may affect our approach if the latter idea is desirable. 
2. How will it impact the protocol? An assumption we had previously is that you can hook up any source to any destination. With CDC this assumption changes.

**Comment by cgardens** [comment]
[proposal](https://github.com/airbytehq/airbyte/pull/2522) on how to handle CDC metadata. Ultimately we are nto going in this direction, but documenting it here for posterity.

**Comment by cgardens** [comment]
updated the description with progress from last week and with new to dos for this week.

**Comment by jrhizor** [comment]
Remaining:
- [ ] configuring table includes
- [ ] updating catalog for metadata fields
- [ ] allowing replication modes based on primary key existence
- [ ] set up replication slot as a `oneOf` field
- [ ] handle termination
- [ ] make sure full refresh edge cases are handled
- [ ] make sure WAL expiration edge cases are handled

**Comment by jrhizor** [comment]
@cgardens should we rename this to postgres / mark it as a duplicate with https://github.com/airbytehq/airbyte/issues/957 ?  Then create separate tickets for other CDC sources?

**Comment by cgardens** [comment]
Yeah
