### ISSUE TITLE
E2E stream table tests - stream sync modes

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#22641]
## Tell us about the problem you're trying to solve
Add E2E tests for stream sync modes functionality in the new stream table

Test stream sync modes(source and destination should support all available). Check that some sync modes have required fields(cursor and PK)

### Tasks
- [x] Cursor or PK field is marked as required (with a red background color) when the user needs to choose values. The user should not be able to save connection settings without the required values.
- [x] _Double-check - If stream sync is disabled, do we still require to set the cursor and pk fields?_
- [x] Incremental Dedup + History: Cursor defined and PK defined
- [x] Incremental Dedup + History: Select Cursor value(only one can be selected)  and PK defined
- [x] Incremental Dedup + History: Select Cursor value(only one can be selected)  and select PK (can be selected multiple) 
- [x] Incremental Dedup + History: Courser defined  and select PK (can be selected multiple)
- [x] Incremental + Append: cursor is required
- [x] Full refresh + Overwrite: cursor and PK are not supported
- [x] Full refresh + Append: cursor and PK are not supported

**Comment by edmundito** [comment]
Optical Sync mode default setting has been extracted to #23449
