### ISSUE TITLE
E2E stream table tests - test stream functionality

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#22640]
## Tell us about the problem you're trying to solve
Add E2E tests for stream functionality in the new stream table

### Tasks

- [x] Check stream namespace, stream name, selected sync mode, destination namespace, destination stream name
- [x] Turn off the sync stream - stream should have a red background and minus icon on the right)
- [x] Check the stream details panel opening/closing by clicking on stream(row)
- [ ] Stream should have all available sync modes
- [ ]  _Stream select (will be covered in bulk edit tests)_

**Comment by edmundito** [comment]
> When a new stream is added to the table: after refreshing the source schema or just turning on the disabled sync stream. _Note_: this case can be tested in connection Update mode only.

This may need to be split into its own issue.

> When a new stream is added to the table: after refreshing the source schema or just turning on the disabled sync stream. _Note_: this case can be tested in connection Update mode only.

Can probably be removed

**Comment by dizel852** [comment]
> This may need to be split into its own issue.

Agree, moved to: https://github.com/airbytehq/airbyte/issues/23470

**Comment by dizel852** [comment]
Сlosing this one since it was already migrated and merged to `-internal`
