### ISSUE TITLE
E2E stream table tests - stream details panel

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#22643]
## Tell us about the problem you're trying to solve
Add E2E tests for stream details panel functionality in the new stream table

### Tasks
- [x] Check panel opening (this case should be covered in https://github.com/airbytehq/airbyte/issues/22640)
- [x] Check stream details info: sync state, namespace(if exist), stream name, chosen sync mode
- [x] Check amount of displayed fields(depends on tests data we will use)
- [x] Check that user is able to scroll a long list of fields()scrolling and desired field is visible 
- [x] Check that each field has info: source field name, data type, Cursor(optional), PK(optional), destination field name
- [x] Check that user is able to select only one cursor value (appropriate sync mode should be chosen)
- [x] Check that user is NOT able to select only one cursor value if it's source-defined (appropriate sync mode should be chosen)
- [x] Check that user is able to select only multiple PK values (appropriate sync mode should be chosen)
- [x] Check that user is NOT able to select PK value if it's source-defined (appropriate sync mode should be chosen)
