### ISSUE TITLE
E2E stream table tests - test stream bulk edit panel

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#22644]
## Tell us about the problem you're trying to solve
Add E2E tests for stream bulk edit panel functionality in the new stream table

### Tasks
- [ ] Select All streams
- [ ] Select streams that are filtered only
- [ ] Cannot click on search when bulk edit panel is open
- [ ] Cannot save/cancel replication changes when panel is open
- [ ] Check that it only supports overlapping sync modes
- [ ] Cursor mode can be set
- [ ] Primary Keys can be set
- [ ] Shows source defined cursor and primary key
- [ ] Shows not available for cursor and primary key
- [ ] Validate cancel changes
- [ ] Validate apply changes
- [ ] Cancels when all streams are de-selected

**Comment by josephkmh** [comment]
Closing because we are going to remove the bulk edit feature
