### ISSUE TITLE
New Source: Fastly

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2306]
## Tell us about the new integration you’d like to have
I'd like to pull data from [Fastly](https://developer.fastly.com/reference/api/) using Airbyte. The main stream I need to pull is: 
* [Billing](https://docs.fastly.com/api/account#billing)

There is a Singer tap [here](https://gitlab.com/meltano/tap-fastly) which we could use.

**Comment by keu** [comment]
## Integration Vetting

**Webhook-based? (no)**

**Available authentication modes (API key)**

**Creating an account**
_self-service free account available? Yes, created, email needs to be confirmed

**How to populate the account with data?**
There is no way to populate an account with test data without actually registering the website and generate traffic. Up to 50$ traffic is included in the free account.

**Available streams for sync**
 Billing

**Integration supports incremental sync?**
No

**Other information/blockers**
It is quite difficult to populate a test account with the data

**Comment by sherifnada** [comment]
@keu can you put the creds for the account in lastpass?

**Comment by keu** [comment]
**Are the account test credentials available in Lastpass?** Yes

## Task breakdown
- [ ] Populate source with data, this could be quite a massive task or even blocker
- [ ] Create source with all streams and full table sync method
- [ ] Ensure that connector follows the best practices.
