### ISSUE TITLE
New Source: Quickbooks

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2309]
## Tell us about the new integration you’d like to have
I would like to pull data from the [Quickbooks API](hhttps://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/account) using Airbyte for the following streams: 

* Account
* Customer
* Credit Memo
* Item
* Invoice
* Journal Entry
* ProfitAndLoss

There is a maintained Singer tap [here](https://github.com/hotgluexyz/tap-quickbooks/) that we could use.

**Comment by vitaliizazmic** [comment]
## Integration Vetting
The integration hasn't already been vetted in https://docs.google.com/spreadsheets/d/1CUkw5ha0zPGJT1-vhe2rT3oIWt_6rVieH40J9fVrLJM/edit#gid=0

[https://developer.intuit.com/app/developer/qbo/docs/get-started](https://developer.intuit.com/app/developer/qbo/docs/get-started)

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
OAuth 2.0 [Access Token](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization)

[Python sample](https://github.com/intuitdeveloper/oauth2pythonsampleapp)

**Creating an account**
Free 30-day trial

[Pricing](https://quickbooks.intuit.com/global/pricing/)

**How to populate the account with data?**
[Sandboxes](https://developer.intuit.com/app/developer/qbo/docs/develop/sandboxes)

**Comment by sherifnada** [comment]
@vitaliizazmic can we permanently use the sandbox account without needing to use the 30-day trial account?

**Comment by vitaliizazmic** [comment]
@sherifnada no. Sandbox environment it's a part of Intuit Developer account. We need to create account to use it. In general accounts are paid.  But we can use 30-day trial.

**Comment by sherifnada** [comment]
I just noticed that while the API uses oauth, it also offers an [oauth playground](https://developer.intuit.com/app/developer/playground) to quickly run oauth in the UI, which makes implementation easier

**Comment by sherifnada** [comment]
There's also another singer tap which seems more developed: https://github.com/singer-io/tap-quickbooks

We should make a choice between which of the two to use

**Comment by vitaliizazmic** [comment]
We can use [Singer Tap](https://github.com/singer-io/tap-quickbooks) to implement new source.

It uses requests_oauthlib.OAuth2Session All we need to set in configs next parameters:
- client_id
- client_secret
- refresh_token
They can be received via [OAuth 2.0 Playground](https://developer.intuit.com/app/developer/playground). Before that you should create app. 

Singer Tap doesn't support one requested stream - ProfitAndLoss. But we can create fork.

Singer Tap supports Full and Incremental syncing.

We can use Sandbox, so we don't need to populate data.

Singer Tap handles errors and rate limits using backoff.

**Task breakdown**

- [ ] Create fork for supporting all requested streams - 3-5h
- [ ] Create new Source based on fork - 3-4h
- [ ] Run integration tests and check new source - 2-3h

**Comment by sherifnada** [comment]
@vitaliizazmic we can skip creating a fork for the extra stream. let's only do that when support is requested by a user.

**Comment by lluisgassovillarejo** [comment]
Hello!
I'd be very interested in getting the ProfitAndLoss table in the Quickbooks connector, but I see this is in the backlog. Are there any changes this gets added? Can I help in any way or form?
Thanks in advance
