### ISSUE TITLE
[EPIC] Stream-Centric UI v1

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#23345]
[Figma](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=5874%3A108663&scaling=min-zoom&page-id=5874%3A106949&starting-point-node-id=5874%3A110892&show-proto-sidebar=1)
[Figma, syncing](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=5874%3A109221&scaling=min-zoom&page-id=5874%3A106949&starting-point-node-id=5874%3A110892&show-proto-sidebar=1)
[Figma, error state](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=5874%3A108857&scaling=min-zoom&page-id=5874%3A106949&starting-point-node-id=5874%3A110892&show-proto-sidebar=1)
[Figma, action required state](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=5874%3A109039&scaling=min-zoom&page-id=5874%3A106949&starting-point-node-id=5874%3A110892&show-proto-sidebar=1)

The linked Figma is for a scoped-down and the feature needs the following:

## Frontend
```[tasklist]
- [ ] https://github.com/airbytehq/airbyte/issues/25292
- [ ] https://github.com/airbytehq/airbyte/issues/25293
- [ ] https://github.com/airbytehq/airbyte/issues/25294
- [x] Ensure free connector program banner still exists when feature flag is on
- [ ] https://github.com/airbytehq/airbyte/issues/23631
- [ ] https://github.com/airbytehq/airbyte/issues/23633
- [ ] https://github.com/airbytehq/airbyte/issues/23636
- [ ] https://github.com/airbytehq/airbyte/issues/23645
- [ ] https://github.com/airbytehq/airbyte/issues/23637
- [ ] https://github.com/airbytehq/airbyte/issues/23639
- [ ] https://github.com/airbytehq/airbyte/issues/23841
- [ ] https://github.com/airbytehq/airbyte/issues/23770
- [ ] https://github.com/airbytehq/airbyte/issues/23772
- [ ] https://github.com/airbytehq/airbyte/issues/23773
- [ ] https://github.com/airbytehq/airbyte/issues/23640
- [ ] https://github.com/airbytehq/airbyte/issues/23912
- [ ] https://github.com/airbytehq/airbyte/issues/23638
- [ ] https://github.com/airbytehq/airbyte/issues/23991
- [ ] https://github.com/airbytehq/airbyte/issues/24325
- [ ] https://github.com/airbytehq/airbyte/issues/24072
- [x] Ensure the app functions as expected with stream first ux disabled
- [x] Verify reset data button on status page resets all expected streams compared to which streams the logs page resets
- [ ] https://github.com/airbytehq/airbyte/issues/24187
- [ ] https://github.com/airbytehq/airbyte/issues/24468
- [ ] https://github.com/airbytehq/airbyte/issues/24400
- [ ] https://github.com/airbytehq/airbyte/issues/24585
```

## Backend
```[tasklist]
- [ ] https://github.com/airbytehq/airbyte/issues/23648
- [ ] https://github.com/airbytehq/airbyte/issues/24337
```
