### ISSUE TITLE
epic - gradle updates

### ISSUE THREAD

**Issue by colesnodgrass** [airbytehq/airbyte#23735]
Epic issue to track issues with or changes we want to make to our gradle implementation.
- [ ] introduce an `airbyte` gradle plugin (with tests!)
    - [ ] with docker support
    - [ ] with publishing support
    - [ ] with local start-up support
- [ ] ensure caching is working for oss and non-oss builds
- [ ] update to gradle 8
