### ISSUE TITLE
[EPIC] Stream-Centric UI v2

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#23875]
v1: #23345

```[tasklist]
- [ ] https://github.com/airbytehq/airbyte/issues/23635
- [ ] https://github.com/airbytehq/airbyte/issues/23644
- [ ] https://github.com/airbytehq/airbyte/issues/23638
```

**Comment by timroes** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/25123
