### ISSUE TITLE
Update the catalog_generation job to be based off of GCS

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#24023]
# Overview
Add a job that downloads all metadata files from gcs and parses it into the oss_catalog.json and cloud_catalog.json files respectively.

This should also
1. Add a the [ConnectorRegistry](https://github.com/airbytehq/airbyte-types/blob/main/models/src/main/resources/ConnectorRegistry.yaml) json schema files to the `lib/models/generated` to validate the catalogs are correct
2. Update the `generate-models` task to generate more than one type ([example script here](https://github.com/airbytehq/airbyte-types/blob/main/models/bin/generate-python-classes.sh))

## TODO
- [x] On new metadata file create catalog and write to registry
- [x] validate with new type
- [x] update to have a legacy catalog asset
- [x] update diff for legacy catalog asset
- [x] Ensure were using V0 instead of V1 for types
- [ ] Output report

**Comment by evantahler** [comment]
Grooming

* This story also includes adding the JSON Schema types and validating the output of generate_model - multiple schemas and multiple files
* If the schema isn't valid, the whole pipeline should fail (and then we should be notified in Slack)
