### ISSUE TITLE
New Source: Iterable

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2412]
## Tell us about the new integration you’d like to have
I would like Airbyte to integrate with [Iterable](https://iterable.com/)

## Describe the context around this new integration
* I am looking to cut cost from 5tran

## Describe the alternative you are considering or using
Continue to use 5tran

**Comment by sherifnada** [comment]
@arhip11 I've pushed this to the top of the vetting list to bump its vetting priority (not urgent, just higher priority for vetting)

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**

no

**Available authentication modes (API key/Oauth/other)**

[API key (Standard)](https://support.iterable.com/hc/en-us/articles/360043464871-API-Keys-)

Airbyte account already created, credentials in the Lastpass account.

**How to populate the account with data?**

It can be done entirely through the [API](https://api.iterable.com/api/docs#campaigns_create_campaign) and some entities using UI

**Available streams for sync**

 * [lists](https://api.iterable.com/api/docs#lists_getLists)
 * [list_users](https://api.iterable.com/api/docs#lists_getLists_0)
 * [campaigns](https://api.iterable.com/api/docs#campaigns_campaigns)
 * [channels](https://api.iterable.com/api/docs#channels_channels)
 * [message_types](https://api.iterable.com/api/docs#messageTypes_messageTypes)
 * [templates](https://api.iterable.com/api/docs#templates_getTemplates)
 * [metadata](https://api.iterable.com/api/docs#metadata_list_tables)
 * [users](https://api.iterable.com/api/docs#users_getUserById_0)

**Integration supports incremental sync?**

no

**Other information/blockers**

For implement current connector can be used [tap-iterable](https://github.com/lambtron/tap-iterable)

**Comment by michel-tricot** [comment]
According to the existing tap, it seems to support incremental for some of the endpoints: https://github.com/lambtron/tap-iterable/blob/b8f6734008616e2de78de638a29ae8a3afdc2af6/tap_iterable/iterable.py#L160

**Comment by yevhenii-ldv** [comment]
@michel-tricot Thank you, I missed the opportunity to increment for streams that need to be received using the [data export](https://api.iterable.com/api/docs#export_exportDataJson) method.

**Comment by yevhenii-ldv** [comment]
## Task breakdown
- [ ] Populate source with data. (estimation 6h, there are several streams responsible for Email, it can be difficult to create fake data for them). 
- [ ] Create source with all streams with full/incremental sync(using Singer Tap) (estimation 5h)
- [ ] Ensure that connector follows the best practices, rate limiting, retry call, proper error messages, has tests (estimation 4h).

### Note
1. To get data on streams: `email_bounce`, `email_unsubscribe`, `email_subscribe`, `email_send_skip`, `email_send`, `email_open`, `email_complaint`, `email_click` and `users` uses the [export JSON endpoint](https://api.iterable.com/api/docs#export_exportDataJson), where it is indicated that only 4 requests can be made per minute. Considering that these streams support incremental, the first launch can take quite a long time.
2. The existing Tap supports a handling Rate Limit (backoff), however it does delay all types of errors from the API. This means that it handles errors `401`, `400`, `429`, `403` and other the [same way](https://github.com/lambtron/tap-iterable/blob/b8f6734008616e2de78de638a29ae8a3afdc2af6/tap_iterable/iterable.py#L47), and if something goes wrong, the user will receive an error only after 10 attempts to reach the server (approximately 350 seconds).

**Comment by sherifnada** [comment]
@yevhenii-ldv things to verify: 

1. Can we sync data for the entire date range? this way we only need to make N requests every sync (N is the number of streams)
2. can we find out how any existing singer taps deal with this process?

**Comment by yevhenii-ldv** [comment]
@sherifnada 

1. yes, we can make a request for the entire date range, so these streams will be Full Refresh.
2. absolutely, errors are handled incorrectly, the backoff works for all errors, not just for Rate Limiting

Based on the issues described above, I think it would be better to create a connector without Singer Tap than make fork for Singer Tap and update it.

**Are the account test credentials available in Lastpass?** Yes

## Task breakdown

- [ ] Populate source with data (5-6h)
- [ ] Create source scaffolding and populate schemas folder (2h, can using schemas from Singer Tap)
- [ ] Implement spec, check, and discover (3h)
- [ ] Implement Read 
    - [ ] Create API base abstract class (2h)
      - [ ] Create Base stream abstract classes (6h)
- [ ] Handle rate limiting (2h)
- [ ] Implement standard tests (2h)
