### ISSUE TITLE
Source: Okta

### ISSUE THREAD

**Issue by arhip11** [airbytehq/airbyte#2414]
## Tell us about the new integration you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368094671073) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**
No

**Available authentication modes (API key/Oauth/other)**
Oauth: https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/create-serviceapp-grantscopes/

**Creating an account**
Self serve free account can be created. **I did not create one for Airbyte**. 

**How to populate the account with data?**
I think we'll need to create some fake users and simulate events for them through the UI. 

**Available streams for sync**
 Full list available in the API docs under "Manage Okta Objects" : https://developer.okta.com/docs/reference/api/

The ones we care about for an MVP are: 
* Groups / Group Memberships
* System logs
* Users

**Integration supports incremental sync?**
Yes, see the filtering section in "API overview"

**Comment by arhip11** [comment]
Account created, password saved to LastPass.
@sherifnada - is anything else required?

**Comment by sherifnada** [comment]
@arhip11 not for the moment. We will prioritize soon! Thanks for getting it ready for implementation.

**Comment by sherifnada** [comment]
using this for Santa as an oauth/jwt test vehicle

**Comment by sherifnada** [comment]
Successfullly implemented oauth for okta in Santa. Next steps will be to fully implement the connector. Should be very straightforward - hardest part is obtaining the refresh token.

**Comment by sherifnada** [comment]
I've added the Oauth refresh token to lastpass. We should be able to use this using the CDK and the `Oauth2Authenticator` as the `authenticator`

**Comment by keu** [comment]
can be used as an example for auth and read/write data https://github.com/okta/okta-sdk-python

**Comment by keu** [comment]
**Are the account test credentials available in Lastpass?** Yes,
go to https://okta-devok12.okta.com/ and use `integration-test+2@airbyte.io`

## Task breakdown
- [ ] Populate source with data (this package can be used for write and read, events can be generated by adding/removing a user to a group)
- [ ] Create source scaffolding and populate schemas folder
- [ ] Implement spec, check and discover
- [ ] Implement Read
    - [ ] Create API base abstract class 
	- [ ] Create Base stream abstract classes
	- [ ] Implement base abstract classes for incremental streams 
- [ ] Handle rate-limiting and back off, add unit tests for it
- [ ] Integrate with acceptance tests

**Comment by grebessi** [comment]
The problem was related to `tap-github` trying to convert a none value to a date.
The PR for this fix is here:
https://github.com/airbytehq/tap-github/pull/3
After it gets approved and released, we will be able to upgrade the package.
