### ISSUE TITLE
[Epic] Destination Performance: Snowflake sync speed to 5 Mb/s (POC)

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#24771]
## What

Destination connectors are bottlenecked by the fact that every process is sequential which means that when a "write process" is kicked off there will be a blocker on the Destination's connectors' ability to read incoming `AirbyteRecordMessages`. As a result, this also causes back-pressure on the platform and the source connector as well

The goal of this project is to increase the throughput of the Destination connector by splitting the reading process and the writing of records as well as handling STATE message(s)

## How

- [ ] Refactor `StagingConsumerFactory`, `BufferedStreamConsumer`, and `SerializedBufferingStrategy` to de-couple the logic of adding records to also handle flushing
- [ ] Refactor components within `StagingConsumerFactory` to limit impact radius to only `Snowflake` instead of all connectors that use `StagingConsumerFactory` (e.g. `destination-redshift`)
- [ ] Test throughput with mocked data

**Comment by evantahler** [comment]
Doc is here https://docs.google.com/document/d/1JAzsk7x0__-k3Fv6fWlws4r0mtqlFwi5NHzQBqkWfHA/edit#heading=h.9nkp6n15eqz3
