### ISSUE TITLE
[Epic] Destination Snowflake to 10 MB/s

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24788]
## Defintion of Done:
* All Cloud workspaces are using a new version of the Snowflake connectors capable of 10Mb/s as shown in at least one workspace. 

## Steps (to be made into stories attached to this epic)
1. Blocked by being able to release just one connector
2. POC already for splitting writing (staging) thread from reading (main) thread
3. Properly handle state management in multiple threads
    * Failure Propagation
    * Handle CDC (all buffers are flushed before state applies).  Per stream vs global checkpointing
4. Test connector on performance workspace
5. Deploy the new connector slowly and test and test along the way (blue/green)
...
99.  And keep looking for bottlenecks until we hit 10m/s (This could be where DataDog for destinations lands)

---

Old notes: from https://github.com/airbytehq/airbyte/issues/24771

## What

Destination connectors are bottlenecked by the fact that every process is sequential which means that when a "write process" is kicked off there will be a blocker on the Destination's connectors' ability to read incoming `AirbyteRecordMessages`. As a result, this also causes back-pressure on the platform and the source connector as well

The goal of this project is to increase the throughput of the Destination connector by splitting the reading process and the writing of records as well as handling STATE message(s)

## How

- [ ] Refactor `StagingConsumerFactory`, `BufferedStreamConsumer`, and `SerializedBufferingStrategy` to de-couple the logic of adding records to also handle flushing
- [ ] Refactor components within `StagingConsumerFactory` to limit impact radius to only `Snowflake` instead of all connectors that use `StagingConsumerFactory` (e.g. `destination-redshift`)
- [ ] Test throughput with mocked data

**Comment by evantahler** [comment]
We will also work with @rodireich to build a Destination test harness to get a reliable, isolated measure of our perfomance.

**Comment by kevin868** [comment]
How are you setting 10Mb/s as a goal? 
I am using Snowflake Destination 0.4.34, and I _believe_ I'm getting 70-100Mbps (as measured from the log, that reads:
`Records read: 39348000 (261 GB)` taking 6.5 hours. ->89 Mbps or 11MB/s 

However this is a pretty wide table so the final denormalized result is only 12.9GB on Snowflake. (but truly 261GB was transferred across the network due to the denormalization stuff).

Anyways I'm all in favor of this Epic.. we feel that Snowflake bulk upload is painfully slow.  In the latest Destination Snowflake connector (using latest Airbyte 44.0, Snowflake dest 0.4.61), things are even slower than the older versions we used above..

**Comment by jcowanpdx** [comment]
@kevin868 good questions. Thanks for raising these concerns.

The 10MB/s goal was set by an internal effort to measure end-to-end performance with a standard dataset in a performance test workspace (PostgreSQL to Snowflake). As such, it's a part of moving the goalposts higher all the time and giving us a target for measurement.  Down the road, the end to end targets will be higher and we'll explore other potential optimizations (stream parallelism is one idea) .We know that today, we can get higher or lower throughputs based on the shape of the data and whether normalization is in play (Normalization is undergoing a rework as well).

That is interesting that you have seen lower performance recently. Platform work is also ongoing, so we'll need to dig in a little bit on that. 0.4.34 goes back to July, which predates me so I'll take a look at the change sets.

**Comment by jcowanpdx** [comment]
@kevin868 I dug into the data a bit for throughput vs. connector version for Snowflake.

The data is inherently spiky due to frequency and size of syncs (esp. large syncs) for each connector version as well as data shape, etc. There are also system effects, as you know well. I filtered to syncs > 1GB to get rid of small noisy syncs.

For 0.4.34, over 695 syncs, we saw 2.76 MB/s, with a max of 15.99
For 0.4.61, over 320 syncs, we saw 3.44 MB/s, with a max of 14.85

We will continue to track these metrics going forward to ensure overall system improvement.

**Comment by jcowanpdx** [comment]
Destination Snowflake to 10MB/s

:white_check_mark: What's been accomplished:
Refactor PR hopefully merging today (4/25)?

:books: Learnings and hurdles:
CI/CD times are running high, test flakiness and high publish times and failures are significantly slowing the process down. Possibly related to experimental CI/CD changes.

:no_entry_sign: Blockers:
destination-snowflake integration tests are holding up a merge and publish. After that, Ryan and I can move forward.

:seedling: Looking ahead:
Started work on Executor and related classes. PR incoming today.
Working on shared tech doc w/ Ryan.

**Comment by evantahler** [comment]
[Writeup doc from April 28](https://docs.google.com/document/d/1v058U_IvD423h6GWkC89TSNLO7vFg1fdpinkHd1_58A/edit#)

**Comment by ryankfu** [comment]
Weekly project update for [Snowflake to 10 MBps](https://github.com/airbytehq/airbyte/issues/24788)

:white_check_mark:  What was done
* [Serialized Message Consumer](https://github.com/airbytehq/airbyte/pull/26700) to pass in a serialized message to the message consumer to reduce memory overhead of variable JsonNode
* [Async Destination Snowflake](https://github.com/airbytehq/airbyte/pull/26700):
  * STATE management for GLOBAL/PER-STREAM
  * Partial Deserialization
  * Improved Buffer Strategy (e.g. what are the rules that trigger a flush, handling at-capacity buffers across N streams, etc)
* Performance Harness
  * [Support for Incremental Syncs with GLOBAL state](https://github.com/airbytehq/airbyte/pull/26443)
  * [Support for mocking CDC stream](https://github.com/airbytehq/airbyte/pull/26219)

:seedling: Next steps:
* :rotating_light: Get reviews from the team on the [Serialized Message Consumer](https://github.com/airbytehq/airbyte/pull/26700) to ensure this change is a no-op for connectors :rotating_light:
* Merge in critical path changes, [Encapsulate and test triggers for assign flush workers](https://github.com/airbytehq/airbyte/pull/26706) , [Async Destination Snowflake](https://github.com/airbytehq/airbyte/pull/26703) by EOD
* The progressive rollout of Snowflake using feature-flags (will want to sync with 
[@Edward Gao (Airbyte)](https://airbytehq-team.slack.com/team/U02UC3SNJ72)
 on how to do this)

:books: Learnings and hurdles:
* The RecordEstimator is at best fuzzy and the memory overhead of deserializing a JSON string is enough that passing it down as a JSON string until flushing/loading is more valuable to utilize as much memory space as possible
* ChatGPT is an extremely valuable tool when needing to understand logs (e.g. garbage collection, the difference between young, full, old)

:no_entry: Blockers
* N/A

**Comment by ryankfu** [comment]
Weekly project update for Async Destinations

:white_check_mark: What's been accomplished:
- Async :snowflake: tests with multiple datasets
   - Postgres 20M, Faker 10M, and bottleneck stream
normalization works, integration tests pass, and resets run without NPE
- Speeds are still at [10 Mbps](https://airbytehq-team.slack.com/archives/C048E3BK1KM/p1687263149352179?thread_ts=1687235210.859209&cid=C048E3BK1KM) between Postgres <> AsyncSnowflake but with OOM fixes addressed in the performance workspace

:warning: What got in the way:
- Botched rollout with a bad serialized string to the CSV writer caused a P0 :facepalm:

:no_entry: Blockers:
- N/A - rollout commencing in the next hour!

:seedling: What's next:
- Start rolling out changes to 10% of Internal Staging Snowflake today
monitoring til 3 PM, if no failures then roll out 10% to all loading options of Snowflake
- File out stress testing tickets (passed the serialized state message, run sync with limited resources 800 MB of mem to see where OOM still occurs and GC takes up valuable CPU time)
- Work with the Sources team to get a CDC Postgres instance with multiple streams running daily in the performance workspace
- Follow up with affected customers that want to do a soft reset from last week's P0
