### ISSUE TITLE
[EPIC] Source Jira to GA

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#24834]
###  According to [checklist](https://docs.google.com/spreadsheets/d/12VxlfgS97JDrgDcDL0Z8FqC7IFf7EYwUGQd5EnYl6x4/edit#gid=1820065035):
 
- Docs
   - [ ] 

- All outstanding bug reports blocking GA:
   - [ ] 
  

- Label connector as GA in cloud:
   - [ ]  
   - [ ] 
  
<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/20357)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by igrankova** [comment]
duplicates [EPIC] Source Jira to GA #20596
