### ISSUE TITLE
New Source: Bing Ads

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2508]
## Tell us about the new integration you’d like to have
I would like to support the Bing Ads API as a source: https://docs.microsoft.com/en-us/advertising/guides/?view=bingads-13

There is a Singer tap [here](https://github.com/singer-io/tap-bing-ads) which works for this connector that we could build on top of.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368219345330) by [Unito](https://www.unito.io)

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)** 

no

**Available authentication modes (API key/Oauth/other)**

In this regard, it is rather difficult here. Bing Ads uses Oauth, but it can be configured in such a way that due to the `refresh_token` to constantly update access token and work with it.
This is described in more detail in this [article](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth?view=bingads-13).

However, using Bing Ads as a connector will require a lot of input to work with the API. 
For example, [Singer Tap](https://github.com/singer-io/tap-bing-ads) requires the following data to receive data:

```
{
  "developer_token": "<developer_token>",
  "customer_id": "<customer_id>",
  "oauth_client_secret": "<oauth_client_secret>",
  "oauth_client_id": "<oauth_client_id>",
  "refresh_token": "<refresh_token>",
  "account_ids": "<account_id_list>",
  "start_date": "2020-11-12T00:00:00Z"
}
```

**Creating an account**

_self-service free account available?_ I tried to create an account, but received the message "Account with this email already exists", and I just logged into the account using integration-test@airbyte.io as a login and password from Microsoft (I found it in Lastpass).

**How to populate the account with data?**

I found that the existing account already has a Campaign to work with.
However, I am not sure that it is possible to add Ads and AdGroups for free, perhaps it will require small material costs.

Also, We can use the Sandbox.

**Available streams for sync**

 * Campaign
 * AdGroup
 * Ad
 * AdvertiserAccount
 * Various Reports (e. g. KeywordPerformanceReport, AdPerformanceReport, AdGroupPerformanceReport,  GeographicPerformanceReport, AgeGenderAudienceReport and other)

**Integration supports incremental sync?**

Yes

**Other information/blockers**

It is difficult to initially configure the connector (to get all the config for its correct operation). 
I have not yet managed to fully configure it and test the correct operation of Singer Tap.

**Comment by yevhenii-ldv** [comment]
## Task breakdown
- [ ] Need to configure the application for Bing to get the corresponding client ID and client secret. And it is also necessary to generate all the tokens with which we can connect with Bing Ads API. (estimation ???, the documentation seems to indicate how this is done, but in reality it seems to be a rather time consuming task.)
- [ ] Populate source with data. (estimation 8h, because filling in the data of the Reports can take a long time). 
- [ ] Create source with all streams with full/incremental sync(using Singer Tap) (estimation 5h)
- [ ] Ensure that connector follows the best practices, rate limiting, retry call, proper error messages, has tests (estimation 4h).

**Comment by bruce-a-gitor** [comment]
One question we have about your upcoming Bing Ads release is whether it will have the ability to bring in the Product Dimension Performance Report? This is definitely a requirement for us and has been a long time shortcoming of Singer.

This Singer issue is the one I am referring to:  https://github.com/singer-io/tap-bing-ads/issues/23

**Comment by davinchia** [comment]
Note: when using the sandbox, I had to create a new account under integration-test@airbyte.io. No campaigns are populated.

**Comment by davinchia** [comment]
[This](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/authentication-oauth-identity-platform.md) is the most complete guide to Bing Authentication I found.

**Comment by sherifnada** [comment]
Deprioritized for the time bing due to bandwidth contstraints. Will update here as we revisit.

**Comment by cheyura** [comment]
Sandbox supports MSAs created using an outlook-int.com email account only. You may not use an outlook.com email account. Also, you may not use an email account from another email service (for example, @contoso.com) even if the account is linked to an outlook.com or outlook-int.com email account.
That why I ve created Yuri.Cherniaiev@outlook-init.com for testing ad campaign

**Comment by sherifnada** [comment]
@cheyura can you create MSA for sandbox integration-test@outlook-int.com and add the credentials to lastpass as "Microsoft Ads Integration Test account" ?

**Comment by cheyura** [comment]
> @cheyura can you create MSA for sandbox [integration-test@outlook-int.com](mailto:integration-test@outlook-int.com) and add the credentials to lastpass as "Microsoft Ads Integration Test account" ?
> 
> You should be able to sign into the existing account using the LP credential titled "Microsoft Integration Test Credentials"

@sherifnada Done and added

**Comment by midavadim** [comment]
Core streams (same as stitch data): 
    Accounts
    Ads
    Ad Groups

Report Streams (subset of Fivetran’s reports):
    Ad Performance Report       (horly, daily like in Fivetran)
    Ad Group Performance report (horly, daily like in Fivetran)
    Campaign performance report (horly, daily like in Fivetran)
    Keyword performance report  (horly, daily like in Fivetran)
    
    
Python bing ads client - bingads:
https://docs.microsoft.com/en-us/advertising/guides/get-started-python?view=bingads-13
pip install bingads

Python tutorial:
https://docs.microsoft.com/en-us/advertising/guides/walkthrough-desktop-application-python?view=bingads-13

SOAP based API
https://pypi.org/project/suds-jurko/ Lightweight SOAP client (Jurko's fork).



References:
Microsoft Docs: 
    https://docs.microsoft.com/en-us/advertising/guides/?view=bingads-13 
Stitch Data docs: 
    https://www.stitchdata.com/docs/integrations/saas/microsoft-advertising 
Fivetran docs: 
Report table schema: 
    https://fivetran.com/docs/applications/microsoft-advertising#reporttables
ERD for the connector: 
    https://docs.google.com/presentation/d/1xNeRCtU5dNVy01kTjE-ydX_BLoRDgKZOHGci1vUKDFg/edit#slide=id.g311502b468_5_443

**Comment by LuliRib** [comment]
Hi, I sync the basic streams from Bing Ads to in Airbyte and I get a lot of tables for each stream.

For example, for the ad_groups, I get 12 tables, as showm in the image. 

Can´t find anything about it in the documentation


![bingAds tables](https://user-images.githubusercontent.com/74010842/195549523-279716e3-a07c-4f5c-b7e9-8e74a3aeca5d.JPG)

**Comment by isisgoliveira** [comment]
Hello! 
I was able to authenticate to the API with the Bing Ads connector and select the desired report/stream. However, this ingestion is bringing cost/spend values ​​that do not exactly match those of the platform, they are just very close. I suspect that it may be a timezone issue.

Anyone who has had this problem or knows how the connector makes the request properly could help me?
