### ISSUE TITLE
[EPIC] Stream-Centric UI v2

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#25123]
## Frontend

```[tasklist]
- [ ] Views for per-stream and per-connection status
- [ ] Update `StreamStatusCard` to match designs
- [ ] Create volume-over-time chart
- [ ] Create connection/stream status history chart
- [ ] Add a _sync status_ column to `StreamStatusList` - "next sync in x", "X/Y records"
- [ ] Confirm/update connection-level message detection & display logic
- [ ] Allow individual streams to be reset and synced; allow those actions to be cancelled
- [ ] https://github.com/airbytehq/airbyte/issues/24584
- [ ] https://github.com/airbytehq/airbyte/issues/24587
- [ ] https://github.com/airbytehq/airbyte/issues/24601
```
