### ISSUE TITLE
connectors-ci: publish comment on PR with checklist

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#25382]
## Tell us about the problem you're trying to solve
We're about to change the process to test connectors on PR.
I suggest we share the process change to connector contributor via a comment automatically posted to a connector PR.

## Describe the solution you’d like
On connector PR opening I'd love a Dagger pipeline to run that would post a comment to the PR with the following content:
* Explain that /test and /publish are deprecated
* Explain that the CI should automatically test their changes
* Explain how connectors can be tested locally
* Share the checklist @bnchrch came up with:

```
### Before Merging a Connector Pull Request 

 Wow! What a great pull request you have here! 🎉 

 To merge this Connector please ensure the following has been done/considered:

- [x] Connector version has been incremented in the Dockerfile and metadata.yaml according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
- [x] If a **Breaking Change** is being introduced, ensure an Airbyte engineer has created a Breaking Change plan by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).
- [ ] If a **Breaking Change** is being introduced, merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Connector's `README.md` updated
- [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
- [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

If the checklist is complete, but the CI check is failing, toggle the `checklist-action-run` on/off to re-run the checklist.
```

## Technical details:

I think this automation should be handled by this [workflow](https://github.com/airbytehq/airbyte/blob/b405ba8178956d9a80b6084bf68068037b55b0eb/.github/workflows/connector_integration_test_single_dagger.yml).

This workflow should run on pull request open and pull request push.
I suggest to pass the webhook event to the dagger pipeline so that it decides what should run, this logic should not be in the GHA workflow itself.
Pseudocode In the dagger pipeline, in the `connectors test` command:
```
if ci:
  if pull_request_open:
    post_comment()
  if pull_request_ready_for_review:
    run test pipeline
```
