### ISSUE TITLE
Update LocalDefinitionsProvider to use registry files instead of definition.yml files

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25540]
## Overview

This is a large refactor to ANY java class that might reference the old catalog or old definition files

## TODO
- [x] Add ConnectorRegistryDownloader from platform
- [x] Remove CombinedConnectorCatalogGenerator.java
- [ ] Update LocalDefinitionProvider.java
- [ ] Update RemoteDefinitionProvider.java
- [x] Remove seedtype
