### ISSUE TITLE
Db sources retry framework

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#25551]
Database sources keep on failing on connection related issues but a retry in such cases could assist us. As part of this epic we need to 
- [ ] Document server level parameters for databases (such as idle timeouts, etc.) to configure for the user to make sure that the server is setup correctly 
- [ ] Identify and categorise exceptions which would fall into the bucket of retries in the code.
- [ ] Change our code to add retry logic whenever we see the above exceptions. We would have to make sure that when we retry we use a new connection and update the query with the offset to make sure that we fetch data from the point we fetched before exception occurred. For instance if we were able to read 3M records of total 11M records and then a retriable exception occurred, we should update the query to fetch the remaining data after the 3M records and not everything again.

**Comment by subodh1810** [comment]
Some instances of such exceptions are https://github.com/airbytehq/oncall/issues/1873
https://github.com/airbytehq/oncall/issues/1459
