### ISSUE TITLE
[EPIC] Source Pinterest: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26303]
### What area the feature impact?

Connectors

### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1c6H7UcPkmdZQZBeIIOJ76k_cFGbT_lovj6k6jQZ2p7M/edit?usp=share_link)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:
- [ ] Targeting analytics for an ad account
- [ ] Targeting analytics for ad groups
- [ ] Targeting analytics for ads
- [ ] Targeting options
- [ ] Keywords
- [ ] Account analytics report
