### ISSUE TITLE
[EPIC] Source Amazon Ads: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#26336]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1DhPeVBrqX371BXg8n_nIXKkQegqpwpr1yi8Bx2AG7P4/edit)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:

- [ ] BudgetRules
- [ ] Suggested keywords
- [ ] Campaign negative keywords
- [ ] Bid recommendations
- [ ] ThemeBasedBidRecommendation
- [ ]  Suggested keywords
- [ ] Negative product targeting
- [ ] Portfolios
- [ ] Advertised product reports
- [ ] Campaign reports
- [ ] Purchased product reports
- [ ] Search term reports
- [ ] Targeting reports
