### ISSUE TITLE
[EPIC] Source Google Search Console: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26586]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1LB7Bi6Zffue9STeMnwTA3POCnIQ3tFSQugb-ja8R-mE/edit?usp=sharing)

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:
- [ ] Keyword Page Report
- [ ] Keyword Site Report by page
- [ ] Keyword Site Report by site
- [ ] Page Report
- [ ] Site Report by page
- [ ] Site Report by site
