### ISSUE TITLE
[Epic] CDC enabled database sources to specify source defined cursor

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#27338]
### What area the feature impact?

Connectors

### Revelant Information

Epic created for CDC enabled database sources to specify source defined cursor. 

```[tasklist]
### Tasks
- [x] https://github.com/airbytehq/airbyte/issues/27340
- [ ] https://github.com/airbytehq/airbyte/issues/27341
- [ ] https://github.com/airbytehq/airbyte/issues/26807
- [ ] https://github.com/airbytehq/airbyte/issues/29528
```

```[tasklist]
### Tasks
```
