### ISSUE TITLE
Publish Java CDK for DB-type Source connectors

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/airbyte#28445]
Internal tech spec doc: https://docs.google.com/document/d/11VAFxQJt8UXLAsAKnxfZMjUqoXylHvkaBRxspEU4pcU/edit#heading=h.fa72b39y2m99

This would add a CDK for Java connectors. First priority will be to support Source DBs. Future scope may also expand to include destination DB connectors.

## Minimal P1 Scope

```[tasklist]
### Tasks
- [x] Publish "no-op" v0.0.1 Java CDK to Maven repository.
- [ ] https://github.com/airbytehq/airbyte/issues/28481
- [ ] https://github.com/airbytehq/airbyte/issues/28483
- [ ] https://github.com/airbytehq/airbyte/issues/28480
- [ ] https://github.com/airbytehq/airbyte/issues/28482
- [ ] https://github.com/airbytehq/airbyte/pull/28687
```

## P2 Scope (follow-ons, when time allows)

```[tasklist]
### Tasks
- [ ] Migrate all source connectors to depend on pinned CDK references.
- [ ] Create a CDK v0.2 that tackles some initial refactoring, removal of unused classes, etc.
- [ ] Migrate destination connectors to CDK if they have a dependency on included CDK classes.
- [ ] Tutorials, videos, other content creation efforts.
```

**Comment by prateekmukhedkar** [comment]
@aaronsteers can we create this as an epic?

**Comment by aaronsteers** [comment]
@prateekmukhedkar - Done. Link here: https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/gh/airbytehq/airbyte/29316

**Comment by prateekmukhedkar** [comment]
This work is tracked by the epic https://github.com/airbytehq/airbyte/issues/29316
