### ISSUE TITLE
Java CDK - Phase 1 (`v0.0.1`-`v0.1.0`)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/airbyte#29316]
This epic covers the following definition of done regarding the new Java CDK:

1. [ ] The CDK can be effectively **developed alongside connectors** which depend upon it, within a single PR.
   - [ ] Java connectors have working CI test flow, including the running of tests which rely on yet-unreleased changes to the CDK.
   - [ ] The CLI for `airbyte-ci connectors test|build` work locally as expected, incorporating unreleased CDK changes when needed.
1. [ ] The CDK has an automated or semi-automated **publish flow** and is accessible via our public Maven repo.
1. [ ] The CDK has appropriate **documentation** covering how to work with it in the following ways:
   - [ ] How to build/test the CDK.
   - [ ] How to develop a connector which relies on unreleased changes to the CDK.
   - [ ] How to publish new versions of the CDK.
   - [ ] Assuming a common IDE, show how developers can inspect a connector's pinned version of the CDK code when it does not align with what is in the local branch. (IntelliJ required, VS Code optional.)

**Comment by akashkulk** [comment]
Closing this
