### ISSUE TITLE
New Source: Presta Shop

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2980]
## Tell us about the new integration you’d like to have
popular open source shopfront platform https://github.com/PrestaShop/PrestaShop/

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368161212651) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
## Integration Vetting

[PrestaShop](https://github.com/PrestaShop/PrestaShop/) is an Open Source e-commerce web application, which is written in PHP.

**Server configuration**

The first stable version of PrestaShop 1.7, 1.7.0.0, was released on November 7th, 2016. Further [updates](https://build.prestashop.com/tag/1.7/) have been released since then.

To [install](https://github.com/PrestaShop/PrestaShop/#server-configuration) the latest PrestaShop 1.7, we need a web server running PHP 7.1+ and any flavor of MySQL 5.0+ (MySQL, MariaDB, Percona Server, etc.). Versions between 1.7.0 and 1.7.6 work with PHP 5.6+.

PrestaShop enables merchants to give third-party tools access to their shop’s database through a CRUD API, otherwise called a [web service](https://devdocs.prestashop.com/1.7/webservice/).

By default, the webservice feature is disabled on PrestaShop and needs to be [switched on](https://devdocs.prestashop.com/1.7/webservice/tutorials/creating-access/#enable-the-webservice) before the first use.

**Webhook-based? (no/partially/yes)**

No

**Available authentication modes (API key/Oauth/other)**

[Access key](https://devdocs.prestashop.com/1.7/webservice/tutorials/creating-access/#create-an-access-key)

**Connecting to the data source**

The PrestaShop web service uses the REST architecture

[Testing access to the Webservice ](https://devdocs.prestashop.com/1.7/webservice/tutorials/testing-access/)

**Creating an account**

Instance deployment is required.

**How to populate the account with data?**

It can be done entirely through the API or through the UI.

**Available streams for sync**

The Webservices can output [JSON](https://devdocs.prestashop.com/1.7/webservice/tutorials/testing-access/#json-format) resource schemas

[Available resources](https://devdocs.prestashop.com/1.7/webservice/reference/#available-resources)

- [Addresses](https://devdocs.prestashop.com/1.7/webservice/resources/addresses/)
- [Attachments](https://devdocs.prestashop.com/1.7/webservice/resources/attachments/)
- [Carriers](https://devdocs.prestashop.com/1.7/webservice/resources/carriers/)
- [Cart rules](https://devdocs.prestashop.com/1.7/webservice/resources/cart_rules/)
- [Carts](https://devdocs.prestashop.com/1.7/webservice/resources/carts/)
- [Categories](https://devdocs.prestashop.com/1.7/webservice/resources/categories/)
- [Combinations](https://devdocs.prestashop.com/1.7/webservice/resources/combinations/)
- [Configurations](https://devdocs.prestashop.com/1.7/webservice/resources/configurations/)
- [Contacts](https://devdocs.prestashop.com/1.7/webservice/resources/contacts/)
- [Content management system](https://devdocs.prestashop.com/1.7/webservice/resources/content_management_system/)
- [Countries](https://devdocs.prestashop.com/1.7/webservice/resources/countries/)
- [Currencies](https://devdocs.prestashop.com/1.7/webservice/resources/currencies/)
- [Customer messages](https://devdocs.prestashop.com/1.7/webservice/resources/customer_messages/)
- [Customer threads](https://devdocs.prestashop.com/1.7/webservice/resources/customer_threads/)
- [Customers](https://devdocs.prestashop.com/1.7/webservice/resources/customers/)
- [Customizations](https://devdocs.prestashop.com/1.7/webservice/resources/customizations/)
- [Deliveries](https://devdocs.prestashop.com/1.7/webservice/resources/deliveries/)
- [Employees](https://devdocs.prestashop.com/1.7/webservice/resources/employees/)
- [Groups](https://devdocs.prestashop.com/1.7/webservice/resources/groups/)
- [Guests](https://devdocs.prestashop.com/1.7/webservice/resources/guests/)
- [Image types](https://devdocs.prestashop.com/1.7/webservice/resources/image_types/)
- [Images](https://devdocs.prestashop.com/1.7/webservice/resources/images/)
- [Languages](https://devdocs.prestashop.com/1.7/webservice/resources/languages/)
- [Manufacturers](https://devdocs.prestashop.com/1.7/webservice/resources/manufacturers/)
- [Messages](https://devdocs.prestashop.com/1.7/webservice/resources/messages/)
- [Order carriers](https://devdocs.prestashop.com/1.7/webservice/resources/order_carriers/)
- [Order cart rules](https://devdocs.prestashop.com/1.7/webservice/resources/order_cart_rules/)
- [Order details](https://devdocs.prestashop.com/1.7/webservice/resources/order_details/)
- [Order histories](https://devdocs.prestashop.com/1.7/webservice/resources/order_histories/)
- [Order invoices](https://devdocs.prestashop.com/1.7/webservice/resources/order_invoices/)
- [Order payments](https://devdocs.prestashop.com/1.7/webservice/resources/order_payments/)
- [Order slip](https://devdocs.prestashop.com/1.7/webservice/resources/order_slip/)
- [Order states](https://devdocs.prestashop.com/1.7/webservice/resources/order_states/)
- [Orders](https://devdocs.prestashop.com/1.7/webservice/resources/orders/)
- [Price ranges](https://devdocs.prestashop.com/1.7/webservice/resources/price_ranges/)
- [Product customization fields](https://devdocs.prestashop.com/1.7/webservice/resources/product_customization_fields/)
- [Product feature values](https://devdocs.prestashop.com/1.7/webservice/resources/product_feature_values/)
- [Product features](https://devdocs.prestashop.com/1.7/webservice/resources/product_features/)
- [Product option values](https://devdocs.prestashop.com/1.7/webservice/resources/product_option_values/)
- [Product options](https://devdocs.prestashop.com/1.7/webservice/resources/product_options/)
- [Product suppliers](https://devdocs.prestashop.com/1.7/webservice/resources/product_suppliers/)
- [Products](https://devdocs.prestashop.com/1.7/webservice/resources/products/)
- [Search](https://devdocs.prestashop.com/1.7/webservice/resources/search/)
- [Shop groups](https://devdocs.prestashop.com/1.7/webservice/resources/shop_groups/)
- [Shop urls](https://devdocs.prestashop.com/1.7/webservice/resources/shop_urls/)
- [Shops](https://devdocs.prestashop.com/1.7/webservice/resources/shops/)
- [Specific price rules](https://devdocs.prestashop.com/1.7/webservice/resources/specific_price_rules/)
- [Specific prices](https://devdocs.prestashop.com/1.7/webservice/resources/specific_prices/)
- [States](https://devdocs.prestashop.com/1.7/webservice/resources/states/)
- [Stock availables](https://devdocs.prestashop.com/1.7/webservice/resources/stock_availables/)
- [Stock movement reasons](https://devdocs.prestashop.com/1.7/webservice/resources/stock_movement_reasons/)
- [Stock movements](https://devdocs.prestashop.com/1.7/webservice/resources/stock_movements/)
- [Stocks](https://devdocs.prestashop.com/1.7/webservice/resources/stocks/)
- [Stores](https://devdocs.prestashop.com/1.7/webservice/resources/stores/)
- [Suppliers](https://devdocs.prestashop.com/1.7/webservice/resources/suppliers/)
- [Supply order details](https://devdocs.prestashop.com/1.7/webservice/resources/supply_order_details/)
- [Supply order histories](https://devdocs.prestashop.com/1.7/webservice/resources/supply_order_histories/)
- [Supply order receipt histories](https://devdocs.prestashop.com/1.7/webservice/resources/supply_order_receipt_histories/)
- [Supply order states](https://devdocs.prestashop.com/1.7/webservice/resources/supply_order_states/)
- [Supply orders](https://devdocs.prestashop.com/1.7/webservice/resources/supply_orders/)
- [Tags](https://devdocs.prestashop.com/1.7/webservice/resources/tags/)
- [Tax rule groups](https://devdocs.prestashop.com/1.7/webservice/resources/tax_rule_groups/)
- [Tax rules](https://devdocs.prestashop.com/1.7/webservice/resources/tax_rules/)
- [Taxes](https://devdocs.prestashop.com/1.7/webservice/resources/taxes/)
- [Translated configurations](https://devdocs.prestashop.com/1.7/webservice/resources/translated_configurations/)
- [Warehouse product locations](https://devdocs.prestashop.com/1.7/webservice/resources/warehouse_product_locations/)
- [Warehouses](https://devdocs.prestashop.com/1.7/webservice/resources/warehouses/)
- [Weight ranges](https://devdocs.prestashop.com/1.7/webservice/resources/weight_ranges/)
- [Zones](https://devdocs.prestashop.com/1.7/webservice/resources/zones/)

**Do any streams support incremental sync?**

We can [filter](https://devdocs.prestashop.com/1.7/webservice/tutorials/advanced-use/additional-list-parameters/#filter-parameter) the expected result with the filter parameter

Some resources have date_add and date_upd, but they are optional.

**Preparation scope & blockers**

Instance deployment is required.

**Other information/blockers**

Singer Tap isn't available.

**Comment by keu** [comment]
look at this https://hub.docker.com/r/prestashop/prestashop/

**Comment by vitaliizazmic** [comment]
**Are the account test credentials available in Lastpass?**

Account test credentials doesn't available in Lastpass. To work with Source we can deploy instance locally using Docker [image](https://hub.docker.com/r/prestashop/prestashop/).

## Task breakdown
- [ ] Populate source with data -  fake data can be populated while installing PrestaShop instance.
- [ ] Create source scaffolding and populate schemas folder - API returns schemas for each resources but in XML format. - 5-6h
- [ ] Implement spec, check, and discover - 1-2h
- [ ] Implement Read
    - [ ] Create API base abstract class 
	- [ ] Create Base stream abstract classes 6-8h
	- [ ] Implement base abstract classes for incremental streams 5-7h
- [ ] Handle rate limiting - 3-4h
- [ ] Implement standard tests - 2-3h

**Comment by sherifnada** [comment]
@vitaliizazmic just seeing this now -- can we support just a subset of the available streams to start with? Just want to make sure we keep the scope of the PR manageable and add more endpoints as users request them. Streams that seem like the most valuable: 

* Contacts
* Customers
* Carts
* Employees
* Orders
* Order invoices
* Order histories
* Order Details
* Products
* Shops
* Suppliers
* Stocks
* Stock Movements
* Taxes

If you have already implemented others we can keep those (no need to throw them away) but hopefully this can help focus the scope
