### ISSUE TITLE
Add analytics message stub for tracking

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#31497]
Allow tracking how often syncs with the new unstructured parser are run in all file-based sources to track success of the project

* [x] Release new protocol models with this change: https://github.com/airbytehq/airbyte-protocol/pull/45
* [ ] Add platform handling to log these messages when encountered https://github.com/airbytehq/airbyte-platform-internal/pull/9307
* [ ] Create issue for creating proper platform implementation
* [ ] Use in connectors supporting unstructured parser to get telemetry insights https://github.com/airbytehq/airbyte/pull/31498

**Comment by flash1293** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/31498 and https://github.com/airbytehq/airbyte-platform-internal/pull/9307
