### ISSUE TITLE
[Investigate] High-leverage DB Sources to non-legacy state

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#32827]
- [x] [Stop saving empty state of LEGACY type if the connector doesn't emit a state](https://github.com/airbytehq/airbyte/issues/22945)
- [ ] [Stop emitting LEGACY state from JDBC connectors ](https://github.com/airbytehq/airbyte/issues/33290)
- [ ] [Stop emitting state from API connectors](https://github.com/airbytehq/airbyte/issues/33291)
- [ ] [Verify that the state table in prod db is not getting any new entires with LEGACY state](https://github.com/airbytehq/airbyte/issues/33292)
- [ ] [Clean up database i.e. clean state table with LEGACY state + change the default option in the state table for state_type column from LEGACY to PER-STREAM](https://github.com/airbytehq/airbyte/issues/33293)
- [ ] [Delete code related to the LEGACY state from connectors and platform](https://github.com/airbytehq/airbyte/issues/33294)
