### ISSUE TITLE
[sources] Tech Spec: adding counts in AirbyteStateMessage

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#32912]
Tech spec doc[in draft]:
https://docs.google.com/document/d/14Qg_lXMzMvMO5oP0RYIe11JIwuCzR9QexcEaSiPJKEk/edit

We want to fill the new field `sourceStats` in AirbyteStateMessage. In the state message we will fill in how many rows we have emitted along with the state.

DoD:
A tech spec specifying where to make the changes. and/or A list of implementation tickets with estimation.
```[tasklist]
### Tasks
- [ ] https://github.com/airbytehq/airbyte/issues/33088
- [ ] Platform to support airbyte-protocol 0.5.0
- [ ] https://github.com/airbytehq/airbyte/issues/33090
- [ ] https://github.com/airbytehq/airbyte/issues/33089
- [ ] https://github.com/airbytehq/airbyte/issues/25756
```

**Comment by xiaohansong** [comment]
Initial draft: https://docs.google.com/document/d/1U6jetOPIvf6CbFP56eG_0DZ_HmHmV-JzJ_kVeInKVPI/edit
