### ISSUE TITLE
Use `pnpm` with docusaurus

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#33921]
We use `pnpm` to finagle all of our `package.json` dependencies outside of docusaurus, which still uses `yarn`. We should migrate this as well, to consolidate on a single tool.

- [X] delete `yarn.lock`, replace with `pnpm-lock.yaml` (automatically generated when installing packages with `pnpm`)
- [X] ~update `package.json` scripts to reference `pnpm` instead of `yarn`~ N/A
- [X] update `docusaurus/README.md` with the new installation and development commands
- [X] update vercel build config to auto-detect package manager based on lockfile instead of hardcoding `yarn`

```[tasklist]
### Tasks
```
