### ISSUE TITLE
[EPIC] Source Chargebee: Silver Certification

### ISSUE THREAD

**Issue by pnilan** [airbytehq/airbyte#35022]
### Relevant information

Enhance Source Chargebee to meet Silver Certification requirements.

### Resources
[Source Chargebee: Certification Checklist](https://docs.google.com/spreadsheets/d/1_dF6QI82odqcNxUkScVkNnfIq0j90ZzQLZgd39d89uk/edit?usp=sharing)
[Chargebee ML](https://docs.google.com/document/d/1yRDI1VItRqDfNKMQukqv0kr4Gx6cgh4Oh_Xh5LnxNo4/edit?usp=sharing)
[Stream Party Sheet](https://docs.google.com/spreadsheets/d/1ngC8A0Pbl9okJGn_oWk9B2kmO3IKdtRurhw_aLVSfZI/edit?usp=sharing)
[Chargebee Stream Profile sheet](https://docs.google.com/spreadsheets/d/1ij0hSltYTf6kVFb_iBzyWU1jrPP8MEouKNcgbyBtTxE/edit?usp=sharing)

Remaining Tasks (as of 2/8/24):

- [ ]  Develop Integration testing for untested streams: `event`, `addon`, `plan`, `virtual_bank_account`, `event`, `site_migration_detail`.
- [ ] Update Schemas for missing fields and field validation
- [ ] Update streams to support incremental sync: `unbilled_charge`, `gift`, `site_migration_detail`
