### ISSUE TITLE
New source: airbyte-native Github connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3695]
## Tell us about the new connector you’d like to have
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. The new connector should have complete feature parity with the existing singer-based one. Once this is complete we should delete the singer-based connector and replace it with the new one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200395747714452) by [Unito](https://www.unito.io)

**Comment by Zirochkaa** [comment]
**Are the account test credentials available in Lastpass?**
yes

## Task breakdown

- [ ] Create source scaffolding and populate schemas folder (3h)
- [ ] Implement `spec`, `check`, and `discover` (4h)
- [ ] Implement `read` command for all (16) streams in full_refresh mode (8h)
- [ ] Add pagination (4h)
- [ ] Compare schemas from `source-github-singer` and actual responses and update schemas if needed (6h)
- [ ] Implement `read` command for incremental streams (16h)
- [ ] Configure acceptance tests (8h)

**Comment by Moofasax** [comment]
looking forward to trying this out!! will there be a new release created today?

**Comment by Zirochkaa** [comment]
> looking forward to trying this out!! will there be a new release created today?

@Moofasax 

Sorry for such a late reply.

We just merged this connector into master and released a new version of the connector.

The connector will be available in the next release of Airbyte (we usually release every Tuesday). If you can't wait and want to get started now trying it out in a running Airbyte instance, add the connector like described in https://docs.airbyte.io/integrations/custom-connectors#adding-your-connectors-in-the-ui . The information for the connector is: 

**Display Name**: GitHub
**Docker repository name**: airbyte/source-github
**Docker image tag**: 0.1.0
**Documentation URL**: hub.docker.com/r/airbyte/source-github

Please let us know if you have any further questions. 

Enjoy!
