### ISSUE TITLE
ClickUp source: add `Time Tracking` stream

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/airbyte#44178]
## Connector Name
source-clickup

## ❓ What
The ClickUp connector does not include Time Tracking information, which retrieves information about time entries.

## 📈  Impact
Users can use the time entry information in ClickUp

## 🤝 Proposed solution
Add a new stream `time_tracking` using the endpoint: hhttps://clickup.com/api/clickupreference/operation/Gettimeentryhistory/
(Optional) Add a new stream `time_tracking_tags` using the endpoint: https://clickup.com/api/clickupreference/operation/Getalltagsfromtimeentries/

```[tasklist]
### Tasks
- [x] Source ClickupApi: Add streams `time_tracking`, `time_tracking_tags`, `team_goals`, `space_tags`, `team_custom_fields`, `list_custom_fields`, `list_comments`
- [x] Source ClickupApi: Add error handlers
- [x] Source ClickupApi: Fix parent child flow
```
