### ISSUE TITLE
🚀 New Source: Cart.com 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4588]
## Tell us about the new connector you’d like to have
We'd like to support the [Cart.com](https://developers.cart.com/docs/rest-api/docs/README.md) API for the following endpoints: 

* [Customers Cart](https://developers.cart.com/docs/rest-api/restapi.json/paths/~1customers/get)
* [Orders](https://developers.cart.com/docs/rest-api/restapi.json/paths/~1orders/get)
* [Order Payments](https://developers.cart.com/docs/rest-api/restapi.json/paths/~1order_payments/get)
* [Products](https://developers.cart.com/docs/rest-api/restapi.json/paths/~1products/get)

**Note: we are already in contact with and will get access to sandbox credentials from Cart.com very soon**

**Comment by keu** [comment]
## Integration Vetting
**Webhook-based? no**

**Available authentication modes ** (API key/Oauth)

**Connecting to the data source** (REST)

**Creating an account**
The client will provide...

**How to populate the account with data?**
All top-level streams can be populated via API with POST.

**Available streams for sync**
https://developers.cart.com/docs/rest-api/docs/resource_list.md

**Do any streams support incremental sync?**
All top-level streams support filtering by ts_updated

**Are the account test credentials available in Lastpass?** Not yet

## Task breakdown
- [ ] Populate source with data (4h)
- [ ] Create source scaffolding and populate schemas folder (2h)
- [ ] Implement spec, check and discover (4h)
- [ ] Implement Read (full and incremental since all of them are incremental) (8h)
- [ ] Handle [rate limiting](https://developers.cart.com/docs/rest-api/docs/README.md#rate-limiting) (2h)
- [ ] Implement standard tests (2h)
- [ ] Implement custom tests for incremental (i.e. update record and incrementally read, since all streams are stable) (2h)

Total: 24h
