### ISSUE TITLE
[EPIC] Publish OSS jars

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5053]
This issue is an epic that tracks various tasks around jar publishing in OSS. Each task will be (or already is) its own issue.
- [x] - With each new release of OSS, each module in OSS should publish a new version of a jar to maven.
- [x] - Cloud should depend only on the Jars it needs (right now it just depends on server to slurp up all other dependencies)
- [x] - Handle issue where jar names in Cloud and OSS conflict leading to really odd errors ([issue](https://github.com/airbytehq/airbyte/issues/5188))
- [x] - OSS should be able to publish a jar (locally) from a branch that cloud can depend on. In other words, cloud should be able to access java code that has not been released yet. This will be useful for development of features on Cloud that depend on unreleased java changes in OSS.

**Comment by davinchia** [comment]
@jrhizor and I were talking today and he feels that using snapshots might cause more harm than good from the shifting nature of snapshot. e.g. Snapshot is initially at git hash `a` and works fine for the local Cloud repo. Another dev merges to master and causes the snapshot to advance to git hash `b`. This merge breaks the local Cloud work, leaving the engineer confused.

One alternative is to use git hashes. I do like this. The problem this causes is clean up. CloudRepo charges by storage instead of network and the plan I think we should get is 150 bucks/month for 100GB of storage. We roughly push around 200mbs per 
'version' today, that's around 500 version before we have to start clean up. Should be pretty doable if there is an api we can hit - we can insert a script that is run on master to check this with every push to master. I'm checking with their support on api availability.

We could also bite the bullet and go with Snapshot for now, with clear instructions around what to do if things start being wonky i.e. use mavenLocal instead.

Any thoughts @ChristopheDuong, as person who currently feels this pain the most? fyi @cgardens

**Comment by davinchia** [comment]
Follow up question for ya Chris, is it possible to use bump version to insert arbitrary git hashes/snapshot versions? Or is that not really supported by the tool.

**Comment by ChristopheDuong** [comment]
https://github.com/peritus/bumpversion/issues/125

**Comment by ChristopheDuong** [comment]
Even if bumpversion doesn't support it natively, I am guessing you could run a `git rev-parse HEAD` command (from the CI script?) to print the git hash into for example the `.bumpversion.cfg` to be used in a `replace` option:

![Screenshot 2021-07-29 at 11 27 07](https://user-images.githubusercontent.com/7718175/127467814-3d0beefa-737e-4d27-9a55-a94dfe973571.png)

Maybe you'd need to combine this to using `--allow-dirty` flag

**Comment by ChristopheDuong** [comment]
If we have a publish when releasing a new version of airbyte (+ link it with https://github.com/airbytehq/airbyte/issues/5047)

and have local ability to rebuild/publish locally the jar (for when I am working on a custom branch on airbyte to be used in the other repo too) then we don't need this SNAPSHOT publish from master (it'd be bonus)

**Comment by ChristopheDuong** [comment]
When building/publishing airbyte repo locally, you could probably just build the jars with the current git hash as version (replacing the .env version variable, not using bumpversion)

then when building airbyte-cloud repo, you also need to overwrite the VERSION variable to point to the git hash you desire
