### ISSUE TITLE
Airbyte Cloud: Usage Tracking UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5448]
## Tell us about the problem you're trying to solve
[Mock up](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26991%3A93697)

- [ ] this is currently blocked because we do not have API for setting / getting credits information
- [ ] this is currently blocked because we do not expose these usage metrics in the UI
- [ ] should the calculation logic in the cost calculator be in the FE or BE?

**Comment by timroes** [comment]
Closing as this has been implemented.
