### ISSUE TITLE
[Epic] Code coverage

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#5961]
- [x] https://github.com/airbytehq/airbyte/issues/3689

Python

- [x] https://github.com/airbytehq/airbyte/issues/5960
- [x] https://github.com/airbytehq/airbyte/issues/3686
- [ ] #7948 7948

Java

- [ ] https://github.com/airbytehq/airbyte/issues/474
