### ISSUE TITLE
Epic: fix connector's schema related failures  

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5972]
Schema related failures:

- [x] #5974
- [x] #5975
- [x] #5976
- [ ] source gitlab - fix schema related failure
- [ ] source google-adwords-singer - fix schema related failure
- [ ] source google-search-console-singer - fix schema related failure
- [x] source google-sheets - fix schema related failure
- [ ] source harvest - fix schema related failure
- [ ] source klaviyo - fix schema related failure
- [ ] source okta - fix schema related failure
- [ ] source pipedrive - fix schema related failure
- [ ] source posthog - fix schema related failure
- [ ] source quickbooks-singer - fix schema related failure
- [ ] source sendgrid - fix schema related failure
- [ ] source slack - fix schema related failure
- [x] source smartsheets - fix schema related failure
- [ ] source surveymonkey - fix schema related failure
- [ ] source tempo - fix schema related failure
- [ ] source twilio - fix schema related failure
- [ ] source zendesk-sunshine - fix schema related failure

**Comment by YiyangLi** [comment]
@midavadim Hey, I am here to see if I can help to fix the schema for source-okta. 

https://github.com/airbytehq/airbyte/pull/14380#discussion_r913389077

Is it related to the json schema validator in python? I am curious about other broken schema failures on okta, if you are willing to share.

**Comment by lazebnyi** [comment]
Fixed
