### ISSUE TITLE
Epic: fix connector's tests

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5978]
Epic: fix connector's tests
- [ ] source cart: fix test failures
- [ ] source dixa: fix test failures
- [ ] source facebook-marketing: fix test failures
- [ ] source jdbc: fix test failures
- [ ] source prestashop : fix test failures
- [ ] source scaffold-java-jdbc: fix test failures
- [ ] source snapchat-marketing: fix test failures
- [ ] source stripe: fix test failures
- [ ] source zendesk-support: fix test failures
- [ ] source square: fix test failures
