### ISSUE TITLE
Epic: fix connector's creds related failures:

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5979]
Epic: fix connector's creds related failures:
- [ ] source appsflyer-singer: fix creds related failure
- [ ] source python-http-tutorial: fix creds related failure
- [ ] source scaffold-source-http: fix creds related failure
- [ ] source scaffold-source-python: fix creds related failure
- [ ] source stock-ticker-api-tutorial: fix creds related failure
- [ ] source zuora: fix creds related failure
