### ISSUE TITLE
[EPIC] Complete Temporal Migration

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6906]
## Tell us about the problem you're trying to solve
Our goal is to remove our own scheduler logic and replace it entirely with temporal. This epic will track the various tasks that go into this project.

## Tasks
- [ ] - (tech spec) https://github.com/airbytehq/airbyte/issues/6905
- [ ] - https://github.com/airbytehq/airbyte/issues/2170

## Old Tasks
The following are tasks that we have accumulated that relate to temporal. As part of this epic, we should decide if these are still important. If they are likely we should close them as part of the epic. If they are no longer relevant, let's close them!
- [ ] - https://github.com/airbytehq/airbyte/issues/2386
- [ ] - https://github.com/airbytehq/airbyte/issues/2387
- [ ] - https://github.com/airbytehq/airbyte/issues/3142
- [ ] - https://github.com/airbytehq/airbyte/issues/3943

**Comment by cgardens** [comment]
done. cron string tracked separately.
