### ISSUE TITLE
Remove legacy migration system

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6917]
## Tell us about the problem you're trying to solve
Before @tuliren implemented migrations with Flyway we used a file based migration system. Keeping the system around is painful because it adds a lot of complexity to the start up sequence of the server app. It generally makes it difficult or blocks making that app HA.

## Plan
What we want to do is change the contract on our migrations. We theoretically allow a user to migrate from any old version of Airbyte to any new version, right now. Instead we propose having a user run two upgrades if they are migrating a great distance. For example, imagine we have Airbyte versions 1-10. We would say that if you are on a version below 5 (say 2) and you want to upgrade to version 10, you must first upgrade from 2 to 5. Then once your migration to 5 is complete, you can upgrade again to version 10.

What this allows us to do is to remove the legacy migration system after version 5. The trade off is that the user has to do an extra upgrade if they are upgrading from a really ancient version.

## Tasks
- [x] - Make sure that if a user is trying to upgrade past the transition version that we throw an exception with clear instructions on what they want to do
- [x] - Document the two step upgrade
- [ ] - After whatever version we do this on, delete the legacy migration system (this includes removing file system persistence and file migration)

**Comment by cgardens** [comment]
all code is written for this. we will release it either today or monday. still a little testing in the release process that needs to happen.
