### ISSUE TITLE
[EPIC] Implement OAuth Flow for Cloud connectors

### ISSUE THREAD

**Issue by avida** [airbytehq/airbyte#7000]
## What
Currently we have a lot of connectors with defined oAuth workflow but there is still no oAuth backend implemented. Now 2 different teams are developing a common list of oAuth connectors. The main goal of this epic is synchronization between them. And everyone can use it for understanding of current statuses of connectors' development. 

### Prioritized scoping:
SurveyMonkey
WooCommerce
Marketo
Pixpanel
Freshdesk
Cart.com
BigCommerce
QuickBooks
Prestashop
Posthog
Pinterest

### Handled by GL team:
- [x] (connector) airbytehq/airbyte#6258 (backend) airbytehq/airbyte#7079
- [ ] (connector) airbytehq/airbyte#6282 (backend) airbytehq/airbyte#7080
- [x] (connector) airbytehq/airbyte#6257 (backend) airbytehq/airbyte#7243
- [x] (connector) airbytehq/airbyte#6261 (backend) airbytehq/airbyte#7353
- [x] (connector) airbytehq/airbyte#7482 (backend by ZZM) airbytehq/airbyte#7511
- [x] airbytehq/airbyte#7314
  - [x] connector
  - [ ] backend
- [x] airbytehq/airbyte#7482
  - [x] connector
- [x] airbytehq/airbyte#7708
  - [x] connector
  - [ ] backend
- [x] airbytehq/airbyte#7704 
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7706  
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7484
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7814 
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7707   
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7709 
  - [x] connector
  - [x] backend
- [ ] airbytehq/airbyte-internal-issues#325  
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#6285
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#6289
  - [x] connector
  - [x] backend
- [x] airbytehq/airbyte#6273
  - [x] connector
  - [x] backend
- [ ] airbytehq/airbyte#6294
  - [x] connector
  - [ ] backend
- [x] airbytehq/airbyte#7480
  - [ ] connector
  - [ ] backend
- [ ] airbytehq/airbyte-internal-issues#307 
  - [x] connector by ZZM airbytehq/airbyte#6271
  - [x] connector
  - [ ] backend
- [x] airbytehq/airbyte#6280
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#8008 
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7098
  - [x] connector
  - [x] backend
- [x] airbytehq/airbyte#7709
  - [x] connector
  - [x] backend
- [x] airbytehq/airbyte#7704
  - [x] connector
  - [x] backend
- [x] airbytehq/airbyte#7754
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7814
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#7906
  - [ ] connector
  - [ ] backend 
- [x] airbytehq/airbyte#8007
  - [x] connector
  - [x] backend
- [x] airbytehq/airbyte#8008
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#8223
  - [ ] connector
  - [ ] backend
- [x] airbytehq/airbyte#10002
  - [ ] connector
  - [ ] backend
### Handled by ZZM team:
- [x]  (backend) source-facebook-pages  airbytehq/airbyte#7109
- [x]  (backend) source-google-search-console
- [ ]  (backend) source-lever-hiring  airbytehq/airbyte#7110
- [x]  (backend) source-salesforce   airbytehq/airbyte#7111
- [x]  (connector) #? (backend) source-asana    airbytehq/airbyte#7051
- [x]  (backend) source-zuora    airbytehq/airbyte#7112
- [x]  (backend) source-google-analytics-v4
- [x]  (backend) source-hubspot   airbytehq/airbyte#7113
- [x]  (backend) source-google-ads
- [x]  (backend) source-github    airbytehq/airbyte#7114
- [x]  (backend) source-facebook-marketing
- [x]  (backend) source-instagram  airbytehq/airbyte#7115
- [x]  (backend) source-slack  airbytehq/airbyte#7116
---
_Next sprint connectors (for ZZM):_
- [ ] airbytehq/airbyte#7508
- [ ] airbytehq/airbyte#7509
- [x] airbytehq/airbyte#7510
- [x] airbytehq/airbyte#7512
- [x] airbytehq/airbyte#7513
- [x] airbytehq/airbyte#7511
---
_Finish python implementation and add java backend:_
- [ ] source-tempo (#7282)  airbytehq/airbyte#7514
- [x] source-gitlab (#7263)   airbytehq/airbyte#7515
- [ ] source-okta (#7262)    airbytehq/airbyte#7516
---

**Comment by terekete** [comment]
Is there a oauth2 flow source connector for Big Query ?
