### ISSUE TITLE
[EPIC] Implement OAuth Flow for Cloud connectors(duplicate)

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#7341]
## Tell us about the problem you're trying to solve
We want to implement OAuth Flow for all existing connectors.
Currently, Airbyte Cloud already supports GoogleOAuthFlow.

Here is the list of connectors that should support OAuth:

### Basic OAuth Connectors in priority order: 

- [ ] #7079
- [ ] #7080
- [ ] #7314
- [ ] #7353
- [ ] Oauth Server Flow: Asana
- [ ] Oauth Server Flow: SurveyMonkey
- [ ] Oauth Server Flow: Pipedrive
- [ ] #7482
- [ ] .....

### Extended OAuth Connectors in priority order: 
- [ ] #7243
- [ ] #6285
- [ ] #6289
- [ ] #6273
- [ ] #6294
- [ ] Zendesk Sunshine
- [ ] WooCommerce
- [ ] Marketo
- [ ] Mixpanel
- [ ] Freshdesk
- [ ] #7480
- [ ] Cart.com
- [ ] BigCommerce
- [ ] #7481
- [ ] Okta
- [ ] Posthog
- [ ] Prestashop

## Describe the solution you’d like
Go through each connector in the basic list. Implement Java part of the OAuth flow and cover the logic with appropriate unit/integration tests.

The acceptance criteria for each ticket is: 

- [ ] Check out the connector branch which should contain a Python part.
- [ ] Set up local dev environment according to this [doc](https://docs.google.com/document/d/1YQ1S47Lpf3up6dsWHpxx7pmjf3tiVgRbdLOplUS4cOQ/edit#)
- [ ] Create a new class `<Connector>OAuthFlow.java` which should extend the BaseOAuthFlow.
- [ ] Introduce the class described in the previous step in the OAuthImplementationFactory.
- [ ] Write unit tests to cover basic OAuth flow.
- [ ] Update the Dockerfile and bump the version if needed.
- [ ] Create a PR

## Implementation hints
There is a difference when implementing this for basic and extended flow because extended flow requires some additional params to be passed from the UI.

**When implementing this for basic flow**, it's probably as simple as adding an additional OAuth flow implementation to the factory and covering that implementation with tests.

**When implementing for extended flow** it might be very similar, but we should generate authorization/redirect/access URLs dynamically and validate the input params on BE.

[This PR](https://github.com/airbytehq/airbyte/pull/7313) contains an example of adding Zendesk OAuth flow.

**important note**: until the next [PR](https://github.com/airbytehq/airbyte/pull/7280) is merged, please only focus on the 'basic' connectors list. The reason is that we are still working out how to pass additional params from the UI in the appropriate way. I will update here once we do.

**Comment by antixar** [comment]
merged with #7000
