### ISSUE TITLE
[EPIC] Normalize Database Schema

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#7867]
- [x]  https://github.com/airbytehq/airbyte/issues/8438
- [x] https://github.com/airbytehq/airbyte/issues/8439
- [x] https://github.com/airbytehq/airbyte/issues/8441
- [x] https://github.com/airbytehq/airbyte/issues/8442
- [x] https://github.com/airbytehq/airbyte/issues/8444
 - [x] https://github.com/airbytehq/airbyte/issues/8446
  - [x] https://github.com/airbytehq/airbyte/issues/8449
  - [x] https://github.com/airbytehq/airbyte/issues/8451 ( this is good to have, not necessary to mark the completion of the project. Would be a good first issue for someone new on the team)

**Comment by cgardens** [comment]
various notes: https://docs.google.com/document/d/1tUTmnrqIH95cAsu9q7LltkhkGNJhl02k2zsvMLfA4c4/edit
