### ISSUE TITLE
Integrate airbyte repo with SonarQube

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#7881]
## Tell us about the problem you're trying to solve

Many issues we have nowadays can be avoided even with static analysis. 

We're going to evaluate the code quality using [SonarQube](https://www.sonarqube.org/). Using that tool we would be able to see all connectors' info in one place and have a good overview of the project code quality.

## Describe the solution you’d like

We're going to generate the SonarQube analytics, base on our tests, pylint and other inner code analytics tools.

To do that we need to implement the following steps:
- Fix github CI to make each job run proper and stable (for now it could fail with unknown reasons, so we could not rely on it).
- Paste together all possible code validation reports (such as pylint, unit tests, flake etc.) and generate the SonarQube assessments based on it. So we don't need to run the code evaluation from the SonarQube itself, just pass the reports there.

### Subtasks

- [x] Search the modules which were changed in PR
- [x] Integrate https://github.com/airbytehq/airbyte/pull/8873 static code checkers
- [x] Update static code checkers to allow building the reports appliable to SonarQube
- [x] Build reports for the modules found
- [x] Update PR after https://github.com/airbytehq/airbyte/pull/8873 is merged
- [x] Add unit tests for each module

## Describe the alternative you’ve considered or used
No alternative with given flow

**Comment by antixar** [comment]
Follow up issue https://github.com/airbytehq/airbyte-cloud/issues/659.
This task has to close posible security variabilities in the future.
About the future SonarQube projects. The Airbyte repo is aggregation of several stacks, languages and services. And one project will be not enough. I propose to classify projects by language and functional target:
1. Airbyte Python Connectors
2. Airbyte Java Connectors
3. Airbyte WebApp
4. Airbyte Server 
5. Airbyte Workers
etc
Every project will have own properties and test scenarios.

**Comment by htrueman** [comment]
As were discussed, we should implement the following flow:
- Search the modules which were changed in PR. E.g. assume that `airbyte-cdk/python/airbyte_cdk/logger.py` and `airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py` were changed. That would mean the `airbyte-cdk` and `airbyte-integrations/connectors/source-salesforce` should be found.
- Build reports for the modules found in prev step in separate github action.
- Pass these module to the SonarQube project for the following module.
- Show SonarQube analytics results on the github PR page as a comment (similar to SAT results shown now).
