### ISSUE TITLE
[EPIC] Audit Logging

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#8120]
## Tell us about the problem you're trying to solve
* As technical support or OC engineering, I want to be able to review when updates to configuration happened to better understand the root cause of bugs.
* As a user, I want to know when configuration was changed to understand unexpected behavior.
* As a security-focused user, I want to know when and WHO changed configuration for security and compliance purposes.

## Describe the solution you’d like
* Each configuration change should be logged. It should include who did it, when, and what the change was.

## Approach
* use SQL triggers to track changes to config tables. we must be able to implement these triggers _without_ making any application code changes.
* incrementally update application code to pass in `updated_by` information
* build UI / API / retool on top of it

### Steps
- [x] airbytehq/airbyte#11900 
- [ ] https://github.com/airbytehq/airbyte-internal-issues/issues/1098
- [ ] https://github.com/airbytehq/airbyte-internal-issues/issues/1099
- [ ] migrate the rest of the configs

**Comment by cgardens** [comment]
@erica-airbyte I think this issue gets at what we were discussing the other day. Please add if you feel I've missed anything.

**Comment by joshuataylor** [comment]
This would be great, could it also sync into a destination as well? Other tools sync their log into the destination you have setup, such as Snowflake.

**Comment by erica-airbyte** [comment]
@cgardens That looks good to me! I think you hit the most important pieces (who did it, when the change happened, and the before and after snapshot). This would be so awesome!
