### ISSUE TITLE
[EPIC] Metrics tracking for connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8400]
Issues derived from google document: [Measuring Connector Reliability](https://docs.google.com/document/d/1HdsL6SZFzHmsvnW3OWN4dX7XMhnMjLACBtoaqeYAocQ/edit#)

## context
- [x] #8638

## Security

- [x] https://github.com/airbytehq/airbyte/issues/7881
- [ ] https://github.com/airbytehq/airbyte/issues/3513

## Data Integrity

- [ ] https://github.com/airbytehq/airbyte/issues/8587 
- [ ] https://github.com/airbytehq/airbyte/issues/8588

## Data Availability
- [ ] https://github.com/airbytehq/airbyte/issues/8590
- [ ] https://github.com/airbytehq/airbyte/issues/8591

## Consistency of Sync & fault tolerance
- [x] https://github.com/airbytehq/airbyte/issues/4342
- [x] https://github.com/airbytehq/airbyte/issues/3595
- [ ] https://github.com/airbytehq/airbyte/issues/8593
- [x] https://github.com/airbytehq/airbyte/issues/8594
- [x] https://github.com/airbytehq/airbyte/issues/8595 
- [x] https://github.com/airbytehq/airbyte/issues/8596

## Code stability / maturity
- [ ] https://github.com/airbytehq/airbyte/issues/7956 / https://github.com/airbytehq/airbyte/issues/2148

## Load Speed
- [ ]

## Ease of use
- [ ]

## Popularity
- [ ]

**Comment by keu** [comment]
I think integration with Sentry should be here as well

**Comment by sherifnada** [comment]
@ChristopheDuong we should probably have an issue here for creating the analytics github project as well no?
