### ISSUE TITLE
Setup analytics project for tracking metrics

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8638]
Discover the current state of the analytics stack at Airbyte and setup the initial repository to centralize the Airbyte warehouse construction

**Comment by sherifnada** [comment]
next steps: 
- [ ] finalize the percentile computations
- [ ] determine next action items (e.g: put in a "real" dashboard, add alerts, etc..) 
- [ ] hand off to the right owner

**Comment by ChristopheDuong** [comment]
Project started at https://github.com/airbytehq/airbyte-warehouse/
