### ISSUE TITLE
Salesforce: Succeed the sync if the daily rate limit is reached

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8690]
## Tell us about the problem you're trying to solve
Salesforce has a daily rate limit (by default, 15k requests per day). If a sync reaches this rate limit there is no use in `sleep`ing, because we would need to sleep for a very long time (the rate limit resets every 24 hours). 

## Describe the solution you’d like
I would like the sync from salesforce to "early succeed" if it reaches the rate limit, and pick up from where it left off the next day. 
also this should be mentioned in the docs, that the connector uses as much rate limit as it can every day then ends the sync early and continues the next time

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by Zirochkaa** [comment]
# Scoping

Am mentioned in the ticket description, right now if salesforce connector reaches daily limit, it will get 403 status code and `errorCode=REQUEST_LIMIT_EXCEEDED` in the response body. If code sees that then it sleeps for some amount of seconds.
Instead, if the daily rate limit is reached we should save the current state and end the sync for all streams. It will work only for incremental streams.

There are two implementations of `read_records()` function with which we can work:
- `SalesforceStream.read_records()`;
- `BulkSalesforceStream.read_records()`.

We can also look at `SourceSalesforce.read()` function because it seems like there we can catch `REQUEST_LIMIT_EXCEEDED` error and stop reading for all streams.

We also need to make sure that both BULK and REST versions are working.

## Task breakdown:

- [ ] Add tests for `REQUEST_LIMIT_EXCEEDED` error (if this does not exist yet);
- [ ] Implement this for REST version;
- [ ] Implement this for BULK version.

**Comment by augan-rymkhan** [comment]
1. In REST API stream 403 status code (Rate Limit) is not backed off, because [should_retry](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py#L236) returns False. 
**Solution**: The exception HTTPError (403) will be handled [here](https://github.com/airbytehq/airbyte/pull/9499/files#diff-0572edeedd561901f8110c0f88b48efde87d1ed91247c0eb189c7229da12090dR104).
2.
