### ISSUE TITLE
[EPIC] Report failure stack traces via sentry

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9104]
## Description
The goal of this ticket is to ensure that we are able to receive stack traces from failing connectors (OSS and Cloud) in Sentry.

## TODOs
- [x] [P0] Integrate Sentry to GA Java destination connectors.
  - https://github.com/airbytehq/airbyte/issues/9328
  - https://github.com/airbytehq/airbyte/issues/9533
- [ ] [P0] Integrate Sentry to GA Python source connectors.
    - This is partially completed. But not every Python connector exception is sent to Sentry yet.
- [ ] [P1] Inject any needed env variables to the connector.
    - Move the environment variable to .env.
    - Propagate the variable to worker and the connector.
- [x] [P1] Enable [suspect commits](https://docs.sentry.io/product/releases/setup/) feature on Sentry.
  - Add Sentry release when publishing a connector
- [ ] [P2] Set an environment to distinguish production from dev
- [ ] [P2] Integrate Sentry to all other destination connectors.
  - https://github.com/airbytehq/airbyte/issues/9867
- [ ] [P2] Integrate Sentry to all other source connectors.
- [x] [P0] Publish new connector versions with Sentry enabled.
  - [x] `destination-e2e-test` https://github.com/airbytehq/airbyte/pull/9940
  - [x] `destination-dev-null` https://github.com/airbytehq/airbyte/pull/9940
  - [x] `source-e2e-test`
  - [x] `source-e2e-test-cloud`
  - [x] `destination-bigquery` https://github.com/airbytehq/airbyte/pull/9945
  - [x] `destination-bigquery-denormalized` https://github.com/airbytehq/airbyte/pull/9945
  - [x] `destination-snowflake` https://github.com/airbytehq/airbyte/pull/9945

## Acceptance criteria
- All GA connector exceptions, from both OSS and Cloud, will be sent to Sentry.

## Timeline
- P0 issues: Jan 28th.

## Reference
- Related tickets can be found [here](https://github.com/airbytehq/airbyte/issues?q=is%3Aissue+is%3Aopen+sentry)

**Comment by sherifnada** [comment]
@augan-rymkhan @VasylLazebnyk apologies for the confusion -- this should be a platform issue

**Comment by tuliren** [comment]
This has been delegated to GL. It is already tracked here: https://github.com/airbytehq/airbyte/issues/9328

**Comment by tuliren** [comment]
## Sprint Summary
- Made solid progress on integrating Sentry with Java destination.
- MVP should be ready by the end of this week.

**Comment by tuliren** [comment]
## Sprint Summary

- Sentry integration is not completely done as planned.
- Local test of Sentry integration works as expected.
- Still working on deploying it to cloud.

**Comment by tuliren** [comment]
## Sprint summary

- Stack trace and performance monitoring is working for Snowflake and BigQuery on Sentry now.

## Next step

- [P0] Activate Sentry for Python GA connectors.
- [P2] Propagate env variable properly. The current approach is hacky. But this is working, so the priority is low.

**Comment by tuliren** [comment]
Close because we will integration with Datadog instead of Sentry.
