### ISSUE TITLE
[EPIC] Improve Snowflake destination to satisfy General Availability criteria

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9352]
## Tell us about the problem you're trying to solve
GA criteria [described here](https://docs.google.com/document/d/1q9ncTSja4pZFJYEEs_AQ6NKOJOrMzcWq7KSyHCx4lPw/edit#heading=h.apstagek5t8o) require that a connector achieve a good degree of reliability. This epic is a placeholder for any work required to improve the Snowflake destination such that it achieves GA status. Some things to keep in mind: 

1. Measurement & visibility: we'll need to have a way to measure how well this connector is doing in the wild, and some sort of error reporting to reliably make improvements. These are captured by the following issues https://github.com/airbytehq/airbyte/issues/9328 and https://github.com/airbytehq/airbyte/issues/8638
2. Absent measurement & visibility we could look at open issues for guidance, including [snowflake's recommended best practices](https://github.com/airbytehq/airbyte/issues/4904)

## Describe the solution you’d like
Snowflake in GA

**Comment by sherifnada** [comment]
next steps:

- [ ] catalogue all open issues, determine which ones need to happen for GA
- [ ] sync up w liren about the benchmark work and whether it overlaps for snowflake GA
- [ ] other items to figure out what is needed to get Snowflake into GA
- [ ]

**Comment by subodh1810** [comment]
Next step issues : 
 - [ ] https://github.com/airbytehq/airbyte/issues/9602
 - [ ] https://github.com/airbytehq/airbyte/issues/9607
 - [ ] https://github.com/airbytehq/airbyte/issues/9615
 - [ ] https://github.com/airbytehq/airbyte/issues/9614
 - [ ] https://github.com/airbytehq/airbyte/issues/9603 - If this is not too much work then only included
