### ISSUE TITLE
[EPIC] Connector Analytics follow ups

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#9479]
## Tell us about the problem you're trying to solve
Following-up on https://github.com/airbytehq/airbyte/issues/8624

- [x] Exclude internal airbyte accounts from analytics
- [x] Allow filtering based on values in the config e.g: exclude all Bigquery destinations which use `INSERT` 
  - [x] #9618
- [ ] Exclude connectors failing due to user error https://github.com/airbytehq/airbyte/issues/9350
- [ ] #9473
- [x] https://github.com/airbytehq/airbyte/issues/9476

## Describe the solution you’d like
Connections from airbyte team should be ignored

**Comment by sherifnada** [comment]
@ChristopheDuong removing from milestone since it's an epic, we should instead add subtickets to the. milestone

**Comment by ChristopheDuong** [comment]
@sherifnada can we close this issue and use https://github.com/airbytehq/airbyte/issues/10328 instead?
