### ISSUE TITLE
[EPIC] API source benchmarks

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9538]
## Summary

This epic covers all issues to create benchmarks to measure the correctness and performance of GA API sources, including the following APIs:
- Salesforce
- Google Ads
- Hubspot
- Shopify
- Github
- Stripe
- Intercom

## TODOs
- [ ] https://github.com/airbytehq/airbyte/issues/9104
- [ ] Create API source benchmark account and connections on cloud
- [ ] Create local benchmark runs for API sources
- [ ] [Optional] Add a `performanceTest` command on CI for API sources
