### ISSUE TITLE
[EPIC] Refactor Secrets Handling

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9646]
## Tell us about the problem you're trying to solve
We should audit our handling of secrets anywhere they are present in code. The goal is identify everywhere in the codebase where secrets are access and that our handling meets our desired security posture. This project is focused on de-risking areas where it would be easy for a developer to make a mistake about secrets.

## Describe the solution you’d like
[Spec](https://docs.google.com/document/d/1heFYlM3c2a4y_r5UtjcCkWPuNSUqYmxgXCinAlgTnBg/edit#)

## Execution Plan
- [x] https://github.com/airbytehq/airbyte/issues/9946
- [x] https://github.com/airbytehq/airbyte/issues/9947
- [x] https://github.com/airbytehq/airbyte/issues/11095
- [x] https://github.com/airbytehq/airbyte/issues/9948
- [x] https://github.com/airbytehq/airbyte/issues/11604
- [ ] https://github.com/airbytehq/airbyte/issues/9949
- [ ] https://github.com/airbytehq/airbyte/issues/9950
- [ ] _potentially others after the initial audit_

**Comment by cgardens** [comment]
relates to: https://github.com/airbytehq/airbyte/issues/7391

**Comment by anand-srinivaas** [comment]
+ 1.

- If there is an option to extend external secret services like cloud secret managers or vault, will be very much helpful!
- Appreciate if this can be done in this quarter :) 

Thanks

**Comment by cgardens** [comment]
@anand-srinivaas thanks for your note! I have updated this issue so that the scope of it is more clear. This issue is focused on refactoring secrets code. 

We actually already support GCP Secrets Manager([docs](https://docs.airbyte.com/operator-guides/configuring-airbyte#secrets)). I have created a separate issue https://github.com/airbytehq/airbyte/issues/10519 to add support for HashiCorp Vault. I don't think we will be able to devote time to Vault this quarter, but we are open to contribution here. If someone can implement the `SecretsPersistence` class with Vault, we can bring it the rest of the way home.

**Comment by cgardens** [comment]
@olivermeyer can you speak a little more about what outcome you'd like. do simply want the the db to be encrypted at rest or are you specifically looking for credentials values to be specifically encrypted?

**Comment by olivermeyer** [comment]
> @olivermeyer can you speak a little more about what outcome you'd like. do simply want the the db to be encrypted at rest or are you specifically looking for credentials values to be specifically encrypted?

@cgardens I am familiar with the Airflow model (which may or may not be a common way of going about this, I don't know): secret values are encrypted in the DB and decrypted with a key which is generated when the Airflow installation is first started ([doc](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html)). To spell it out, this means that even if someone somehow accesses the DB, they still see our secrets.

Right now, if someone gains access to our Airbyte DB, they will also get access to most system to which Airbyte connects. That's a problem.

Does this make sense?

**Comment by cgardens** [comment]
Closing as the projects we care about for this quarter are complete. The remaining open issues will be prioritized and handled separately.
