### ISSUE TITLE
[EPIC] Scope connection definitions by workspace

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9652]
## Tell us about the problem you're trying to solve
We want to allow different workspaces to do a few different things:
1. Use _different_ versions of the _same_ connector definitions. (e.g. workspace 1 uses postgres 0.11.1 and workspace 2 uses 0.12.0)
2. Use _different_ connectors entirely (e.g. workspace 1 has access to custom connector A and workspace 2 doesn't OR workspace 1 has access to alpha connector X and workspace 2 doesn't)
3. A workspace admin is able to change the connector versions and add custom connectors
4. An instance admin is able to change connector versions and add connectors for any workspace.
5. Ability to mark connectors that by _default_ are provisioned to all workspaces
6. Ability to mark connectors that _not_ provisioned by default but can be provisioned by an instance admin

## Describe the solution you’d like
[Tech Spec](https://docs.google.com/document/d/1KfJiTKZnBIUr1CFHUbi-8LjByRh03bheX6TQnuWlZyY/edit?usp=sharing) for API changes

Implemented in:
- [x] airbytehq/airbyte#11244
- [x] airbytehq/airbyte#11305
- [x] airbytehq/airbyte#11330
- [x] airbytehq/airbyte#11336
- [x] airbytehq/airbyte#11338
- [x] airbytehq/airbyte#11339

<details>
  <summary>New endpoints added</summary>

| oss | cloud |
|-----|-------|
| `/v1/source_definitions/list_private`  | :white_check_mark: admin only |
| `/v1/source_definitions/list_for_workspace` | :white_check_mark: workspace reader |
| `/v1/source_definitions/get_for_workspace` | :white_check_mark: workspace reader |
| `/v1/source_definitions/create_custom` | :no_entry: unimplemented |
| `/v1/source_definitions/update_custom` | :no_entry: unimplemented |
| `/v1/source_definitions/delete_custom` | :no_entry: unimplemented |
| `/v1/source_definitions/grant_definition`  | :white_check_mark: admin only |
| `/v1/source_definitions/revoke_definition`  | :white_check_mark: admin only |
| | |
| `/v1/destination_definitions/list_private`  | :white_check_mark: admin only |
| `/v1/destination_definitions/list_for_workspace` | :white_check_mark: workspace reader |
| `/v1/destination_definitions/get_for_workspace` | :white_check_mark: workspace reader |
| `/v1/destination_definitions/create_custom` | :no_entry: unimplemented |
| `/v1/destination_definitions/update_custom` | :no_entry: unimplemented |
| `/v1/destination_definitions/delete_custom` | :no_entry: unimplemented |
| `/v1/destination_definitions/grant_definition`  | :white_check_mark: admin only |
| `/v1/destination_definitions/revoke_definition`  | :white_check_mark: admin only |

</details>

## Remaining Tasks
Here are the remaining steps to get scoped connection definitions working in cloud (that should be done in order):
- [x] uptake the changes in cloud and allow cloud users to use the new get/list endpoints for workspace scoped definitions https://github.com/airbytehq/airbyte-cloud/pull/1311
- [x] https://github.com/airbytehq/airbyte/issues/11606
- [x] https://github.com/airbytehq/airbyte/issues/11607 (should be done together with the previous step)
- [ ] https://github.com/airbytehq/airbyte-cloud/issues/1335
- [x] ensure admins can access the endpoints for listing private connector definitions and granting/revoking connector definitions to workspaces https://github.com/airbytehq/airbyte-cloud/pull/1312
- [ ] https://github.com/airbytehq/airbyte-cloud/issues/1336
- [x] airbytehq/airbyte-cloud#1869

**Comment by cgardens** [comment]
@pmossman I updated this issue to be a bit less vague. lmk if you have other questions.

**Comment by git-phu** [comment]
After all of the above PRs are merged, we should have all the schema and API changes necessary for supporting scoped connectors.
So the remaining steps would be to:

- [ ] uptake the changes in cloud and allow cloud users to use the new get/list endpoints for workspace scoped definitions (can be done as part of this ticket)
- [ ] update the webapp to use the new workspace scoped endpoints for CRUD/list of connector definitions
- [ ] create a migration to convert all existing custom connector definitions in oss deployments to be correctly configured as custom definitions based on the new schema changes (should be done together with the previous step)
- [ ] uptake the webapp changes in cloud and restrict the non-scoped get/list definition endpoints to admin only
- [ ] ensure admins can access the endpoints for listing private connector definitions and granting/revoking connector definitions to workspaces (also can be done as part of this ticket)
- [ ] provide a ui for admins to create and view private connector definitions and grant them to workspaces

**Comment by cgardens** [comment]
de-prioritized for Q2. not blocked.

**Comment by pmossman** [comment]
Ongoing work towards custom connectors is now captured in a new epic: https://github.com/airbytehq/airbyte-cloud/issues/3079
