### ISSUE TITLE
[EPIC] OC Debugging tool: replay syncs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9659]
## Tell us about the problem you're trying to solve
https://github.com/airbytehq/airbyte-cloud/issues/855

* [x] https://github.com/airbytehq/airbyte/issues/10247
* [x] https://github.com/airbytehq/airbyte/issues/10248
* [ ] https://github.com/airbytehq/airbyte/issues/10249
